### ISSUE TITLE
Can you provide more information about inheritance and Superclasses?

### ISSUE THREAD

**Issue by Glurt** [requery/requery#107]
I have a base class that defines common columns that many entities will have, it looks like this:

````  
@Superclass
public abstract class Thing implements Persistable {

    @Key
    public String id;

    @Column(unique = true)
    public String name;
    @Column
    public String kind;
    @Column
    public DateTime created;
    @Column
    public DateTime created_utc;
}
````

I then have some entities defined like so: 

````
@Entity
public abstract class AbstractAccount extends Thing {
 
    //Auth
    String accessToken;
    String refreshToken;
}
````

What I'm trying to do is check whether or not an account exists when the app firsts loads and creates one if not, however `datastore.count(Account.class).get().value()` returns 1. I can uninstall the app and it will still say 1.

Since the app detects an account it attempts to load it but crashes due to
`Caused by: android.database.sqlite.SQLiteException: no such column: id (code 1):`

Am I missing something or doing something wrong?

**Comment by npurushe** [comment]
That looks like it should work fine. I would verify that 1) in the generated Account class you have all the columns you expect and 2) When you run the app and the tables are created you see in the log that the create table statement has all the columns. (Logging is enabled with `DatabaseSource.setLoggingEnabled(true)`)

**Comment by Glurt** [comment]
I've enabled logging but I'm not sure if it's working, here's how I'm building the datastore

````
@Provides
    @Singleton
    SingleEntityStore<Persistable> provideDataStore(Application context) {
        final EntityModel model = Models.DEFAULT;
        final DatabaseSource databaseSource = new DatabaseSource(context, model, DataStoreConstants.DATASTORE_VERSION);
        databaseSource.setLoggingEnabled(true);
        final Configuration configuration = new ConfigurationBuilder(databaseSource, model)
                .setMapping(new CustomMapping(new SQLite()))
                .useDefaultLogging()
                .build();

        //Create the tables
        new SchemaModifier(configuration).createTables(TableCreationMode.CREATE_NOT_EXISTS);
        return RxSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
    }
````
I've tried removing the .useDefaultLogging() and creating the tables but the outcome is still the same. Here is the stacktrace 

> 04-21 11:08:32.347 5186-5186/com.cooper.redditvideo W/System: ClassLoader referenced unknown path: /data/app/com.cooper.redditvideo-1/lib/arm
04-21 11:08:36.664 5186-5186/com.cooper.redditvideo W/System: ClassLoader referenced unknown path: /data/app/com.cooper.redditvideo-1/lib/arm
04-21 11:08:37.502 5186-5186/com.cooper.redditvideo I/requery: beforeExecuteUpdate {0} sql:
                                                               {1}
04-21 11:08:37.503 5186-5186/com.cooper.redditvideo I/requery: afterExecuteUpdate
04-21 11:08:37.503 5186-5186/com.cooper.redditvideo I/requery: beforeExecuteUpdate {0} sql:
                                                               {1}
04-21 11:08:37.503 5186-5186/com.cooper.redditvideo I/requery: afterExecuteUpdate
04-21 11:08:37.505 5186-5186/com.cooper.redditvideo I/requery: beforeExecuteUpdate {0} sql:
                                                               {1}
04-21 11:08:37.506 5186-5186/com.cooper.redditvideo I/requery: afterExecuteUpdate
04-21 11:08:37.507 5186-5186/com.cooper.redditvideo I/requery: beforeExecuteUpdate {0} sql:
                                                               {1}
04-21 11:08:37.507 5186-5186/com.cooper.redditvideo I/requery: afterExecuteUpdate
04-21 11:08:37.521 5186-5186/com.cooper.redditvideo I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
04-21 11:08:37.724 5186-5186/com.cooper.redditvideo I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
04-21 11:08:37.738 5186-5186/com.cooper.redditvideo I/requery: beforeExecuteQuery {0} sql:
                                                               {1}
04-21 11:08:37.743 5186-5186/com.cooper.redditvideo I/requery: afterExecuteQuery
04-21 11:08:37.882 5186-5186/com.cooper.redditvideo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
04-21 11:08:38.213 5186-5186/com.cooper.redditvideo D/HomePresenterImpl: Loading current account
04-21 11:08:38.222 5186-5186/com.cooper.redditvideo E/SQLiteLog: (1) no such column: id
04-21 11:08:38.225 5186-5186/com.cooper.redditvideo D/AndroidRuntime: Shutting down VM
04-21 11:08:38.227 5186-5186/com.cooper.redditvideo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.cooper.redditvideo, PID: 5186
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cooper.redditvideo/com.cooper.redditvideo.app.presentation.ui.home.HomeActivity}: android.database.sqlite.SQLiteException: no such column: id (code 1): , while compiling: select id, accessToken, comment_karma, created, created_utc, deviceId, gold_creddits, gold_expiration, has_mail, has_mod_mail, has_verified_email, hide_from_robots, inbox_count, isAnonymous, isLoggedIn, is_gold, is_mod, is_suspended, kind, link_karma, name, over_18, refreshToken, suspension_expiration_utc from Account where isLoggedIn = ?
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: android.database.sqlite.SQLiteException: no such column: id (code 1): , while compiling: select id, accessToken, comment_karma, created, created_utc, deviceId, gold_creddits, gold_expiration, has_mail, has_mod_mail, has_verified_email, hide_from_robots, inbox_count, isAnonymous, isLoggedIn, is_gold, is_mod, is_suspended, kind, link_karma, name, over_18, refreshToken, suspension_expiration_utc from Account where isLoggedIn = ?
                                                                          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                          at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                          at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                          at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                          at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                          at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994)
                                                                          at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38)
                                                                          at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:162)
                                                                          at io.requery.android.sqlite.BaseConnection.prepareStatement(BaseConnection.java:148)
                                                                          at io.requery.sql.SelectResult.createStatement(SelectResult.java:82)
                                                                          at io.requery.sql.SelectResult.iterator(SelectResult.java:107)
                                                                          at io.requery.query.BaseResult.iterator(BaseResult.java:111)
                                                                          at io.requery.query.BaseResult.firstOr(BaseResult.java:92)
                                                                          at io.requery.query.BaseResult.firstOrNull(BaseResult.java:102)
                                                                          at com.cooper.redditvideo.app.data.disk.DiskRepository.getCurrentAccount(DiskRepository.java:40)
                                                                          at com.cooper.redditvideo.app.data.manager.AccountManager.getCurrentAccount(AccountManager.java:199)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomePresenterImpl.loadCurrentAccount(HomePresenterImpl.java:36)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomePresenterImpl.onInitialise(HomePresenterImpl.java:28)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomeActivity.onCreate(HomeActivity.java:66)
                                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by npurushe** [comment]
Hi it's not necessary to call `createTables` yourself on Android. The `DatabaseSource` class handles since it extends SQLiteOpenHelper. However make sure you are increasing DataStoreConstants.DATASTORE_VERSION when you change the schema, or clear the app's data and run it again, that's most likely the cause of your missing column.

**Comment by Glurt** [comment]
I'll remove the createTables call, I thought that perhaps the crash was due to the tables not being present before I was querying them. I've been using the ADB Idea plugin for Android Studio to clear the data and uninstall rather than incrementing the version number.

I've tried running it on an emulator and it's working perfectly. It's still crashing on my N5 though, even after uninstalling so I tried increasing the version number and got this:

> 04-21 15:48:19.977 8707-8707/com.cooper.redditvideo I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.sql.ManagedTransaction>
04-21 15:48:20.269 8707-8707/com.cooper.redditvideo I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
04-21 15:48:20.331 8707-8707/com.cooper.redditvideo I/requery: beforeExecuteUpdate io.requery.android.sqlite.SqliteStatement@3843234 sql: create table if not exists Submission (id varchar(255) primary key, approved_by varchar(255), author varchar(255), author_flair_text varchar(255), banned_by varchar(255), clicked boolean not null, created varchar(255), created_utc varchar(255), distinguished varchar(255), domain varchar(255), downs integer not null, gilded integer not null, hidden boolean not null, is_self boolean not null, kind varchar(255), likes boolean, link_flair_text varchar(255), media varchar(255), name varchar(255) unique, num_comments integer not null, num_reports integer not null, over_18 boolean not null, permalink varchar(255), preview varchar(255), saved boolean not null, score integer not null, selftext varchar(255), selftext_html varchar(255), stickied boolean not null, subreddit varchar(255), subreddit_id varchar(255), thumbnail varchar(255), title varchar(255), ups integer not null, url varchar(255), videoId varchar(255), visited boolean not null)
04-21 15:48:20.331 8707-8707/com.cooper.redditvideo I/requery: afterExecuteUpdate
04-21 15:48:20.332 8707-8707/com.cooper.redditvideo I/requery: beforeExecuteUpdate io.requery.android.sqlite.SqliteStatement@3843234 sql: create table if not exists Account (id varchar(255) primary key, accessToken varchar(255), comment_karma integer not null, created varchar(255), created_utc varchar(255), deviceId varchar(255), gold_creddits integer not null, gold_expiration varchar(255), has_mail boolean not null, has_mod_mail boolean not null, has_verified_email boolean not null, hide_from_robots boolean not null, inbox_count integer not null, isAnonymous boolean not null, isLoggedIn boolean not null, is_gold boolean not null, is_mod boolean not null, is_suspended boolean not null, kind varchar(255), link_karma integer not null, name varchar(255) unique, over_18 boolean not null, refreshToken varchar(255), suspension_expiration_utc varchar(255))
04-21 15:48:20.333 8707-8707/com.cooper.redditvideo I/requery: afterExecuteUpdate
04-21 15:48:20.336 8707-8707/com.cooper.redditvideo I/requery: beforeExecuteUpdate io.requery.android.sqlite.SqliteStatement@a89de85 sql: alter table Account add column name varchar(255) unique 
04-21 15:48:20.336 8707-8707/com.cooper.redditvideo E/SQLiteLog: (1) Cannot add a UNIQUE column
04-21 15:48:20.350 8707-8707/com.cooper.redditvideo D/AndroidRuntime: Shutting down VM
04-21 15:48:20.360 8707-8707/com.cooper.redditvideo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.cooper.redditvideo, PID: 8707
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cooper.redditvideo/com.cooper.redditvideo.app.presentation.ui.home.HomeActivity}: rx.exceptions.OnErrorNotImplementedException: java.sql.SQLException: android.database.sqlite.SQLiteException: Cannot add a UNIQUE column (code 1): , while compiling: alter table Account add column name varchar(255) unique
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: rx.exceptions.OnErrorNotImplementedException: java.sql.SQLException: android.database.sqlite.SQLiteException: Cannot add a UNIQUE column (code 1): , while compiling: alter table Account add column name varchar(255) unique
                                                                          at rx.Single$8.onError(Single.java:1421)
                                                                          at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
                                                                          at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                          at rx.Single$1$1.onError(Single.java:105)
                                                                          at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:37)
                                                                          at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)
                                                                          at rx.Single$1.call(Single.java:110)
                                                                          at rx.Single$1.call(Single.java:90)
                                                                          at rx.Single.subscribe(Single.java:1586)
                                                                          at rx.Single.subscribe(Single.java:1412)
                                                                          at com.cooper.redditvideo.app.data.manager.AccountManager.checkForAnonymousAccount(AccountManager.java:61)
                                                                          at com.cooper.redditvideo.app.data.manager.AccountManager.<init>(AccountManager.java:49)
                                                                          at com.cooper.redditvideo.app.data.DataModule.provideAccountManager(DataModule.java:72)
                                                                          at com.cooper.redditvideo.app.data.DataModule_ProvideAccountManagerFactory.get(DataModule_ProvideAccountManagerFactory.java:31)
                                                                          at com.cooper.redditvideo.app.data.DataModule_ProvideAccountManagerFactory.get(DataModule_ProvideAccountManagerFactory.java:11)
                                                                          at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
                                                                          at com.cooper.redditvideo.app.presentation.di.DaggerApplicationComponent.accountManager(DaggerApplicationComponent.java:101)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.DaggerHomeComponent$3.get(DaggerHomeComponent.java:56)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.DaggerHomeComponent$3.get(DaggerHomeComponent.java:54)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomeModule_ProvidePresenterFactory.get(HomeModule_ProvidePresenterFactory.java:28)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomeModule_ProvidePresenterFactory.get(HomeModule_ProvidePresenterFactory.java:8)
                                                                          at dagger.internal.ScopedProvider.get(ScopedProvider.java:46)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomeActivity_MembersInjector.injectMembers(HomeActivity_MembersInjector.java:26)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomeActivity_MembersInjector.injectMembers(HomeActivity_MembersInjector.java:8)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.DaggerHomeComponent.inject(DaggerHomeComponent.java:69)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomeActivity.setupComponent(HomeActivity.java:57)
                                                                          at com.cooper.redditvideo.app.presentation.ui.common.BaseActivity.onCreate(BaseActivity.java:50)
                                                                          at com.cooper.redditvideo.app.presentation.ui.home.HomeActivity.onCreate(HomeActivity.java:62)
                                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                      	... 9

**Comment by npurushe** [comment]
Ok the problem is:
`E/SQLiteLog: (1) Cannot add a UNIQUE column`

Unfortunately you cannot add a column with a unique column to an existing table. If you clear your apps data it will work fine but If you have actually released the app you have to think about an upgrade schema for handling this case or remove the unique qualifier.

**Comment by Glurt** [comment]
The app is still in development so it isn't an issue but clearing the data has no effect. Am I right in thinking that this library is just a wrapper around the Android Sqlite framework and uninstalling should remove all traces of the database?

**Comment by npurushe** [comment]
Yes it just uses the SQLite api for android, uninstall should also work

**Comment by Glurt** [comment]
Everything seems to be working on the emulator so it must be an issue on my end, if I figure out what's going on and it relates to requery I'll post another issue. 

Thanks for the help!
