### ISSUE TITLE
Strict mode exception

### ISSUE THREAD

**Issue by miomao656** [requery/requery#108]
@OneToMany MutableResult<DocumentVersion> getVersions();

in other class we have 

@ManyToOne Document getDocument();

insert some data with .getVersions().add() and when i call getVersions() strict mode throws exception

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
              java.lang.Throwable: Explicit termination method 'close' not called
                  at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                  at android.database.CursorWindow.<init>(CursorWindow.java:111)
                  at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
                  at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
                  at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                  at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
                  at io.requery.android.sqlite.CursorResultSet.<init>(CursorResultSet.java:68)
                  at io.requery.android.sqlite.SqlitePreparedStatement.executeQuery(SqlitePreparedStatement.java:148)
                  at io.requery.sql.SelectResult.iterator(SelectResult.java:136)
                  at io.requery.query.BaseResult.iterator(BaseResult.java:111)
                  at io.requery.query.ModifiableResult.iterator(ModifiableResult.java:69)
```

beta11 version of the library

**Comment by npurushe** [comment]
Thanks for reporting, looks like an easy fix will be in the next update.

**Comment by npurushe** [comment]
Do you have the whole log from that stacktrace? there should be some more information before and after that will help solve it completely. Thanks

**Comment by miomao656** [comment]
I am sorry but right now i am unable to reproduce it.

**Comment by npurushe** [comment]
Looking at the code it should not iterate the result just by calling get. So will close for now please post back if it reoccurs.
