### ISSUE TITLE
NullPointerException when running app for the second time.

### ISSUE THREAD

**Issue by julianraj** [requery/requery#111]
I am collecting data from the web and storing it in DB when the app is run for the first time. 
On the first run, insert and select query works fine without any problem.
But on the second run when I try to fetch data from the DB, it gives NullPointerException.

`Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object io.requery.sql.Mapping.read(io.requery.query.Expression, java.sql.ResultSet, int)' on a null object reference
                                                                        at io.requery.sql.EntityReader.fromResult(EntityReader.java:531)
                                                                        at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
                                                                        at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
                                                                        at io.requery.query.BaseResult.collect(BaseResult.java:77)
                                                                        at io.requery.query.BaseResult.toList(BaseResult.java:69)`

The query I have is:
`data.select(Section.class).limit(20).offset(0).get().toList();`

**Comment by npurushe** [comment]
Thanks for reporting looks like the mapping is null. Do you override or provide your own mapping? Otherwise it will always be non-null.

**Comment by julianraj** [comment]
"Do you override or provide your own mapping?" - Didn't get you.
Well but the same query works for the first time.

**Comment by julianraj** [comment]
What should I do to correct this on my side?

**Comment by npurushe** [comment]
Please retry with the beta16 version. It's not exactly clear that this could happen in anything running android since the mapping is never null so this fix is just a guess

**Comment by julianraj** [comment]
Tried the beta16 version and it seems to have fixed the problem. :+1:
