### ISSUE TITLE
unable to marshal value io.requery.util.ObservableSet

### ISSUE THREAD

**Issue by thomas-se** [requery/requery#113]
On Android I get the following exception when trying to parcel an entity created from the abstract class below:

```
java.lang.RuntimeException: Parcel: unable to marshal value io.requery.util.ObservableSet@e324b4b
     at android.os.Parcel.writeValue(Parcel.java:1418)
     at io.requery.android.EntityParceler.writeToParcel(EntityParceler.java:80) 
     at com.m.b.persistence.requery.RequeryBEntity.writeToParcel(RequeryBEntity.java:686)
     ...
```

RequeryB:
```Java
@Entity
public abstract class RequeryB implements InterfaceB, Parcelable {


    @Key @Generated
    Long id;

    String name;
    Status status;
    boolean alarmEnabled;
    Long statusTimeStamp;
    String imagePath;
    Type type;
    String notes;
    float currentEstimate;



    @OneToMany
    Set<RequeryA> measurements_;

    Long creationTimeStamp;
    Double longitude;
    Double latitude;
    Double altitude;

    @Override
    public String toString() {
        return this.getName() + " [" + this.getStatus().toString() + "]" ;
    }
}
```

RequeryA: 
```Java
@Entity
public abstract class RequeryA implements InterfaceA, Parcelable {

	@Key
	@Generated
	long id;

	@ManyToOne
	RequeryA belongsTo_;

	int count;

	long observationTimeStamp;

	String comment;

	
}
```

**Comment by thomas-se** [comment]
Same with Set/Result/MutableResult: 
```
java.lang.RuntimeException: Parcel: unable to marshal value io.requery.util.ObservableSet@55d1928
...
java.lang.RuntimeException: Parcel: unable to marshal value io.requery.query.ModifiableResult@37d77e6
...
java.lang.RuntimeException: Parcel: unable to marshal value io.requery.query.ModifiableResult@948e53c
```
Only when using  `List<RequeryA> measurements_` I get another exception:
````
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=12, result=-1, data=Intent { cmp=com.m_pulso.beebuddy/.gui.activity.MainActivity (has extras) }} to activity {com.m_pulso.beebuddy/com.m_pulso.beebuddy.gui.activity.MainActivity}: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4920)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)
    at android.app.ActivityThread.access$1600(ActivityThread.java:221)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
  Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
    at com.m_pulso.beebuddy.persistence.requery.RequeryBEntity$11.set(RequeryBEntity.java:176)
    at io.requery.proxy.EntityProxy.setObject(EntityProxy.java:151)
    at io.requery.android.EntityParceler.readFromParcel(EntityParceler.java:65)
    at com.m_pulso.beebuddy.persistence.requery.RequeryBEntity$32.createFromParcel(RequeryBEntity.java:521)
    at com.m_pulso.beebuddy.persistence.requery.RequeryBEntity$32.createFromParcel(RequeryBEntity.java:518)
```

**Comment by npurushe** [comment]
Thanks for reporting. Relational lists should be skipped when parceling. 

Just a warning though after unparceling the entity will become detached (not persistable anymore) and relational sets/lists will be empty. The reason for this is set/lists are expensive to marshal and they also may contain cyclic links back to the original object. So generally inside your app your should use keys and `findByKey` to lookup entities instead of parceling them.
