### ISSUE TITLE
Updating to new version leads to StackoverFlow

### ISSUE THREAD

**Issue by Pr0bability** [requery/requery#119]
Hello,

updating to the new beta version of Requery leads to StackoverFlow exception, here is the log:

```
04-28 13:15:43.486 24523-24549/eu.flowup.pillmo E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
                                                                  Process: eu.flowup.pillmo, PID: 24523
                                                                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                      at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: java.lang.StackOverflowError: stack size 1038KB
                                                                      at java.util.IdentityHashMap.getModuloHash(IdentityHashMap.java:444)
                                                                      at java.util.IdentityHashMap.findIndex(IdentityHashMap.java:428)
                                                                      at java.util.IdentityHashMap.get(IdentityHashMap.java:380)
                                                                      at io.requery.util.ClassMap.get(ClassMap.java:86)
                                                                      at java.util.Collections$UnmodifiableMap.get(Collections.java:1268)
                                                                      at io.requery.meta.ImmutableEntityModel.typeOf(ImmutableEntityModel.java:50)
                                                                      at io.requery.sql.EntityDataStore$DataContext.proxyOf(EntityDataStore.java:561)
                                                                      at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:759)
                                                                      at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                                      at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                                      at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                                      at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                                      at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                      at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                                      at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                                      at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                                      at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                                  	at io.requery.sql.EntityWriter.cascade
04-28 13:15:43.520 24523-24549/eu.flowup.pillmo D/Error: ERR: exClass=java.lang.StackOverflowError
04-28 13:15:43.520 24523-24549/eu.flowup.pillmo D/Error: ERR: exMsg=stack size 1038KB
04-28 13:15:43.520 24523-24549/eu.flowup.pillmo D/Error: ERR: file=IdentityHashMap.java
04-28 13:15:43.520 24523-24549/eu.flowup.pillmo D/Error: ERR: class=java.util.IdentityHashMap
04-28 13:15:43.520 24523-24549/eu.flowup.pillmo D/Error: ERR: method=getModuloHash line=444
04-28 13:15:43.531 24523-24533/eu.flowup.pillmo W/art: Suspending all threads took: 7.887ms
04-28 13:15:43.531 24523-24549/eu.flowup.pillmo D/Error: ERR: stack=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                             at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                             at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                             at java.lang.Thread.run(Thread.java:818)
                                                          Caused by: java.lang.StackOverflowError: stack size 1038KB
                                                             at java.util.IdentityHashMap.getModuloHash(IdentityHashMap.java:444)
                                                             at java.util.IdentityHashMap.findIndex(IdentityHashMap.java:428)
                                                             at java.util.IdentityHashMap.get(IdentityHashMap.java:380)
                                                             at io.requery.util.ClassMap.get(ClassMap.java:86)
                                                             at java.util.Collections$UnmodifiableMap.get(Collections.java:1268)
                                                             at io.requery.meta.ImmutableEntityModel.typeOf(ImmutableEntityModel.java:50)
                                                             at io.requery.sql.EntityDataStore$DataContext.proxyOf(EntityDataStore.java:561)
                                                             at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:759)
                                                             at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                             at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                             at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                             at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                             at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:566)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                             at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:762)
                                                             at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:642)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                                                             at io.requery.sql.EntityWriter.update(EntityWriter.java:496)
                                                             at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:897)
                                                         	at io.requery.sql.EntityWriter.update(En
```

**Comment by npurushe** [comment]
Thanks for reporting. this is the same as #99 will be fixed in the next update

**Comment by npurushe** [comment]
Can you try the beta17 version?

**Comment by Pr0bability** [comment]
Still produces the same Exception.
