### ISSUE TITLE
Syntax error when upserting with a compound @Key

### ISSUE THREAD

**Issue by dukeyin** [requery/requery#143]
I'm trying to use requery for the first time, using 1.0.0-beta18 for android.

I have an Entity where I'd like to be able to do an upsert based on a pair of identity columns:

```
public interface Chart...
    @Key
    @ManyToOne
    Song getSong();

   @Key
    Integer getChart();

    ....
```
The operation ends up failing up for:
```
E/SQLiteLog: (1) near "ANDsong": syntax error
Message: near "ANDsong": syntax error (code 1): , while compiling: select chart from Chart where chart =? ANDsong =?
```

I thought it might be because of using an Entity as the ```@Key``` column, so I tried switching it out for an Integer ID without the ```@ManyToOne```, but same problem:
```
public interface Chart...
    @Key
    Integer getSongId();

   @Key
    Integer getChart();

    ....
```
```
E/SQLiteLog: (1) near "ANDsongId": syntax error
Message: near "ANDsongId": syntax error (code 1): , while compiling: select chart from Chart where chart =? ANDsongId =?
```

The relevant part of the Requery stack trace seems to be:
```
...
at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38)
at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:131)
at io.requery.android.sqlite.BaseConnection.prepareStatement(BaseConnection.java:160)
at io.requery.sql.ConnectionDelegate.prepareStatement(ConnectionDelegate.java:53)
at io.requery.sql.EntityReader.refresh(EntityReader.java:218)
at io.requery.sql.EntityReader.refresh(EntityReader.java:180)
at io.requery.sql.EntityReader.load(EntityReader.java:150)
at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61)
at io.requery.proxy.EntityProxy.get(EntityProxy.java:75)
at io.requery.proxy.EntityProxy.get(EntityProxy.java:70)
at io.requery.sql.EntityWriter.bindParameters(EntityWriter.java:360)
at io.requery.sql.EntityUpdateOperation$1.get(EntityUpdateOperation.java:66)
at io.requery.sql.EntityUpdateOperation$1.get(EntityUpdateOperation.java:55)
at io.requery.query.SuppliedScalar.value(SuppliedScalar.java:51)
at io.requery.sql.EntityWriter.insert(EntityWriter.java:445)
at io.requery.sql.EntityWriter.upsert(EntityWriter.java:484)
at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:263)
...
```

**Comment by npurushe** [comment]
The beta19 version contains this fix
