### ISSUE TITLE
Can't select entity which has a compound key using another entity

### ISSUE THREAD

**Issue by dukeyin** [requery/requery#147]
Entity example same as before:
```
public interface Chart...
    @Key
    @ManyToOne
    Song getSong(); // Song has a single column @Key, primitive int, not autogenerated

   @Key
    Integer getChart();

    ....
```

I try to run:
```
SingleEntityStore<Persistable>.select(ChartEntity.class).get().toList()
```
```
Caused by: java.sql.SQLDataException: no column song
 at io.requery.android.sqlite.CursorResultSet.findColumn(CursorResultSet.java:113)
 at io.requery.sql.EntityReader.readCacheKey(EntityReader.java:476)
 at io.requery.sql.EntityReader.fromResult(EntityReader.java:496)
 at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
 at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
 at io.requery.query.BaseResult.collect(BaseResult.java:78) 
 at io.requery.query.BaseResult.toList(BaseResult.java:70) 
```
which includes all columns except for the ManyToOne Entity ID column.  (It does include the Integer part of the compound key).  This results in no rows being able to load.

On the other hand, this raw query works:
```List<Tuple> list = SingleEntityStore<Persistable>.raw("SELECT c.*, s.name FROM Chart c, Song s WHERE c.song = s.id ORDER BY s.name, c.chart").toList();```

**Comment by npurushe** [comment]
The beta19 version contains this fix

**Comment by dukeyin** [comment]
Unfortunately I still see an issue with the select of this Entity example:
```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to (Song interface)
	at java.lang.Class.cast(Class.java:1505)
	at io.requery.sql.GenericMapping.read(GenericMapping.java:289)
	at io.requery.sql.EntityReader.readCacheKey(EntityReader.java:477)
	at io.requery.sql.EntityReader.fromResult(EntityReader.java:496)
	at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
	at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
	at io.requery.query.BaseResult.collect(BaseResult.java:78)
	at io.requery.query.BaseResult.toList(BaseResult.java:70)
```

I took a look at ```EntityReader``` and it seems the loading of the Song might happen at lines 497~507, but that is after line 496 where the ClassCastException is thrown because the Integer key is not an Entity interface.
