### ISSUE TITLE
Strange behavior of EntityStore.findByKey returned exception without result

### ISSUE THREAD

**Issue by cocia** [requery/requery#149]
This is my code to implement update/insert for android sqlite:
```java
        if(RequeryOrm.store().findByKey(CloudAccount.class, cloudAccount.getAccountId()) == null){
            RequeryOrm.store().insert(cloudAccount);
        }else{
            RequeryOrm.store().update(cloudAccount);
        }
```
findByKey method throws NoSuchElementException from here:
```java
java.util.NoSuchElementException
	at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:98)
	at io.requery.query.BaseResult.first(BaseResult.java:86)
	at io.requery.sql.EntityDataStore.findByKey(EntityDataStore.java:376)
```

As I excpected, findByKey should return null if there is not a matched result by query.

How do you think?

**Comment by npurushe** [comment]
Thanks for reporting, yes agree this method should return null if there is no element.
