### ISSUE TITLE
Error while watching for changes with Limit statement

### ISSUE THREAD

**Issue by YuriHeupa** [requery/requery#153]
I've an selection with limit statement, and I'm using the method `toSelfObservable()` to watch changes on FileEntity table:
```java
getData().select(FileEntity.class).where(FileEntity.DOWNLOAD_COMPLETED.eq(true))
        .limit(PAGINATION_LIMIT).get().toSelfObservable()
        .observeOn(AndroidSchedulers.mainThread())
        .flatMap(fileEntities -> fileEntities.toObservable().toList())
        .subscribe(fileEntities -> {
            //do something with entities
        }, Throwable::printStackTrace);
```
But when another query affects this one I receive the following error:
```
05-23 01:42:12.848 W/System.err: java.lang.IllegalStateException
05-23 01:42:12.849 W/System.err:     at io.requery.query.BaseResult.iterator(BaseResult.java:109)
05-23 01:42:12.849 W/System.err:     at io.requery.query.BaseResult.iterator(BaseResult.java:48)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:50)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
05-23 01:42:12.849 W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8460)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
05-23 01:42:12.849 W/System.err:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
05-23 01:42:12.849 W/System.err:     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
05-23 01:42:12.849 W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-23 01:42:12.849 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-23 01:42:12.849 W/System.err:     at android.os.Looper.loop(Looper.java:135)
05-23 01:42:12.849 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5256)
05-23 01:42:12.849 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-23 01:42:12.849 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-23 01:42:12.849 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
05-23 01:42:12.849 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
05-23 01:42:12.850 W/System.err: java.lang.IllegalStateException
05-23 01:42:12.850 W/System.err:     at io.requery.query.BaseResult.iterator(BaseResult.java:109)
05-23 01:42:12.850 W/System.err:     at io.requery.query.BaseResult.iterator(BaseResult.java:48)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:50)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
05-23 01:42:12.850 W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8460)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
05-23 01:42:12.850 W/System.err:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
05-23 01:42:12.850 W/System.err:     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
05-23 01:42:12.850 W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-23 01:42:12.850 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-23 01:42:12.850 W/System.err:     at android.os.Looper.loop(Looper.java:135)
05-23 01:42:12.851 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5256)
05-23 01:42:12.851 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-23 01:42:12.851 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-23 01:42:12.851 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
05-23 01:42:12.851 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by npurushe** [comment]
Thanks for reporting looks like the result was closed by the OnSubscribe
