### ISSUE TITLE
Null object reference on OneToMany cascade relation when entity is saved

### ISSUE THREAD

**Issue by francoispluchino** [requery/requery#162]
When I want to insert (with upsert) an entity in the database with a relation `OneToMany`, an exception is thrown.

**Entity example:**
```java
public interface User extends Parcelable, Persistable {
    //...

    @OneToMany(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    List<Post> getPosts();
}
```

**Stack trace:**
```
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object io.requery.util.function.Supplier.get()' on a null object reference
W/System.err:     at io.requery.sql.Attributes.get(Attributes.java:38)
W/System.err:     at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:771)
W/System.err:     at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:655)
W/System.err:     at io.requery.sql.EntityWriter.insert(EntityWriter.java:452)
W/System.err:     at io.requery.sql.EntityWriter.upsert(EntityWriter.java:493)
W/System.err:     at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:265)
W/System.err:     at io.requery.rx.SingleEntityStoreFromBlocking$7.get(SingleEntityStoreFromBlocking.java:148)
W/System.err:     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
W/System.err:     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)
W/System.err:     at rx.Single$1.call(Single.java:94)
W/System.err:     at rx.Single$1.call(Single.java:74)
W/System.err:     at rx.Single.subscribe(Single.java:1725)
W/System.err:     at rx.Single.subscribe(Single.java:1802)
W/System.err:     at rx.Single$19$1.call(Single.java:1857)
W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
W/System.err:     at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:108)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

I used the `1.0.0-beta20` version and Rx observable. I added the `mappedBy` option, but I get the same error.

**Comment by francoispluchino** [comment]
Ok, sorry, I forgot the mapping ManyToOne on the other entity...

But I have another error now:

```
java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: User.id (code 1555)
```

**Entites example:**
```java
public interface User extends Parcelable, Persistable {
    @Key
    String getId();

    @OneToMany(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    List<Post> getPosts();
}
```
```java
public interface Post extends Parcelable, Persistable {
    @Key
    String getId();

    @ManyToOne(cascade = {CascadeAction.NONE})
    User getUser();
}
```

```java
//...
Post post = new Post();
post.setId(UUID.randomUUID().toString());

User user = new User();
user.setId(UUID.randomUUID().toString());
user.getPosts().add(post);

singleEntityStore.upsert(user).toBlocking().value();
```

Looks like there 2 times an insertion of the User in database. Did I miss something? Thanks.

**Comment by francoispluchino** [comment]
Closing for #155.
