### ISSUE TITLE
ClassCastException when fetching from the database.

### ISSUE THREAD

**Issue by shymek** [requery/requery#167]
Hi. 

> beta20

I have a model which is saved to the database correctly. I receive the Iterable with my Entities but when I want to select them I get this exception:
`java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
                                                                          at java.lang.Class.cast(Class.java:1505)
                                                                          at io.requery.sql.GenericMapping.read(GenericMapping.java:289)
                                                                          at io.requery.sql.EntityReader.fromResult(EntityReader.java:562)
                                                                          at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
                                                                          at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
                                                                          at io.requery.rx.OnSubscribeFromQuery$ElementProducer.request(OnSubscribeFromQuery.java:91)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                          at io.requery.rx.OnSubscribeFromQuery.call(OnSubscribeFromQuery.java:51)
                                                                          at io.requery.rx.OnSubscribeFromQuery.call(OnSubscribeFromQuery.java:39)
                                                                          at rx.Observable$2.call(Observable.java:162)
                                                                          at rx.Observable$2.call(Observable.java:154)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:8314)
                                                                          at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:235)
                                                                          at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
                                                                          at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
                                                                          at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                          at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
                                                                          at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
                                                                          at rx.Observable$2.call(Observable.java:162)
                                                                          at rx.Observable$2.call(Observable.java:154)
                                                                          at rx.Observable$2.call(Observable.java:162)
                                                                          at rx.Observable$2.call(Observable.java:154)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:8314)
                                                                          at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                          at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

I noticed that when I remove all my 
`List<String>`
fields it works. If I even have one such field I can't fetch the data.

**Comment by dukeyin** [comment]
This looks like the same problem I'm still having in e.g. #154 although I am using a blocking entity store instead of rx.

**Comment by shymek** [comment]
@dukeyin I will check the blocking entity store later today and see what will happen.
But nontheless this is an issue that needs fixing.

**Comment by shymek** [comment]
@dukeyin I just created a gist that solved my problem and I am happy to share it.
https://gist.github.com/shymek/e784c964704eca007ab6d6966238df70

**Comment by dukeyin** [comment]
Wow.  It never occurred to me that I forgot to put the Converter annotation on my List field, but I guess I should have realized that when requery was persisting to the database as ```[1, 0, 1,...]``` when it should have been ```1,0,1,...``` without brackets and spaces.

**Comment by shymek** [comment]
Ok it was stupid of me to try to save List of Strings in the database, sorry for confusion!

**Comment by npurushe** [comment]
Yup if you need to store a list or collection inside a column of a database that doesn't support that natively then converting into another basic type like a String is the correct solution.

**Comment by ZakTaccardi** [comment]
@npurushe - I have an AutoValue class with a method for a List<Strings>, so I get this error. Shouldn't the code generation handle this?

I'm guessing I have to manually define a `io.requery.Converter` to fix this myself?

**Comment by npurushe** [comment]
If you are mapping list contents to a single column yes you should use a `Converter` for this purpose.

**Comment by agrimgrover** [comment]
ClassCast exception occurred for me , as I was using Builder class and then requery to access those getters, requery only support pojo getters and setters
