### ISSUE TITLE
Multi database compile issues

### ISSUE THREAD

**Issue by miomao656** [requery/requery#17]
helper

```
public class CityReQuery {

    public static final String STATE_DB = "state_db";

    private static CityReQuery mInstance;
    private SingleEntityStore<Persistable> entityStore;

    private CityReQuery() {
    }

    public static CityReQuery getInstance() {
        if (mInstance == null) {
            mInstance = new CityReQuery();
        }
        return mInstance;
    }

    public SingleEntityStore<Persistable> getEntityStore() {
        return entityStore;
    }

    /**
     * Initialize general database on first start
     */
    public void init(Context context) {
        initGeneralDataStore(context);
    }

    /**
     * @return {@link EntityDataStore} single instance for the application. <p/> Note if you're
     * using Dagger you can make this part of your application level module returning {@code
     * @Provides @Singleton}.
     */
    private SingleEntityStore<Persistable> initGeneralDataStore(Context context) {
        if (entityStore == null) {
            // override onUpgrade to handle migrating to a new version
//            DatabaseSource source = new DatabaseSource(context, , Models., STATE_DB, 1);
//            Configuration configuration = source.getConfiguration();
//            entityStore = RxSupport.toReactiveStore(new EntityDataStore<>(configuration));
        }
        return entityStore;
    }
}
```

helper,

```
public class UserReQuery {

    public static final String USER_DB = "user_db";

    private static UserReQuery mInstance;
    private SingleEntityStore<Persistable> entityStore;

    private UserReQuery() {
    }

    public static UserReQuery getInstance() {
        if (mInstance == null) {
            mInstance = new UserReQuery();
        }
        return mInstance;
    }

    public SingleEntityStore<Persistable> getEntityStore() {
        return entityStore;
    }

    /**
     * Initialize general database on first start
     */
    public void init(Context context) {
        initGeneralDataStore(context);
    }

    /**
     * @return {@link EntityDataStore} single instance for the application. <p/> Note if you're
     * using Dagger you can make this part of your application level module returning {@code
     * @Provides @Singleton}.
     */
    private SingleEntityStore<Persistable> initGeneralDataStore(Context context) {
        if (entityStore == null) {
            // override onUpgrade to handle migrating to a new version
//            DatabaseSource source = new DatabaseSource(context, Models., USER_DB, 1);
//            Configuration configuration = source.getConfiguration();
//            entityStore = RxSupport.toReactiveStore(new EntityDataStore<>(configuration));
        }
        return entityStore;
    }
}
```

user
```

@Entity(name = UserReQuery.USER_DB)
public interface User {

    @Key
    @Generated
    int getId();

    String getName();

    void setName(String name);

    @ManyToMany(mappedBy = "members")
    Result<Group> getMemberGroups();

    @ManyToMany(mappedBy = "admins")
    Result<Group> getAdminGroups();

}
```

group

```
@Entity(name = UserReQuery.USER_DB)
public interface Group {

    @Key
    @Generated
    int getId();

    String getName();

    void setName(String name);

    @JunctionTable(name = "group_members")
    @ManyToMany(mappedBy = "memberGroups")
    Result<User> getMembers();

    @JunctionTable(name = "group_admins")
    @ManyToMany(mappedBy = "adminGroups")
    Result<User> getAdmins();
}
```

city

```
@Entity(name = CityReQuery.STATE_DB)
public interface City {

    @Key
    @Generated
    int getId();

    String getPTT();

    void setPTT(String ptt);

    String getName();

    void setName(String name);

    @ManyToOne
    State getState();

    void setState(State state);

    @OneToMany(mappedBy = "city")
    Result<Street> getStreets();
}
```

state

```
@Entity(name = CityReQuery.STATE_DB)
public interface State {

    @Key
    @Generated
    int getId();

    String getPostCode();

    void setPostCode(String line1);

    String getName();

    void setName(String line2);

    @OneToMany(mappedBy = "state")
    Result<City> getCities();
}
```

street 

```
@Entity(name = CityReQuery.STATE_DB)
public interface Street {

    @Key
    @Generated
    int getId();

    String getName();

    void setName(String name);

    @ManyToOne
    City getCity();

    void setCity(City city);

}
```

and when i try to compile it throws this stack trace 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: couldn't make a guess for requerytest.user_db

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: couldn't make a guess for requerytest.user_db
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
        at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: java.lang.IllegalArgumentException: couldn't make a guess for requerytest.user_db
        at com.squareup.javapoet.Util.checkArgument(Util.java:62)
        at com.squareup.javapoet.ClassName.bestGuess(ClassName.java:149)
        at io.requery.processor.EntityNameResolver.typeNameOf(EntityNameResolver.java:35)
        at io.requery.processor.EntityGenerator.<init>(EntityGenerator.java:108)
        at io.requery.processor.EntityProcessor.process(EntityProcessor.java:114)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 34 more


```

**Comment by npurushe** [comment]
`@Entity(name = UserReQuery.USER_DB)`

Hi I don't think this is what you want. Entity#name is use to control the name of the generated class, not the table. Add `@Table(name = UserReQuery.USER_DB)` to specify the table name and then remove the name from @Entity. 

This shouldn't be a compile error though, so will add a message instead. Thanks for reporting.

**Comment by miomao656** [comment]
I am not sure if i understand. I want to have two databases in app, and i tough this was the way to do this? How can i define what entities i want in what database?

**Comment by npurushe** [comment]
Hi, you need to use the #model property to separate them into 2 separate models. For example you can use `@Entity(model = "db1")` on the items for the first database and `@Entity(model = "db2")`, I thought you were trying to set the table name which is different.

**Comment by miomao656** [comment]
Tnx this is what i need

**Comment by npurushe** [comment]
Hi can you try a clean and rebuild? Also are all your entity classes in the same java package?

**Comment by miomao656** [comment]
Yes they are in the same package, the command for building is 
`gradle clean build --refresh-dependencies --stacktrace this was the command`

**Comment by npurushe** [comment]
Looks like there is a bug if they are in the same package, will work on a fix today. Thanks for reporting.

**Comment by miomao656** [comment]
you're wellcome, i will report if i find something else

**Comment by miomao656** [comment]
Update: the same error happens if i put entity classes in the separate packages.

**Comment by miomao656** [comment]
Hi, I still can't compile
I use the same gradle command and get this error

I use android studio beta 6 with 
classpath 'com.android.tools.build:gradle:2.0.0-beta6'
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

and applied plugin apply plugin: 'com.neenbedankt.android-apt'

```
error: Attempt to recreate a file for type requerytest.statedb.Models
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:47)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:103)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
        at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

```

**Comment by npurushe** [comment]
Hi what version of gradle are you using? Also can you post the contents of the Models.java file that it says is being recreated? Thanks

**Comment by miomao656** [comment]
gradle version is 2.11

and content of statedb Modles file that is generated is

```
// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package requerytest.statedb;

import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;

public class Models {
    public static final EntityModel STATE_DB = new EntityModelBuilder("state_db")
    .addType(CityEntity.$TYPE)
    .addType(StateEntity.$TYPE)
    .addType(StreetEntity.$TYPE)
    .build();

    private Models() {
    }
}

```

**Comment by npurushe** [comment]
Ok thanks, and in the package requerytest.statedb you only have those 3 entities Citiy, State and Street?

**Comment by miomao656** [comment]
helper class is also there StateReQuery

```
public class StateReQuery {

    public static final String STATE_DB = "state_db";

    private static StateReQuery mInstance;
    private SingleEntityStore<Persistable> entityStore;

    private StateReQuery() {
    }

    public static StateReQuery getInstance() {
        if (mInstance == null) {
            mInstance = new StateReQuery();
        }
        return mInstance;
    }

    public SingleEntityStore<Persistable> getEntityStore() {
        return entityStore;
    }

    /**
     * Initialize general database on first start
     */
    public void init(Context context) {
        initGeneralDataStore(context);
    }

    /**
     * @return {@link EntityDataStore} single instance for the application. <p/> Note if you're
     * using Dagger you can make this part of your application level module returning {@code
     * @Provides @Singleton}.
     */
    private SingleEntityStore<Persistable> initGeneralDataStore(Context context) {
        if (entityStore == null) {
            // override onUpgrade to handle migrating to a new version
            DatabaseSource source = new DatabaseSource(context, Models.STATE_DB, STATE_DB, 1);
            Configuration configuration = source.getConfiguration();
            entityStore = RxSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
        }
        return entityStore;
    }
}
```

**Comment by npurushe** [comment]
What's the output of `gradlew dependencies` in your main project.

**Comment by miomao656** [comment]
Sucessful

```
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations

BUILD SUCCESSFUL

Total time: 5.07 secs

```

**Comment by npurushe** [comment]
I mean can you run that in the project that has your code, so one level in thanks

**Comment by miomao656** [comment]
yeah sure here you go

```
Project :app
------------------------------------------------------------

_debugAndroidTestApk - ## Internal use, do not manually configure ##
No dependencies

_debugAndroidTestCompile - ## Internal use, do not manually configure ##
No dependencies

_debugApk - ## Internal use, do not manually configure ##
+--- com.android.support:appcompat-v7:23.2.0
|    +--- com.android.support:support-v4:23.2.0
|    |    \--- com.android.support:support-annotations:23.2.0
|    +--- com.android.support:animated-vector-drawable:23.2.0
|    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |         \--- com.android.support:support-v4:23.2.0 (*)
|    \--- com.android.support:support-vector-drawable:23.2.0 (*)
+--- io.reactivex:rxjava:1.1.1
+--- io.reactivex:rxandroid:1.1.0
|    \--- io.reactivex:rxjava:1.1.0 -> 1.1.1
+--- io.requery:requery:1.0-SNAPSHOT
+--- io.requery:requery-android:1.0-SNAPSHOT
\--- com.facebook.stetho:stetho:1.3.1
     +--- com.google.code.findbugs:jsr305:2.0.1
     \--- commons-cli:commons-cli:1.2

_debugCompile - ## Internal use, do not manually configure ##
+--- com.android.support:appcompat-v7:23.2.0
|    +--- com.android.support:support-v4:23.2.0
|    |    \--- com.android.support:support-annotations:23.2.0
|    +--- com.android.support:animated-vector-drawable:23.2.0
|    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |         \--- com.android.support:support-v4:23.2.0 (*)
|    \--- com.android.support:support-vector-drawable:23.2.0 (*)
+--- io.reactivex:rxjava:1.1.1
+--- io.reactivex:rxandroid:1.1.0
|    \--- io.reactivex:rxjava:1.1.0 -> 1.1.1
+--- io.requery:requery:1.0-SNAPSHOT
+--- io.requery:requery-android:1.0-SNAPSHOT
\--- com.facebook.stetho:stetho:1.3.1
     +--- com.google.code.findbugs:jsr305:2.0.1
     \--- commons-cli:commons-cli:1.2

_debugUnitTestApk - ## Internal use, do not manually configure ##
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

_debugUnitTestCompile - ## Internal use, do not manually configure ##
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

_releaseApk - ## Internal use, do not manually configure ##
+--- com.android.support:appcompat-v7:23.2.0
|    +--- com.android.support:support-v4:23.2.0
|    |    \--- com.android.support:support-annotations:23.2.0
|    +--- com.android.support:animated-vector-drawable:23.2.0
|    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |         \--- com.android.support:support-v4:23.2.0 (*)
|    \--- com.android.support:support-vector-drawable:23.2.0 (*)
+--- io.reactivex:rxjava:1.1.1
+--- io.reactivex:rxandroid:1.1.0
|    \--- io.reactivex:rxjava:1.1.0 -> 1.1.1
+--- io.requery:requery:1.0-SNAPSHOT
+--- io.requery:requery-android:1.0-SNAPSHOT
\--- com.facebook.stetho:stetho:1.3.1
     +--- com.google.code.findbugs:jsr305:2.0.1
     \--- commons-cli:commons-cli:1.2

_releaseCompile - ## Internal use, do not manually configure ##
+--- com.android.support:appcompat-v7:23.2.0
|    +--- com.android.support:support-v4:23.2.0
|    |    \--- com.android.support:support-annotations:23.2.0
|    +--- com.android.support:animated-vector-drawable:23.2.0
|    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |         \--- com.android.support:support-v4:23.2.0 (*)
|    \--- com.android.support:support-vector-drawable:23.2.0 (*)
+--- io.reactivex:rxjava:1.1.1
+--- io.reactivex:rxandroid:1.1.0
|    \--- io.reactivex:rxjava:1.1.0 -> 1.1.1
+--- io.requery:requery:1.0-SNAPSHOT
+--- io.requery:requery-android:1.0-SNAPSHOT
\--- com.facebook.stetho:stetho:1.3.1
     +--- com.google.code.findbugs:jsr305:2.0.1
     \--- commons-cli:commons-cli:1.2

_releaseUnitTestApk - ## Internal use, do not manually configure ##
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

_releaseUnitTestCompile - ## Internal use, do not manually configure ##
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

androidJacocoAgent - The Jacoco agent to use to get coverage data.
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128.pom
\--- org.jacoco:org.jacoco.agent:0.7.4.201502262128

androidJacocoAnt - The Jacoco ant tasks to use to get execute Gradle tasks.
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.ant/0.7.4.201502262128/org.jacoco.ant-0.7.4.201502262128.pom
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.report/0.7.4.201502262128/org.jacoco.report-0.7.4.201502262128.pom
\--- org.jacoco:org.jacoco.ant:0.7.4.201502262128
     +--- org.jacoco:org.jacoco.core:0.7.4.201502262128
     |    \--- org.ow2.asm:asm-debug-all:5.0.1
     +--- org.jacoco:org.jacoco.report:0.7.4.201502262128
     |    +--- org.jacoco:org.jacoco.core:0.7.4.201502262128 (*)
     |    \--- org.ow2.asm:asm-debug-all:5.0.1
     \--- org.jacoco:org.jacoco.agent:0.7.4.201502262128

androidTestApk - Classpath packaged with the compiled 'androidTest' classes.
No dependencies

androidTestApt
No dependencies

androidTestCompile - Classpath for compiling the androidTest sources.
No dependencies

androidTestProvided - Classpath for only compiling the androidTest sources.
No dependencies

androidTestWearApp - Link to a wear app to embed for object 'androidTest'.
No dependencies

apk - Classpath packaged with the compiled 'main' classes.
No dependencies

apt
+--- io.requery:requery-processor:1.0-SNAPSHOT
|    +--- com.squareup:javapoet:1.5.1
|    +--- org.eclipse.persistence:javax.persistence:2.1.1
|    \--- io.requery:requery:1.0-SNAPSHOT
+--- com.android.support:appcompat-v7:23.2.0
|    +--- com.android.support:support-v4:23.2.0
|    |    \--- com.android.support:support-annotations:23.2.0
|    +--- com.android.support:animated-vector-drawable:23.2.0
|    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |         \--- com.android.support:support-v4:23.2.0 (*)
|    \--- com.android.support:support-vector-drawable:23.2.0 (*)
+--- io.reactivex:rxjava:1.1.1
+--- io.reactivex:rxandroid:1.1.0
|    \--- io.reactivex:rxjava:1.1.0 -> 1.1.1
+--- io.requery:requery:1.0-SNAPSHOT
+--- io.requery:requery-android:1.0-SNAPSHOT
\--- com.facebook.stetho:stetho:1.3.1
     +--- com.google.code.findbugs:jsr305:2.0.1
     \--- commons-cli:commons-cli:1.2

archives - Configuration for archive artifacts.
No dependencies

compile - Classpath for compiling the main sources.
+--- com.android.support:appcompat-v7:23.2.0
|    +--- com.android.support:support-v4:23.2.0
|    |    \--- com.android.support:support-annotations:23.2.0
|    +--- com.android.support:animated-vector-drawable:23.2.0
|    |    \--- com.android.support:support-vector-drawable:23.2.0
|    |         \--- com.android.support:support-v4:23.2.0 (*)
|    \--- com.android.support:support-vector-drawable:23.2.0 (*)
+--- io.reactivex:rxjava:1.1.1
+--- io.reactivex:rxandroid:1.1.0
|    \--- io.reactivex:rxjava:1.1.0 -> 1.1.1
+--- io.requery:requery:1.0-SNAPSHOT
+--- io.requery:requery-android:1.0-SNAPSHOT
\--- com.facebook.stetho:stetho:1.3.1
     +--- com.google.code.findbugs:jsr305:2.0.1
     \--- commons-cli:commons-cli:1.2

debugApk - Classpath packaged with the compiled 'debug' classes.
No dependencies

debugCompile - Classpath for compiling the debug sources.
No dependencies

debugProvided - Classpath for only compiling the debug sources.
No dependencies

debugWearApp - Link to a wear app to embed for object 'debug'.
No dependencies

default - Configuration for default artifacts.
No dependencies

default-mapping - Configuration for default mapping artifacts.
No dependencies

default-metadata - Metadata for the produced APKs.
No dependencies

provided - Classpath for only compiling the main sources.
No dependencies

releaseApk - Classpath packaged with the compiled 'release' classes.
No dependencies

releaseCompile - Classpath for compiling the release sources.
No dependencies

releaseProvided - Classpath for only compiling the release sources.
No dependencies

releaseWearApp - Link to a wear app to embed for object 'release'.
No dependencies

testApk - Classpath packaged with the compiled 'test' classes.
No dependencies

testApt
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

testCompile - Classpath for compiling the test sources.
\--- junit:junit:4.12
     \--- org.hamcrest:hamcrest-core:1.3

testDebugApk - Classpath packaged with the compiled 'testDebug' classes.
No dependencies

testDebugCompile - Classpath for compiling the testDebug sources.
No dependencies

testDebugProvided - Classpath for only compiling the testDebug sources.
No dependencies

testDebugWearApp - Link to a wear app to embed for object 'testDebug'.
No dependencies

testProvided - Classpath for only compiling the test sources.
No dependencies

testReleaseApk - Classpath packaged with the compiled 'testRelease' classes.
No dependencies

testReleaseCompile - Classpath for compiling the testRelease sources.
No dependencies

testReleaseProvided - Classpath for only compiling the testRelease sources.
No dependencies

testReleaseWearApp - Link to a wear app to embed for object 'testRelease'.
No dependencies

testWearApp - Link to a wear app to embed for object 'test'.
No dependencies

wearApp - Link to a wear app to embed for object 'main'.
No dependencies

BUILD SUCCESSFUL

Total time: 9.057 secs

```

**Comment by npurushe** [comment]
Ok I think I reproduced your problem working on a new fix, thanks for your patience :)

**Comment by miomao656** [comment]
yw :+1:

**Comment by npurushe** [comment]
Ok latest snapshot should work, thanks!
