### ISSUE TITLE
ClassCastException when using primitive data type in CompoundKey

### ISSUE THREAD

**Issue by laarmen** [requery/requery#170]
Hi,
One of my models has the following primary keys:

```java
@Entity
public abstract class Measure {
...
    @Key
    int measureNb;
    @Key
    String instrumentId;
...
}
```
and I wanted to fetch one using `findByKey()`, the key being constructed via the following

```java
    private CompositeKey<MeasureEntity> makeKey(Measure m) {
        Map<Attribute<MeasureEntity,?>, Object> map = new HashMap<>();
        map.put(MeasureEntity.INSTRUMENT_ID, m.getInstrument().getId());
        map.put(MeasureEntity.MEASURE_NB, m.getNumber());
        return new CompositeKey<>(map);
    }
```
`getNumber()` returns an `int`.

When I run findByKey, I get the following crash:

Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to int
                                                                                at java.lang.Class.cast(Class.java:1402)
                                                                                at io.requery.proxy.CompositeKey.get(CompositeKey.java:58)
                                                                                at io.requery.sql.EntityDataStore.findByKey(EntityDataStore.java:371)
                                                                                at io.requery.rx.SingleEntityStoreFromBlocking$15.get(SingleEntityStoreFromBlocking.java:232)
                                                                                at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
                                                                                at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)
                                                                                at rx.Single$1.call(Single.java:110)
                                                                                at rx.Single$1.call(Single.java:90)
                                                                                at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                                at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                                at java.lang.Thread.run(Thread.java:856)

Somewhere in there, there is problem with the un/boxing of Java primitive types, it seems.

Cheers,
Simon

**Comment by npurushe** [comment]
Thanks for reporting, this change will be in the next update as a temporary workaround you can use the boxed type. Also planning to make creating a composite key a bit easier.
