### ISSUE TITLE
[BUG] Query builder condition with ManyToOne relation is broke

### ISSUE THREAD

**Issue by francoispluchino** [requery/requery#180]
**Entites example:**
```java
public interface User extends Parcelable, Persistable {
    @Key
    String getId();

    @OneToMany(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    List<Post> getPosts();
}
```
```java
public interface Post extends Parcelable, Persistable {
    @Key
    String getId();

    @ManyToOne(cascade = {CascadeAction.NONE})
    User getUser();
}
```

I have an execption when I try to count the Post for an specific user:

```java
Integer countPost = singleEntityStore.count(PostEntity.class)
    .where(PostEntity.USER_ID.equal("<user_id>"));
```
Exception:
```
java.lang.ClassCastException: java.lang.String cannot be cast to com.example.models.UserEntity
```
Use `eq()` method doesn't change.

However, no problem if I use a class instance:
```java
UserEntity user = new UserEntity();
user.setId("<user_id>");

Integer countPost = singleEntityStore.count(PostEntity.class)
    .where(PostEntity.USER.equal(user));
```

**Comment by npurushe** [comment]
Do you have the full stacktrace?

**Comment by francoispluchino** [comment]
Yes, of course:

```
FATAL EXCEPTION: main
Process: com.example, PID: 5551
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to com.example.models.UserEntity
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.example.models.UserEntity
    at com.example.models.UserEntity$14.apply(UserEntity.java:238)
    at io.requery.sql.Attributes.replaceKeyReference(Attributes.java:61)
    at io.requery.sql.SelectResult.iterator(SelectResult.java:130)
    at io.requery.query.BaseResult.iterator(BaseResult.java:122)
    at io.requery.query.BaseResult.first(BaseResult.java:86)
    at io.requery.sql.SelectCountOperation$1.evaluate(SelectCountOperation.java:42)
    at io.requery.sql.SelectCountOperation$1.evaluate(SelectCountOperation.java:38)
    at io.requery.query.BaseScalar.value(BaseScalar.java:49)
    at com.example.MainActivity.onCreate(MainActivity.java:29)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by francoispluchino** [comment]
@npurushe Thanks!

**Comment by christianCallelero** [comment]
is this fixed?
