### ISSUE TITLE
NPE: limit is null in OffsetFetchGenerator using SQLServer platform

### ISSUE THREAD

**Issue by hastebrot** [requery/requery#193]
**Example code:**

~~~kotlin
dataStore.select(FooEntity::class.java).get().toList() // throws NPE.
dataStore.select(FooEntity::class.java).limit(999).get().toList() // works.
~~~

**Exception stacktrace:**

~~~
Exception in thread "main" java.lang.NullPointerException
	at io.requery.sql.gen.OffsetFetchGenerator.write(OffsetFetchGenerator.java:47)
	at io.requery.sql.platform.SQLServer$OrderByOffsetFetchLimit.write(SQLServer.java:150)
	at io.requery.sql.gen.OffsetFetchGenerator.write(OffsetFetchGenerator.java:37)
	at io.requery.sql.gen.OffsetFetchGenerator.write(OffsetFetchGenerator.java:30)
	at io.requery.sql.gen.StatementGenerator.write(StatementGenerator.java:93)
	at io.requery.sql.gen.DefaultOutput.toSql(DefaultOutput.java:93)
	at io.requery.sql.SelectResult.createQuery(SelectResult.java:97)
	at io.requery.sql.SelectResult.iterator(SelectResult.java:105)
	at io.requery.query.BaseResult.iterator(BaseResult.java:122)
	at io.requery.query.BaseResult.collect(BaseResult.java:76)
	at io.requery.query.BaseResult.toList(BaseResult.java:70)
~~~

**Run with debugger (`OffsetFetchGenerator.java`):**

~~~java
protected void write(QueryBuilder qb, Integer limit, Integer offset) {
    if (offset != null) {
        qb.keyword(OFFSET) // qb: "select ..."
            .value(offset)
            .keyword(offset > 1 ? ROWS : ROW) // offset: "0"
            .keyword(FETCH, NEXT)
            .value(limit)
            .keyword(limit > 1 ? ROWS : ROW) // limit: null
            .keyword(ONLY);
    // ...
}
~~~

**build.gradle:**

~~~gradle
compile "io.requery:requery:1.0.0-beta22"
kapt "io.requery:requery-processor:1.0.0-beta22"
compile "net.sourceforge.jtds:jtds:1.3.1" // open source driver.
compile "com.microsoft.sqlserver:sqljdbc42:4.2" // closed source driver.
~~~

Throws the exception with both `net.sourceforge.jtds.jdbcx.JtdsDataSource` and `com.microsoft.sqlserver.jdbc.SQLServerDataSource`.

**Comment by npurushe** [comment]
Thanks for reporting!
