### ISSUE TITLE
strange fail on insert.... copy from 195

### ISSUE THREAD

**Issue by danysz** [requery/requery#199]
Hi

I have an entity 

```
@Entity
public interface Connection extends Parcelable, Persistable {

    @Key
    @Generated
    int getId();

    @Column(unique = true)
    @Index("indexConnectionName")
    String getName();

    @Column(unique = true)
    @Index("indexSSID")
    String getSSID();

    String getIPAddressLocal();

    String getIPAddressRemote();

    int getPortLocal();

    int getPortRemote();

    String getUserName();

    String getPassword();

    Long getVBoxLastUpdate();

    @OneToMany(mappedBy = "connection", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<Floor> getFloorsList();
}

```

When I try to call insert on this kind of object for the second time in the "data" of ConnectionEntity the "id" is "0". For the second insert I got error that the "id" alreayd exist of course...
What I am doing wrong ?

Continue : 

Of course.. But in the software I make
new connection and it's created with 0 in id...

`mConnectionEntity = new ConnectionEntity();
`

This is the row that I try to use to create a new connection and insert it..
First time is ok second time it fails.

Thanks

Daniel

**Comment by npurushe** [comment]
Please provide some example, it's not quite clear what issue you're describing, there shouldn't be any `second time` insert for the same entity instance. If you have that entity it would work like so:
```java
Connection e1 = new ConnectionEntity(); // id is 0 because nothing has be inserted yet
data.insert(e1); // id is generated and usable after the insert, you can't insert e1 again
```

**Comment by danysz** [comment]
The problem is that when I try to insert the new Connection (el) I got the
error that is already there...
There is a way I can if it's trying to "generate" the id or not ?

Thanks

On Tue, Jun 21, 2016 at 5:56 AM, Nikhil Purushe <notifications@github.com>
wrote:

> Please provide some example, it's not quite clear what issue you're
> describing, there shouldn't be any second time insert for the same entity
> instance. If you have that entity it would work like so:
>
> Connection e1 = new ConnectionEntity(); // id is 0 because nothing has be inserted yet
> data.insert(e1); // id is generated and usable after the insert, you can't insert e1 again
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/requery/requery/issues/199#issuecomment-227327660>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABlzQHsIle8eeUrPN9UTXKtMflCw0Zegks5qN1LvgaJpZM4I59cT>
> .
>



-- 
Best regards

Daniel Szasz

**Comment by npurushe** [comment]
What's the exact exception message? If you have a generated id then there shouldn't be a problem

**Comment by npurushe** [comment]
Also please include a stacktrace

**Comment by danysz** [comment]
FATAL EXCEPTION: main
                                                               Process: com.vitrea.v7, PID: 29552
                                                               io.requery.sql.StatementExecutionException: Exception executing statement: insert into Connection (SSID, iPAddressLocal, iPAddressRemote, name, password, portLocal, portRemote, userName, vBoxLastUpdate) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
                                                                   at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:74)
                                                                   at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:55)
                                                                   at io.requery.query.BaseScalar.value(BaseScalar.java:49)
                                                                   at io.requery.sql.EntityWriter.insert(EntityWriter.java:452)
                                                                   at io.requery.sql.EntityWriter.insert(EntityWriter.java:410)
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:200)
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190)
                                                                   at com.vitrea.v7.activities.ActivityConnection.doSaveConnection(ActivityConnection.java:150)
                                                                   at com.vitrea.v7.activities.ActivityConnection.access$000(ActivityConnection.java:20)
                                                                   at com.vitrea.v7.activities.ActivityConnection$1.onClick(ActivityConnection.java:88)
                                                                   at android.view.View.performClick(View.java:5204)
                                                                   at android.view.View$PerformClick.run(View.java:21155)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                Caused by: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Connection.SSID (code 2067)
                                                                   at io.requery.android.sqlite.BaseConnection.throwSQLException(BaseConnection.java:69)
                                                                   at io.requery.android.sqlite.SqlitePreparedStatement.executeUpdate(SqlitePreparedStatement.java:164)
                                                                   at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:69)
                                                                   at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:55) 
                                                                   at io.requery.query.BaseScalar.value(BaseScalar.java:49) 
                                                                   at io.requery.sql.EntityWriter.insert(EntityWriter.java:452) 
                                                                   at io.requery.sql.EntityWriter.insert(EntityWriter.java:410) 
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:200) 
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190) 
                                                                   at com.vitrea.v7.activities.ActivityConnection.doSaveConnection(ActivityConnection.java:150) 
                                                                   at com.vitrea.v7.activities.ActivityConnection.access$000(ActivityConnection.java:20) 
                                                                   at com.vitrea.v7.activities.ActivityConnection$1.onClick(ActivityConnection.java:88) 
                                                                   at android.view.View.performClick(View.java:5204) 
                                                                   at android.view.View$PerformClick.run(View.java:21155) 
                                                                   at android.os.Handler.handleCallback(Handler.java:739) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Connection.SSID (code 2067)
                                                                   at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                   at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
                                                                   at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                   at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                   at io.requery.android.sqlite.SqlitePreparedStatement.executeUpdate(SqlitePreparedStatement.java:160)
                                                                   at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:69) 
                                                                   at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:55) 
                                                                   at io.requery.query.BaseScalar.value(BaseScalar.java:49) 
                                                                   at io.requery.sql.EntityWriter.insert(EntityWriter.java:452) 
                                                                   at io.requery.sql.EntityWriter.insert(EntityWriter.java:410) 
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:200) 
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190) 
                                                                   at com.vitrea.v7.activities.ActivityConnection.doSaveConnection(ActivityConnection.java:150) 
                                                                   at com.vitrea.v7.activities.ActivityConnection.access$000(ActivityConnection.java:20) 
                                                                   at com.vitrea.v7.activities.ActivityConnection$1.onClick(ActivityConnection.java:88) 
                                                                   at android.view.View.performClick(View.java:5204) 
                                                                   at android.view.View$PerformClick.run(View.java:21155) 
                                                                   at android.os.Handler.handleCallback(Handler.java:739) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by npurushe** [comment]
`Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Connection.SSID (code 2067)`

you're trying to insert 2 connections with the same id violating the uniqueness of the ssid column

**Comment by npurushe** [comment]
Please check how unique database columns should be handled, you should check if a column with that ssid exists first and either update it or delete it first before inserting a new one, either that or remove the constraint if it's not required.
