### ISSUE TITLE
Exceptions should be more informative.

### ISSUE THREAD

**Issue by nathanieloliveira** [requery/requery#2]
During testing I got the following exception:

```
java.lang.IllegalStateException
at io.requery.sql.QueryGenerator.appendInsert(QueryGenerator.java:155)
at io.requery.sql.QueryGenerator.toSql(QueryGenerator.java:92)
at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:53)
at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:48)
at io.requery.query.SuppliedScalar.value(SuppliedScalar.java:51)
at io.requery.sql.EntityWriter.insert(EntityWriter.java:346)
at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:183)
at com.ubervet.RequeryTest.testUser(RequeryTest.java:47)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879).
```

My Entity Class is:
```
@Entity
public abstract class AbstractUser {
    @Key @Generated
    int localId;
}
```

I'm testing the library like this:
```
public class RequeryTest extends ApplicationTestCase<UbervetApplication> {

    SingleEntityStore<Persistable> data;

    public RequeryTest() {
        super(UbervetApplication.class);
    }

    @Override
    protected void setUp() throws Exception {
        super.setUp();

        DatabaseSource source = new DatabaseSource(getContext(), Models.DEFAULT, 1);
        Configuration configuration = source.getConfiguration();
        data = RxSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
    }

    @SmallTest
    public void testUser() {
        User user1 = new User();
        User user2 = new User();
        User user3 = new User();

        int localId1 = data.toBlocking().insert(user1).getLocalId();
        int localId2 = data.toBlocking().insert(user2).getLocalId();
        int localId3 = data.toBlocking().insert(user3).getLocalId();

        assertEquals(user1.getLocalId(), localId1);
        assertEquals(user2.getLocalId(), localId2);
        assertEquals(user3.getLocalId(), localId3);
    }
}

```
I'm sorry if this is trivial to solve but I can't find what is the problem with my code.
Regards

**Comment by npurushe** [comment]
@nathanieloliveira Yes I agree that exception should be more informative. The issue you have here is actually no data to insert. Since you just have an id in your entity that is generated the INSERT statement would be empty which is why it throws. If you add a non generated column that issue will go away.

**Comment by npurushe** [comment]
A good explanation for SQLite specifically is [here](http://stackoverflow.com/questions/2662927/android-sqlite-nullcolumnhack-parameter-in-insert-replace-methods)

**Comment by npurushe** [comment]
I've added a more informative message to the exception. Thanks for your feedback!

**Comment by npurushe** [comment]
Actually going to keep this open since it would also be nice to have a compile time warning in such a case.
