### ISSUE TITLE
doc request: adding requery over existing DB

### ISSUE THREAD

**Issue by kenkyee** [requery/requery#200]
This is probably an unusual use case for requery, but for an old Android app that already has a DB (copied from assets into a specific database file on program startup), how do you map requery objects to it?

**Comment by npurushe** [comment]
This is a primary use case, not unusual. You have to create entity classes that correspond to the schema of your database. If you package the database in the assets bundle you should copy it to the data directory on app first run, then pass the name and schema version to `DatabaseSource` which will open it. If you don't know the schema/version you can use a sqlite database viewer (e.g. [sqlitebrowser](http://sqlitebrowser.org/)) to view it.

**Comment by kenkyee** [comment]
Thanks...I actually got this working yesterday.  One thing I haven't figured out is how to get Requery to use a many to many mapping table (typical sql table w/ two columns w/ foreign keys in each).

Other tips I would have found useful beforehand (I should probably write this up for the wiki):
- you can run sqlite3 on the db and type in ".schema" to dump the schema
- when defining the table, use the @Table tag to directly map the existing table to the entity
```
@Entity
@Table(name="mytable")
```
- when defining the columns, use the @Column tag to directly map the existing columns:
`@Column(name="someColumn")`
- directly name the database in your DataSource and also set that the column names be quoted because they may be named in conflict w/ SQL keywords:
```
DatabaseSource source = new DatabaseSource(mContext, Models.DEFAULT,
                AssetDBHelper.DATABASE_NAME, AssetDBHelper.DATABASE_VERSION) {
            @Override
            protected void onConfigure(ConfigurationBuilder builder) {
                super.onConfigure(builder);
                builder.setQuoteColumnNames(true);
            }
        };
```

**Comment by npurushe** [comment]
Table/Column are optional, if your class and field names match those in the schema exactly you can just omit them. @JunctionTable is used to define the Many-to-many junction table. A simple example is [here](https://github.com/requery/requery/tree/master/requery-test/src/main/java/io/requery/test/model3)

**Comment by kenkyee** [comment]
But how do you define the name of the @JunctionTable?  And how do you define the junction table's column names?  That example just tells it to use one.

I was hardcoding the table/column names to make sure it'd use the right ones.  I've gotten bitten in the past using Proguard obfuscation on Android w/ Gson where it used implicit column name mapping and the obfuscation converted the field names to a/b/c etc. :-)

**Comment by npurushe** [comment]
You can set the [name attribute](http://requery.github.io/javadoc/io/requery/JunctionTable.html) to define the name, by default it will be a concatenation of the joined table names with an underscore. Columns can also be optionally defined, but by default it uses a composite key of the joined type's keys.

**Comment by kenkyee** [comment]
This almost worked but I can't define the column names of the junction table.  The schema looks like this:

```
CREATE TABLE routes (route STRING PRIMARY KEY, color INTEGER, oppositecolor INTEGER, pathblob BLOB, listorder INTEGER, agencyid INTEGER, routetitle STRING);
CREATE TABLE stops (tag STRING PRIMARY KEY, lat FLOAT, lon FLOAT, title STRING, parent STRING);
CREATE TABLE stopmapping (route STRING, tag STRING, PRIMARY KEY (route, tag));
```

The tables look like this:

```
@Entity
@Table(name="routes")
public interface Routes {
    @Key
    @Column(name="route")
    String getRoute();

    @Column(name="color")
    int getColor();

    @Column(name="oppositecolor")
    int getOppositeColor();

    @Column(name="pathblob")
    byte[] getPathBlob();

    @Column(name="listorder")
    int getListOrder();

    @Column(name="agencyid")
    int getAgencyId();

    @Column(name="routetitle")
    String getRouteTitle();

    @ManyToMany
    Set<Stops> getStops();
}

@Entity
@Table(name="stops")
public interface Stops extends Persistable {
    @Key
    @Column(name="tag")
    String getTag();

    @Column(name="lat")
    float getLat();

    @Column(name="lon")
    float getLon();

    @Column(name="title")
    String getTitle();

    @JunctionTable(name="stopmapping")
    @ManyToMany
    Set<Routes> getRoutes();
}
```

And the error I get is this (note that it's thinking the column named tag in the mapping table should be named stopsId):

`android.database.sqlite.SQLiteException: no such column: b.stopsId (code 1): , while compiling: select a."tag", a."lat", a."lon", a."title" from stops a inner join stopmapping b on a."tag" = b."stopsId" inner join routes c on b."routesId" = c."route" where c."route" = ?`

**Comment by npurushe** [comment]
You should define the stopmapping type as an entity and use @JunctionTable.type to set it otherwise requery will just generate a default stopmapping entity w/ default column names that in this case doesn't match your table definition.

**Comment by kenkyee** [comment]
Tried this:

```
@Entity
@Table(name="stops")
public interface Stops extends Persistable {
    @Key
    @Column(name="tag")
    String getTag();

    @Column(name="lat")
    float getLat();

    @Column(name="lon")
    float getLon();

    @Column(name="title")
    String getTitle();

    @JunctionTable(type=StopMapping.class)
    @ManyToMany
    Set<Routes> getRoutes();
}
```

also tried type="StopMappingEntity.class"
but the compile error says:

> Error:Execution failed for task ':mobile:compileDevDebugJavaWithJavac'.
> java.lang.IllegalArgumentException: couldn't make a guess for 

The stopmapping table is defined as:

```
@Entity
public interface StopMapping {
    @Column(name="route")
    String getRoute();

    @Column(name="tag")
    String getTag();
}

```

Can't find an example in the repo or the code where it handles the type attribute...

**Comment by npurushe** [comment]
Do you have the full stack trace?

**Comment by kenkyee** [comment]
Here's the exception if I use type=StopMapping.class:

`
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mobile:compileDevDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: couldn't make a guess for 
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: java.lang.IllegalArgumentException: couldn't make a guess for 
	at io.requery.com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at io.requery.com.squareup.javapoet.ClassName.bestGuess(ClassName.java:159)
	at io.requery.processor.EntityNameResolver.joinEntityName(EntityNameResolver.java:68)
	at io.requery.processor.EntityGenerator.lambda$generateJunctionType$27(EntityGenerator.java:819)
	at io.requery.processor.EntityGenerator.generateJunctionType(EntityGenerator.java:819)
	at io.requery.processor.EntityGenerator.lambda$generateAttribute$25(EntityGenerator.java:754)
	at io.requery.processor.EntityGenerator.generateAttribute(EntityGenerator.java:749)
	at io.requery.processor.EntityGenerator.lambda$generateStaticMetadata$16(EntityGenerator.java:551)
	at io.requery.processor.EntityGenerator.generateStaticMetadata(EntityGenerator.java:528)
	at io.requery.processor.EntityGenerator.generate(EntityGenerator.java:148)
	at io.requery.processor.EntityProcessor.process(EntityProcessor.java:191)
	at org.jetbrains.kotlin.annotation.AnnotationProcessorWrapper.process(AnnotationProcessorWrapper.kt:115)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 34 more


BUILD FAILED`


Here's what I get if I use type=StopMappingEntity.class:

`* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mobile:compileDevDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: couldn't make a guess for 
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: java.lang.IllegalArgumentException: couldn't make a guess for 
	at io.requery.com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at io.requery.com.squareup.javapoet.ClassName.bestGuess(ClassName.java:159)
	at io.requery.processor.EntityNameResolver.joinEntityName(EntityNameResolver.java:68)
	at io.requery.processor.EntityGenerator.lambda$generateJunctionType$27(EntityGenerator.java:819)
	at io.requery.processor.EntityGenerator.generateJunctionType(EntityGenerator.java:819)
	at io.requery.processor.EntityGenerator.lambda$generateAttribute$25(EntityGenerator.java:754)
	at io.requery.processor.EntityGenerator.generateAttribute(EntityGenerator.java:749)
	at io.requery.processor.EntityGenerator.lambda$generateStaticMetadata$16(EntityGenerator.java:551)
	at io.requery.processor.EntityGenerator.generateStaticMetadata(EntityGenerator.java:528)
	at io.requery.processor.EntityGenerator.generate(EntityGenerator.java:148)
	at io.requery.processor.EntityProcessor.process(EntityProcessor.java:191)
	at org.jetbrains.kotlin.annotation.AnnotationProcessorWrapper.process(AnnotationProcessorWrapper.kt:115)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 34 more
`
