### ISSUE TITLE
Stackoverflow when upserting

### ISSUE THREAD

**Issue by Glurt** [requery/requery#205]
I get a Stackoverflow with the following exception:

Caused by: java.lang.StackOverflowError: stack size 1037KB
                                                                            at android.database.sqlite.SQLiteConnection$OperationLog.endOperation(SQLiteConnection.java:1355)
                                                                            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:525)
                                                                            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                            at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:996)
                                                                            at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38)
                                                                            at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:127)
                                                                            at io.requery.sql.ConnectionDelegate.prepareStatement(ConnectionDelegate.java:225)
                                                                            at io.requery.sql.PreparedQueryOperation.prepare(PreparedQueryOperation.java:58)
                                                                            at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:66)
                                                                            at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:55)
                                                                            at io.requery.query.BaseScalar.value(BaseScalar.java:49)
                                                                            at io.requery.sql.EntityWriter.update(EntityWriter.java:594)
                                                                            at io.requery.sql.EntityWriter.upsert(EntityWriter.java:494)
                                                                            at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:932)
                                                                            at io.requery.sql.EntityWriter.update(EntityWriter.java:575)
                                                                            at io.requery.sql.EntityWriter.upsert(EntityWriter.java:494)
                                                                            at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:932)
                                                                            at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:641)
                                                                            at io.requery.sql.EntityWriter.update(EntityWriter.java:600)
                                                                            at io.requery.sql.EntityWriter.upsert(EntityWriter.java:494)
                                                                            at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:932)

It seems to be related to these two entities:

````
@Entity(stateless = true)
public abstract class AbstractMedia implements Persistable {

    @Key
    String id = UUID.randomUUID().toString();

    @OneToOne(mappedBy = "media")
    Submission submission;

    @ForeignKey
    @OneToOne(cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    OEmbed oembed;

    String type;

}
````

````
@Entity(stateless = true)
public abstract class AbstractOEmbed implements Persistable {

    @Key
    String id = UUID.randomUUID().toString();

    @OneToOne(mappedBy = "oembed")
    Media media;

    String provider_url;
    String description;
    String title;
    String url;
    String type;
    String author_name;
    String author_url;
    int thumbnail_height;
    int thumbnail_width;
    String thumbnail_url;
}
````

As always I'll keep doing some debugging but if you spot any glaring issues let me know.

**Comment by Glurt** [comment]
Quick question; I've followed the Person and Phone example that you provided but I'm using Abstract classes rather than interfaces. My theory is that since it's a class and not an interface, when the entity is being written into the database it's picking up relationships and getting stuck in an endless loop.

For example, when writing Media it's finding OEmbed and writing that, but then within OEmbed it's finding Media and rewriting that, finding OEmbed again etc etc.

**Comment by npurushe** [comment]
Wether it's an interface or class won't make a difference, this maybe likely happening because you modified both sides of the relationship before persisting them, when you only to need to modify one side and then persist. But either way it shouldn't stackoverflow will look into it.

**Comment by Glurt** [comment]
The whole hierarchy is created from a web response so you're correct that both are modified, they are all stateless as well so I suppose this will always be the case.
