### ISSUE TITLE
No key in provided entity when upgrading from beta18 to beta23

### ISSUE THREAD

**Issue by vanniktech** [requery/requery#214]
When `upserting` we're getting `No key in provided entity` with beta23. Before that we were running on beta18 and we had no problems and also didn't change anything between the two versions.

This is a simplification of our persisted class:

```java
@AutoValue
@Entity
public abstract class MyClass {
    public static final int ID = 0;

    @NonNull
    public static Builder builder() {
        return new AutoValue_MyClass.Builder();
    }

    // Some more properties

    public int getId() {
        return ID;
    }
}
```

Basically we always only want one entry of that class in all the tables hence we were using `upsert` on it.

Even adding `@Key` on the `getId()` method won't help. Still getting `No Key in provided entity` exception.

Is this a bug between beta18 and beta23 or is there anything wrong with our model class?

**Comment by npurushe** [comment]
Do you have the full stacktrace? thanks. Looks like this problem would be fixed by marking the id field with @Key, that should work make sure you are doing a full build after that change

**Comment by vanniktech** [comment]
I tried this

```java
@Key
public int getId() {
    return ID:
}
```

and it didn't work. I'll give you the full stacktrace soon as I'm right now not able to get it right away.

**Comment by vanniktech** [comment]
@npurushe  there you go

```
No key in provided entity
 io.requery.sql.MissingKeyException: No key in provided entity
     at io.requery.sql.EntityWriter.update(EntityWriter.java:507)
     at io.requery.sql.EntityWriter.upsert(EntityWriter.java:494)
     at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:274)
     at my.package.persistance.shiny.RequeryDatabase.upsert(RequeryDatabase.java:35)
     at my.package.interactors.FeatureFlagsInteractor.lambda$loadFeatureFlags$0(FeatureFlagsInteractor.java:53)
     at my.package.interactors.FeatureFlagsInteractor$$Lambda$1.call(Unknown Source)
     at rx.Single$16.onNext(Single.java:1591)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
     at android.os.Handler.handleCallback(Handler.java:751)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6044)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by npurushe** [comment]
That exception is only thrown if the type being persisted has zero keys. I would double check your type for ID has setKey(true) in the generated code.

**Comment by vanniktech** [comment]
@npurushe unfortunately this still does not work with `rc1`. I'm still getting the exception.

```
io.requery.sql.MissingKeyException: No key in provided entity

	at io.requery.sql.EntityWriter.update(EntityWriter.java:505)
	at io.requery.sql.EntityWriter.upsert(EntityWriter.java:493)
	at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:264)
	at net.familo.android.persistance.shiny.RequeryDatabase.upsert(RequeryDatabase.java:36)
	at net.familo.android.persistance.shiny.RequeryDatabaseTest.clearShouldKeepFeatureFlags(RequeryDatabaseTest.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

Also in the generated code it looks like there's nothing generated for:

```java
@Key
public int getId() {
    return ID;
}
```

In the generated `$TYPE` variable there's no call with `addAttribute(ID)` and also there's no `QueryAttribute` generated for the id.

**Comment by npurushe** [comment]
Yeah I think the issue here is you're inside an AutoValue class but implementing the method, for an @AutoValue class you should not implement `getId()` but instead define it as `@Key public abstract int getId()`
