### ISSUE TITLE
dex2oat fails in runtime

### ISSUE THREAD

**Issue by uKL** [requery/requery#227]
## Given
- Any Android OS with ART
- multidex enabled 1.0.1
- compile 'io.requery:requery:1.0.0-rc2'
- compile 'io.requery:requery-android:1.0.0-rc2'
- compile 'io.requery:requery-kotlin:1.0.0-rc2'
- kapt 'io.requery:requery-processor:1.0.0-rc2'
- kotlin 1.0.3

## Description
While using Kotlin data store, the application compiles but installing the app fails with
```
4425 KB/s (43996204 bytes in 9.708s)
	pkg: /data/local/tmp/app-debug.apk
Failure [INSTALL_FAILED_DEXOPT]
```

On the ADB console I can see:

```
07-21 13:17:33.823 5484-5484 E/dex2oat: Failed to open dex from file descriptor for zip file '/data/app/my.package-1/base.apk': Failure to verify dex file '/data/app/my.package-1/base.apk': Invalid method name: '!='
07-21 13:17:33.923 1250-4008 I/art: Explicit concurrent mark sweep GC freed 115598(4MB) AllocSpace objects, 33(1612KB) LOS objects, 32% free, 65MB/97MB, paused 2.995ms total 207.774ms
07-21 13:17:34.013 5127-5488 I/art: Explicit concurrent mark sweep GC freed 136267(6MB) AllocSpace objects, 0(0B) LOS objects, 35% free, 29MB/45MB, paused 483us total 54.522ms
07-21 13:17:34.033 474-474 E/installd: DexInv: --- END '/data/app/my.package-1/base.apk' --- status=0x0100, process failed
07-21 13:17:34.043 1250-1337 W/PackageManager: Package couldn't be installed in /data/app/my.package-1
                                               com.android.server.pm.PackageManagerException: scanPackageLI
                                                   at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:7180)
                                                   at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:6463)
                                                   at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:11738)
                                                   at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12329)
                                                   at com.android.server.pm.PackageManagerService.access$2700(PackageManagerService.java:275)
                                                   at com.android.server.pm.PackageManagerService$8.run(PackageManagerService.java:10074)
                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                   at android.os.Looper.loop(Looper.java:135)
                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                   at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

Looks like `Conditional` interface method `!=` causes some issues.

**Comment by npurushe** [comment]
Thanks for reporting this is an unfortunate limitation in Android's runtime will remove those method aliases to work around it
