### ISSUE TITLE
error on calling upsert on android sqlite

### ISSUE THREAD

**Issue by aegis123** [requery/requery#247]
I'm getting an `java.sql.SQLIntegrityConstraintViolationException: UNIQUE constraint failed` when calling upsert on the datastore on Android. I thought that it would do a insert or replace. Is there a way of adding a Constraint on the column to replace on conflict?

**Comment by npurushe** [comment]
Can you post the full stack trace? thanks

**Comment by npurushe** [comment]
Closing for now, please post back if you have any update

**Comment by aegis123** [comment]
Sorry it took some time. My entity look like this

```
@Entity
@AutoValue
public abstract class ThreadEntity implements Persistable {

    @Key
    @NonNull
    public abstract String id();

    @NonNull
    public abstract String subject();

    @NonNull
    public abstract Calendar createdAt();

    @Nullable
    @ForeignKey(references = AccountEntity.class, delete = ReferentialAction.NO_ACTION, update = ReferentialAction.NO_ACTION)
    public abstract AccountEntity createdBy();

    @Nullable
    @ForeignKey(references = AccountEntity.class, delete = ReferentialAction.NO_ACTION, update = ReferentialAction.NO_ACTION)
    public abstract List<AccountEntity> participants();

    @Nullable
    public abstract List<MessageDb> messages();

    public static ThreadEntity create(@NonNull String id,
                                      @NonNull String subject,
                                      @NonNull Calendar createdAt,
                                      @Nullable AccountEntity createdBy,
                                      @Nullable List<AccountEntity> participants,
                                      @Nullable List<MessageDb> messages) {
        return new AutoValue_ThreadEntity(id, subject, createdAt, createdBy, participants, messages);
    }
}
```

And here is the stacktrace for the upsert.

```
E/SQLiteLog: (1555) abort at 15 in [insert into ThreadEntity (id, createdAt, createdBy, messages, participants, subject) values (?, ?, ?, ?, ?, ?)]: UNIQUE constraint failed: ThreadEntity.id
E/InboxFragment: error error
io.requery.PersistenceException: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: ThreadEntity.id (code 1555)
     at io.requery.sql.BatchUpdateOperation.evaluate(BatchUpdateOperation.java:90)
     at io.requery.sql.BatchUpdateOperation.evaluate(BatchUpdateOperation.java:35)
     at io.requery.query.element.QueryElement.get(QueryElement.java:317)
     at io.requery.sql.EntityWriter.batchInsert(EntityWriter.java:277)
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:223)
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:211)
     at io.requery.rx.SingleEntityStoreFromBlocking$2.get(SingleEntityStoreFromBlocking.java:93)
     at io.requery.rx.SingleEntityStoreFromBlocking$2.get(SingleEntityStoreFromBlocking.java:90)
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)
     at rx.Single$1.call(Single.java:90)
     at rx.Single$1.call(Single.java:70)
     at rx.Single.subscribe(Single.java:1839)
     at rx.Single.subscribe(Single.java:1916)
     at rx.Single$19$1.call(Single.java:1971)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
  Caused by: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: ThreadEntity.id (code 1555)
     at io.requery.android.sqlite.BaseConnection.throwSQLException(BaseConnection.java:69)
     at io.requery.android.sqlitex.SqlitexPreparedStatement.executeUpdate(SqlitexPreparedStatement.java:158)
     at io.requery.sql.BatchUpdateOperation.evaluate(BatchUpdateOperation.java:72)
     at io.requery.sql.BatchUpdateOperation.evaluate(BatchUpdateOperation.java:35) 
     at io.requery.query.element.QueryElement.get(QueryElement.java:317) 
     at io.requery.sql.EntityWriter.batchInsert(EntityWriter.java:277) 
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:223) 
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:211) 
     at io.requery.rx.SingleEntityStoreFromBlocking$2.get(SingleEntityStoreFromBlocking.java:93) 
     at io.requery.rx.SingleEntityStoreFromBlocking$2.get(SingleEntityStoreFromBlocking.java:90) 
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34) 
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23) 
     at rx.Single$1.call(Single.java:90) 
     at rx.Single$1.call(Single.java:70) 
     at rx.Single.subscribe(Single.java:1839) 
     at rx.Single.subscribe(Single.java:1916) 
     at rx.Single$19$1.call(Single.java:1971) 
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
     at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
     at java.lang.Thread.run(Thread.java:818) 
  Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: ThreadEntity.id (code 1555)
     at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
     at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:762)
     at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:764)
     at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:68)
     at io.requery.android.sqlitex.SqlitexPreparedStatement.executeUpdate(SqlitexPreparedStatement.java:156)
     at io.requery.sql.BatchUpdateOperation.evaluate(BatchUpdateOperation.java:72) 
     at io.requery.sql.BatchUpdateOperation.evaluate(BatchUpdateOperation.java:35) 
     at io.requery.query.element.QueryElement.get(QueryElement.java:317) 
     at io.requery.sql.EntityWriter.batchInsert(EntityWriter.java:277) 
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:223) 
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:211) 
     at io.requery.rx.SingleEntityStoreFromBlocking$2.get(SingleEntityStoreFromBlocking.java:93) 
     at io.requery.rx.SingleEntityStoreFromBlocking$2.get(SingleEntityStoreFromBlocking.java:90) 
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34) 
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23) 
     at rx.Single$1.call(Single.java:90) 
     at rx.Single$1.call(Single.java:70) 
     at rx.Single.subscribe(Single.java:1839) 
     at rx.Single.subscribe(Single.java:1916) 
     at rx.Single$19$1.call(Single.java:1971) 
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
     at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
     at java.lang.Thread.run(Thread.java:818) 
```
