### ISSUE TITLE
How to get CommonDataSource instance for KotlinConfiguration on Android?

### ISSUE THREAD

**Issue by I60R** [requery/requery#261]
DatabaseSource class used in Android example don't implement this interface

**Comment by npurushe** [comment]
Hi DatabaseSource provides it's own Configuration instance already. So you just need:
`val store = KotlinEntityDataStore<Persistable>(databaseSource.configuration);`

**Comment by I60R** [comment]
Thanks. Using it I got following output:  
 
```
08/25 13:27:16: Launching app
$ adb push /home/user/Android/app/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.pkg.app
$ adb shell pm install -r "/data/local/tmp/com.pkg.app"
	pkg: /data/local/tmp/com.pkg.app
Success


$ adb shell am start -n "com.pkg.app/com.pkg.app.MyApplicationActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.pkg.app.test | com.pkg.app
Connecting to com.pkg.app
W/ActivityThread: Application com.pkg.app is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8601', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1485)
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --compiler-filter=speed --instruction-set-variant=cortex-a15 --instruction-set-features=default --dex-file=/data/app/com.pkg.app-2/base.apk --oat-file=/data/dalvik-cache/arm/data@app@com.pkg.app-2@base.apk@classes.dex) because non-0 exit status
W/art: Failure to verify dex file '/data/app/com.pkg.app-2/base.apk': Invalid method name: '!='
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.pkg.app, PID: 21415
                  java.lang.RuntimeException: Unable to instantiate application com.pkg.app.MyApplication: java.lang.ClassNotFoundException: Didn't find class "com.pkg.app.MyApplication" on path: DexPathList[[zip file "/data/app/com.pkg.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.pkg.app-2/lib/arm, /data/app/com.pkg.app-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:676)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6290)
                      at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7225)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pkg.app.MyApplication" on path: DexPathList[[zip file "/data/app/com.pkg.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.pkg.app-2/lib/arm, /data/app/com.pkg.app-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6290) 
                      at android.app.ActivityThread.access$1800(ActivityThread.java:221) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:158) 
                      at android.app.ActivityThread.main(ActivityThread.java:7225) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                  	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.pkg.app-2/base.apk
                      at dalvik.system.DexFile.openDexFileNative(Native Method)
                      at dalvik.system.DexFile.openDexFile(DexFile.java:295)
                      at dalvik.system.DexFile.<init>(DexFile.java:80)
                      at dalvik.system.DexFile.<init>(DexFile.java:59)
                      at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
                      at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
                      at dalvik.system.DexPathList.<init>(DexPathList.java:120)
                      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
                      at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:84)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:45)
                      at android.app.LoadedApk.getClassLoader(LoadedApk.java:434)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:659)
                      		... 9 more
                  	Suppressed: java.lang.ClassNotFoundException: com.pkg.app.MyApplication
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 12 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by npurushe** [comment]
I think this is just an unrelated Android studio instant run bug, you should be able to clean and rebuild and should be fine unless there is something else you have going on.

**Comment by I60R** [comment]
I have disabled instant run, and unfortunately, clean and rebuild don't help. Error happens only when requery included in project.
Also, notice line `W/art: Failure to verify dex file '/data/app/com.pkg.app-2/base.apk': Invalid method name: '!='`
Maybe it is related to #227

**Comment by npurushe** [comment]
Right that issue is fixed and resolved though, so make sure you are using the latest version 1.0.0-rc3

**Comment by I60R** [comment]
Right. My wersion was `rc2`. Upgraded, and it works. Thank you
