### ISSUE TITLE
OneToOne always inserts instead of updates

### ISSUE THREAD

**Issue by dasheck0** [requery/requery#30]
Hi,

I just played around with the library. I created a simple User and a Phone model, whereas a User always has a phone number. The code is as follows:

```
@Entity public interface UserDatabaseEntity extends Persistable {

  @Key int getId();

  String getUsername();

  String getEmail();

  @ForeignKey @OneToOne PhoneDatabaseEntity getPhone();
}
```
```
@Entity public interface PhoneDatabaseEntity extends Persistable {

  @Key int getId();

  String getNumber();

  @OneToOne(mappedBy = "phone") UserDatabaseEntity getUser();
}
```
```
private void storeUser() {
    UserDatabaseEntityEntity user = new UserDatabaseEntityEntity();
    user.setId(0);
    user.setEmail("fghjklÖ");
    user.setUsername("fghbjnkl");

    PhoneDatabaseEntityEntity phone = new PhoneDatabaseEntityEntity();
    phone.setId(0);
    phone.setNumber("1234567890");

    user.getAddresses().add(address1);
    user.getAddresses().add(address2);
    user.setPhone(phone);

    if (store.select(UserDatabaseEntity.class).where(UserDatabaseEntityEntity.ID.eq(user.getId())).get().firstOrNull()
        == null) {
      Log.d("TAG", "No user found -> inserting");
      store.insert(user);
    } else {
      Log.d("TAG", "Found user with id -> updating");
      store.update(user);
    }
  }
```
When I and the code once all gets inserted into the database as expected. After that I get the following exception. It says that it cannot create another phone entity, since there is already one with the given id. Note that I want to set the ids myself and do not want to use auto generated ids. There is a reason for that. Also it seems that the phone is inserted even when I update the user. Shouldn't it update the phone too instead of inserting? Maybe I am doing something wrong?

EDIT: This does not happen when using one to many relationships.

Best regards 
dasheck
```
03-09 10:27:38.924 27648-27648/com.requerytest E/SQLiteLog: (1555) abort at 9 in [insert into PhoneDatabaseEntity (id, number) values (?, ?)]: UNIQUE constraint failed: PhoneDatabaseEntity.id
03-09 10:27:38.928 27648-27648/com.requerytest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.requerytest, PID: 27648
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.requerytest/com.requerytest.MainActivity}: io.requery.PersistenceException: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: PhoneDatabaseEntity.id (code 1555)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                         Caused by: io.requery.PersistenceException: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: PhoneDatabaseEntity.id (code 1555)
                                                                            at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:76)
                                                                            at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:49)
                                                                            at io.requery.query.SuppliedScalar.value(SuppliedScalar.java:51)
                                                                            at io.requery.sql.EntityWriter.insert(EntityWriter.java:422)
                                                                            at io.requery.sql.EntityWriter.cascadeInsert(EntityWriter.java:737)
                                                                            at io.requery.sql.EntityWriter.update(EntityWriter.java:465)
                                                                            at io.requery.sql.EntityDataStore.update(EntityDataStore.java:216)
                                                                            at com.requerytest.MainActivity.storeUser(MainActivity.java:57)
                                                                            at com.requerytest.MainActivity.onCreate(MainActivity.java:25)
                                                                            at android.app.Activity.performCreate(Activity.java:5990)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                         Caused by: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: PhoneDatabaseEntity.id (code 1555)
                                                                            at io.requery.android.sqlite.DatabaseConnection.throwSQLException(DatabaseConnection.java:77)
                                                                            at io.requery.android.sqlite.PreparedStatementAdapter.executeUpdate(PreparedStatementAdapter.java:208)
                                                                            at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:70)
                                                                            at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:49) 
                                                                            at io.requery.query.SuppliedScalar.value(SuppliedScalar.java:51) 
                                                                            at io.requery.sql.EntityWriter.insert(EntityWriter.java:422) 
                                                                            at io.requery.sql.EntityWriter.cascadeInsert(EntityWriter.java:737) 
                                                                            at io.requery.sql.EntityWriter.update(EntityWriter.java:465) 
                                                                            at io.requery.sql.EntityDataStore.update(EntityDataStore.java:216) 
                                                                            at com.requerytest.MainActivity.storeUser(MainActivity.java:57) 
                                                                            at com.requerytest.MainActivity.onCreate(MainActivity.java:25) 
                                                                            at android.app.Activity.performCreate(Activity.java:5990) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                         Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: PhoneDatabaseEntity.id (code 1555)
                                                                            at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                            at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
                                                                            at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                                            at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                                            at io.requery.android.sqlite.PreparedStatementAdapter.executeUpdate(PreparedStatementAdapter.java:206)
                                                                            at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:70) 
                                                                            at io.requery.sql.UpdateOperation$1.get(UpdateOperation.java:49) 
                                                                            at io.requery.query.SuppliedScalar.value(SuppliedScalar.java:51) 
                                                                            at io.requery.sql.EntityWriter.insert(EntityWriter.java:422) 
                                                                            at io.requery.sql.EntityWriter.cascadeInsert(EntityWriter.java:737) 
                                                                            at io.requery.sql.EntityWriter.update(EntityWriter.java:465) 
                                                                            at io.requery.sql.EntityDataStore.update(EntityDataStore.java:216) 
                                                                            at com.requerytest.MainActivity.storeUser(MainActivity.java:57) 
                                                                            at com.requerytest.MainActivity.onCreate(MainActivity.java:25) 
                                                                            at android.app.Activity.performCreate(Activity.java:5990) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by npurushe** [comment]
Hi in storeUser() you check if the User exists or not and then update it which is ok. However you are not doing this for the Phone. In the first run of the code you insert a new User (id 0) and Phone (id 0). In the second run of the code you update User (id 0) which a new Phone (id 0). The library will not know the Phone (id 0) already exists in the db since you are creating a new one so by default it will insert it. 

You should instead try fetching the User with id 0, if it exists get it's Phone via getPhone() check if it that exists and only create a new Phone if it doesn't. Hope that makes sense.

**Comment by dasheck0** [comment]
Thanks for the fast reply. It does make sense. On the other hand I would like cascading save actions on the phone (or is this only supported for OneToMany relationships). Look at the code. I am never saving the phone directly, but implicitly by saving the user. 

To make this correct and thus a little complicated I would disable cascade saving and save the phone and after that the user. Then I can check if both exist and upsert (insert or update if exists) them correctly. But I wanted to only upsert the user. Is this possible even wanted with this library?

Don't get my wrong. Your way may work but I find it too overdone. May aim is to use the cascading feature here.

**Comment by npurushe** [comment]
Yes you can disable cascading via the annotation `@OneToOne(cascade = CascadeAction.NONE)`, it is fully configurable.

**Comment by dasheck0** [comment]
Maybe this is a way to get this work. Is there still a way to upsert users with their phone numbers properly, while still using non generated keys?

**Comment by npurushe** [comment]
I think the basic problem is that you have to be know that a phone with that id exists so it can be updated, which means checking for it first (either via the relation or via the query). If you mean upsert support on the database level SQLite doesn't really have upsert, it has insert/replace which is not the same and is a bit dangerous because it will delete previous data and doesn't work well with Foreign key constraints.
