### ISSUE TITLE
[Android] Blocking on runInTransaction

### ISSUE THREAD

**Issue by wolkenschieber** [requery/requery#319]
Hi,

I'm trying to initially populate a database in the [MainActivity](https://gist.github.com/wolkenschieber/a8b5e8e26ef29218b4297d509fbe88b3#file-mainactivity-java). 
The observerable containing the insert operations are defined in the [CreateLotteries](https://gist.github.com/wolkenschieber/a8b5e8e26ef29218b4297d509fbe88b3#file-createlotteries-java) helper. Since the data comprises entries in different tables, they should run in an transaction.

However on executing the transaction (or subscribing to it), the app blocks and [logs](https://gist.github.com/wolkenschieber/a8b5e8e26ef29218b4297d509fbe88b3#file-log-output) `
W/SQLiteConnectionPool: The connection pool for database '/data/user/0/app/databases/default' has been unable to grant a connection
`.

The population seems to work, if the insert is done without the transaction.

I attached an excerpt of the datamodel in a [gist](https://gist.github.com/wolkenschieber/a8b5e8e26ef29218b4297d509fbe88b3).

Am I doing something wrong, my conversion of the transaction parameter looks a little bit strange to me.

Thanks in advance.

**Comment by npurushe** [comment]
Hi if you remove the `observeOn(Schedulers.io())` do you still encounter the same problem?

**Comment by wolkenschieber** [comment]
Yes, the behaviour stay the same with `observable.subscribe()`.

**Comment by wolkenschieber** [comment]
When testing different transaction modes, I found out that

* `TransactionMode.NONE` inserts the data as excepted (but without transactions)
* `TransactionMode.MANAGED` results in a `java.lang.NoClassDefFoundError: Failed resolution of: Lio/requery/sql/ManagedTransaction;`
* `TransactionMode.AUTO` leads to above blocking behaviour

**Comment by wolkenschieber** [comment]
The thread dump in blocking state, looks like a deadlock. Maybe one transaction wants to start before another one is finished?

```
"main@4348" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks main@4348
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:2127)
	  - locked <0x14bd> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:840)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:203)
	  at rx.internal.util.BlockingUtils.awaitForComplete(BlockingUtils.java:49)
	  at rx.singles.BlockingSingle.value(BlockingSingle.java:85)
	  at io.requery.rx.SingleEntityStoreFromBlocking$17$1.call(SingleEntityStoreFromBlocking.java:335)
	  at io.requery.rx.SingleEntityStoreFromBlocking$17$1.call(SingleEntityStoreFromBlocking.java:329)
	  at io.requery.sql.EntityDataStore.runInTransaction(EntityDataStore.java:525)
	  at io.requery.sql.EntityDataStore.runInTransaction(EntityDataStore.java:535)
	  at io.requery.rx.SingleEntityStoreFromBlocking$17.call(SingleEntityStoreFromBlocking.java:329)
	  at io.requery.rx.SingleEntityStoreFromBlocking$17.call(SingleEntityStoreFromBlocking.java:326)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	  at rx.Observable.subscribe(Observable.java:10296)
	  at rx.Observable.subscribe(Observable.java:10263)
	  at rx.Observable.subscribe(Observable.java:10038)
	  at MainActivity.populateDatabase(MainActivity.java:121)
```

```
"pool-1-thread-1@5305" prio=5 tid=0x79 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks pool-1-thread-1@5305
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:2127)
	  - locked <0x14c7> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
	  at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:670)
	  at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
	  at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
	  at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:310)
	  at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
	  at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:507)
	  at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:442)
	  at io.requery.android.sqlite.SqliteConnection.ensureTransaction(SqliteConnection.java:56)
	  at io.requery.android.sqlite.BaseConnection.setAutoCommit(BaseConnection.java:188)
	  at io.requery.sql.ConnectionTransaction.begin(ConnectionTransaction.java:81)
	  at io.requery.sql.ThreadLocalTransaction.begin(ThreadLocalTransaction.java:66)
	  at io.requery.sql.ThreadLocalTransaction.begin(ThreadLocalTransaction.java:48)
	  at io.requery.sql.TransactionScope.<init>(TransactionScope.java:39)
	  at io.requery.sql.TransactionScope.<init>(TransactionScope.java:33)
	  at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:195)
	  at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:189)
	  at io.requery.rx.SingleEntityStoreFromBlocking$1.get(SingleEntityStoreFromBlocking.java:83)
	  at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
	  at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)
	  at rx.Single.subscribe(Single.java:1798)
	  at rx.Single$15$1.call(Single.java:1870)
	  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	  at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	  at java.lang.Thread.run(Thread.java:761)
```

**Comment by npurushe** [comment]
Thanks for the update, working on reproducing it

**Comment by wolkenschieber** [comment]
I stripped down the app to a minimal scenario reproducing the issue.

**Comment by npurushe** [comment]
Hi thanks for the detailed example. There were some significant issues with the original implementation that are now fixed. However on Android you have to extra careful to use a single threaded rx scheduler (e.g. not Schedulers.io()) for all write operations to prevent the connection not available problem.

**Comment by wolkenschieber** [comment]
Great to hear that you resolved the issue to fast. I will be glad to test this with single threaded scheduler, `Schedulers.from(Executors.newSingleThreadExecutor())`. Thanks for the hint!
