### ISSUE TITLE
Example Android App crash

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#329]
Hi there,

the example Android App crashes immediately after installation. Tested on the emulator with Android API 22 and the latest source code.

```Java
 java.lang.RuntimeException: Unable to start activity ComponentInfo{io.requery.android.example.app/io.requery.android.example.app.PeopleActivity}: rx.exceptions.OnErrorNotImplementedException: java.sql.SQLException: android.database.sqlite.SQLiteException: near "Group": syntax error (code 1): , while compiling: create table Group (id integer primary key autoincrement not null, name varchar(255))
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
     at android.app.ActivityThread.access$800(ActivityThread.java:151)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5254)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
  Caused by: rx.exceptions.OnErrorNotImplementedException: java.sql.SQLException: android.database.sqlite.SQLiteException: near "Group": syntax error (code 1): , while compiling: create table Group (id integer primary key autoincrement not null, name varchar(255))
     at rx.Single$15.onError(Single.java:1637)
     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
     at rx.Single$1$1.onError(Single.java:84)
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:37)
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)
     at rx.Single$1.call(Single.java:89)
     at rx.Single$1.call(Single.java:69)
     at rx.Single.subscribe(Single.java:1824)
     at rx.Single.subscribe(Single.java:1628)
     at io.requery.android.example.app.PeopleActivity.onCreate(PeopleActivity.java:72)
     at android.app.Activity.performCreate(Activity.java:5990)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:135) 
     at android.app.ActivityThread.main(ActivityThread.java:5254) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
  Caused by: io.requery.sql.TableModificationException: java.sql.SQLException: android.database.sqlite.SQLiteException: near "Group": syntax error (code 1): , while compiling: create table Group (id integer primary key autoincrement not null, name varchar(255))
     at io.requery.sql.SchemaModifier.createTables(SchemaModifier.java:142)
     at io.requery.android.sqlite.DatabaseSource.onCreate(DatabaseSource.java:201)
     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
     at io.requery.android.sqlite.DatabaseSource.getConnection(DatabaseSource.java:230)
     at io.requery.sql.EntityDataStore$DataContext.getConnection(EntityDataStore.java:607)
     at io.requery.sql.EntityDataStore.checkConnectionMetadata(EntityDataStore.java:546)
     at io.requery.sql.EntityDataStore$DataContext.getPlatform(EntityDataStore.java:685)
     at io.requery.sql.EntityDataStore$DataContext.getStatementGenerator(EntityDataStore.java:692)
     at io.requery.sql.gen.DefaultOutput.<init>(DefaultOutput.java:65)
     at io.requery.sql.SelectResult.createQuery(SelectResult.java:97)
     at io.requery.sql.SelectResult.iterator(SelectResult.java:106)
     at io.requery.query.BaseResult.iterator(BaseResult.java:123)
     at io.requery.query.BaseResult.first(BaseResult.java:87)
     at io.requery.sql.SelectCountOperation$1.evaluate(SelectCountOperation.java:42)
     at io.requery.sql.SelectCountOperation$1.evaluate(SelectCountOperation.java:38)
     at io.requery.query.BaseScalar.value(BaseScalar.java:49)
     at io.requery.query.BaseScalar$2.get(BaseScalar.java:98)
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
     at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23) 
     at rx.Single$1.call(Single.java:89) 
     at rx.Single$1.call(Single.java:69) 
     at rx.Single.subscribe(Single.java:1824) 
     at rx.Single.subscribe(Single.java:1628) 
     at io.requery.android.example.app.PeopleActivity.onCreate(PeopleActivity.java:72) 
     at android.app.Activity.performCreate(Activity.java:5990) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:135) 
     at android.app.ActivityThread.main(ActivityThread.java:5254) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by Agraphie** [comment]
The problem steams from the class `Group` in the example App. in SQLite "Group" is a reserved keyword (cf. http://www.sqlite.org/lang_keywords.html). If we add `@Table(name = "PersonGroup")` to the demo app, the crash is resolved. I'm hesistant to create a pull request though, because "Group" was always a reserved keyword yet the demo app must have worked before.

**Comment by npurushe** [comment]
Hi yes correct, that was added for illustrative purposes but not used in the app
