### ISSUE TITLE
Relationships not working with Java 8 Android Jack compiler

### ISSUE THREAD

**Issue by wa1demar** [requery/requery#332]
If enable jackOptions and add some relations to entities app it was crashed during build

`Caused by: java.lang.NullPointerException
        at io.requery.processor.Mirrors.namesEqual(Mirrors.java:159)
        at io.requery.processor.Mirrors.implementsInterface(Mirrors.java:109)
        at io.requery.processor.Mirrors.isInstance(Mirrors.java:91)
        at io.requery.processor.AttributeMember.validateCollectionType(AttributeMember.java:202)
        at io.requery.processor.AttributeMember.checkMemberType(AttributeMember.java:194)
        at io.requery.processor.AttributeMember.process(AttributeMember.java:147)
        at io.requery.processor.EntityType.lambda$process$5(EntityType.java:114)
        at io.requery.processor.EntityType.process(EntityType.java:114)
        at io.requery.processor.EntityProcessor.process(EntityProcessor.java:147)
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
`

**Comment by Glurt** [comment]
Is there an eta for this?

**Comment by npurushe** [comment]
1.0.2 contains this change
