### ISSUE TITLE
Creating insert query failed

### ISSUE THREAD

**Issue by stbychkov** [requery/requery#341]
Hi.
I have a entity with generated key and relations to other entities.
```java
@Entity
public abstract class AbstractLevel_1 implements Parcelable{

    @Key
    @Generated
    Integer mId;

    @OneToMany
    List<AbstractLevel_2_1> mLevel_2_1;

    @OneToMany
    List<AbstractLevel_2_2> mLevel_2_2;
}
```

When I try to insert this model into entity store, I get the SQLiteException.
Test:
```java
@Test
public void tryInsert(){
    Level_1 level1 = new Level_1();

    mEntityStore.upsert(level1).toBlocking().value();
    List<Level_1> insertedLevels = mEntityStore.select(Level_1.class).get().toList();

    assertNotSame(0, insertedLevels.size());
}
```

Stacktrace:
```
android.database.sqlite.SQLiteException: Cannot prepare statement, base error code: 1

	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getSqliteException(ShadowSQLiteConnection.java:495)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:464)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:388)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:79)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
	at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994)
	at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38)
	at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:147)
	at io.requery.sql.ConnectionDelegate.prepareStatement(ConnectionDelegate.java:237)
	at io.requery.sql.PreparedQueryOperation.prepare(PreparedQueryOperation.java:53)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:51)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
	at io.requery.query.BaseScalar.value(BaseScalar.java:49)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:446)
	at io.requery.sql.EntityWriter.upsert(EntityWriter.java:463)
	at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:280)
	at io.requery.rx.SingleEntityStoreFromBlocking$8.get(SingleEntityStoreFromBlocking.java:154)
	at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
	at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)
	at rx.Single$1.call(Single.java:90)
	at rx.Single$1.call(Single.java:70)
	at rx.Single.subscribe(Single.java:1839)
	at rx.Single.subscribe(Single.java:1916)
	at rx.Single$19$1.call(Single.java:1971)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() insert into Level_1 () default values [near ")": syntax error]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:143)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:459)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:388)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:79)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java)
	at android.database.sqlite.SQLiteSession.$$robo$$prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java)
	at android.database.sqlite.SQLiteProgram.$$robo$$__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$compileStatement(SQLiteDatabase.java:994)
	at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java)
	... 23 more
Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() insert into Level_1 () default values [near ")": syntax error]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:487)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:542)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:529)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:392)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:388)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

If I add some field into this entity, test passed. Is it so designed?

**Comment by npurushe** [comment]
requery wasn't generating an `insert default values` statement in this case, but generally having a table with just 1 generated column is not particularly useful

**Comment by npurushe** [comment]
1.0.2 contains this change

**Comment by PhobosXIII** [comment]
@npurushe bug is reproduced in version 1.4.0. When I try to insert  model with just 1 generated column into entity store, I get: 
`E/SQLiteLog: (1) near "FieldsSchema": syntax error`

If I add some field into model, all works fine.
