### ISSUE TITLE
StackOverflowError in ManagedTransaction.begin()

### ISSUE THREAD

**Issue by alex-shpak** [requery/requery#354]
Hi!
I was setting up some transactions for tests and ran into

```
java.lang.StackOverflowError
	at io.requery.sql.ManagedTransaction.begin(ManagedTransaction.java:131)
	at io.requery.sql.ManagedTransaction.begin(ManagedTransaction.java:131)
	at io.requery.sql.ManagedTransaction.begin(ManagedTransaction.java:131)
	at io.requery.sql.ManagedTransaction.begin(ManagedTransaction.java:131)
```

```java
    @Override
    public Transaction begin(TransactionIsolation isolation) {
        if (isolation != null) {
            throw new TransactionException("isolation can't be specified in managed mode");
        } else {
            return begin(null);
        }
    }
```

Looks like if I set `transactionIsolation` in configuration - it leads to exception and not setting `transactionIsolation` with `TransactionMode.MANAGED` leads to SO.

Please tell if you need some additional information.

**Comment by npurushe** [comment]
Thanks for reporting, yeah looks like that check is a bit out of date will update
