### ISSUE TITLE
io.requery.util.function.Supplier.get() on a null object reference

### ISSUE THREAD

**Issue by jashhk** [requery/requery#356]
Hi,

I am trying to insert a record to the database with RxJava in Android (which is Sqlite), and having trouble when inserting an entity with `@ManyToMany` relationship. It always throws `java.lang.NullPointerException` and gets nothing.

Below are two classes that I use.

```
@Entity
public interface Device extends Observable, Parcelable, Persistable {

    @Key
    @Index(value = "address_index")
    @Column(unique = true)
    @Bindable
    String getAddress();

    @Bindable
    int getRssi();

    @Bindable
    String getName();

    @Bindable
    String getNickname();

    @Bindable
    String getItemInfo();

    String getIcon();

    @Bindable
    boolean getIsEnabledAntilost();

    @Bindable
    int getDistance();

    @Bindable
    int getAlert();

    //@Column(value = "(strftime('%s','now'))")
    // No auto-generated timestamp :(
    long getCreateTime();

    @Bindable
    long getLastAntilostDate();

    @Bindable
    boolean getConnected();

    @Bindable
    int getStatus();

    @Bindable
    int getBatteryLevel();

    @ManyToMany(mappedBy = "devices")
    MutableResult<DeviceGattCharacteristic> getGattCharacteristic();
}
```

```
@Entity
public class DeviceGattCharacteristic {

    @Key
    protected UUID uuid;
    @Key
    protected int properties;
    @Key
    protected int permissions;

    @JunctionTable
    @ManyToMany
    protected MutableResult<DeviceEntity> devices;

    @Transient
    boolean notifiable;
    @Transient
    boolean readable;
    @Transient
    boolean writable;
    @Transient
    boolean broadcastable;
    @Transient
    boolean extended;
    @Transient
    boolean indictable;

    @PostLoad
    void afterLoad() {
        describeProperties();
    }

    @PostUpdate
    void afterUpdate() {
        describeProperties();
    }

    private void describeProperties() {
        notifiable = (BleGattUtil.isCharacteristicNotifiable(properties));
        readable = (BleGattUtil.isCharacteristicReadable(properties));
        writable = (BleGattUtil.isCharacteristicWritable(properties));
        broadcastable = (BleGattUtil.isCharacteristicBroadcastable(properties));
        extended = (BleGattUtil.isCharacteristicExtended(properties));
        indictable = (BleGattUtil.isCharacteristicIndictable(properties));
    }
}
```

Code (`DatabaseHelper.java`):
```
public Observable<DeviceGattCharacteristicEntity> addDeviceGattCharacteristic(final DeviceEntity device, final BluetoothGattCharacteristic characteristic) {
        DeviceGattCharacteristicEntity gatt = new DeviceGattCharacteristicEntity();
        gatt.setUuid(characteristic.getUuid());
        gatt.setProperties(characteristic.getProperties());
        gatt.setPermissions(characteristic.getPermissions());
        gatt.getDevices().add(device);
        dataStore.toBlocking().insert(gatt); // <-- this line throws NullPointerException
        return dataStore.refresh(gatt).toObservable();
    }
```

Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object io.requery.util.function.Supplier.get()' on a null object reference
    at io.requery.sql.Attributes.get(Attributes.java:38)
    at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:684)
    at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:621)
    at io.requery.sql.EntityWriter.insert(EntityWriter.java:448)
    at io.requery.sql.EntityWriter.insert(EntityWriter.java:406)
    at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:203)
    at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:189)
    at com.r_guardian.antiloss.data.local.DatabaseHelper.addDeviceGattCharacteristic(DatabaseHelper.java:108)
    at com.r_guardian.antiloss.data.DataManager.addDeviceGattCharacteristic(DataManager.java:128)
    at com.r_guardian.antiloss.beacon.BeaconManager$$Lambda$23.call(Unknown Source)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
    at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:283)
    at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:226)
    at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:375)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
    at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
    at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:154)
    at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
    at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
    at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.onNext(OperatorSwitchIfEmpty.java:90)
    at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:76)
    at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:76)
    at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
    at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117)
    at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
    at rx.internal.operators.OperatorTake$1$1.request(OperatorTake.java:109)
    at rx.internal.operators.OperatorTake$1$1.request(OperatorTake.java:109)
    at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
    at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.setProducer(OperatorSwitchIfEmpty.java:64)
    at rx.internal.operators.OperatorTake$1.setProducer(OperatorTake.java:93)
    at rx.internal.operators.OperatorTake$1.setProducer(OperatorTake.java:93)
    at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.setProducer(OnSubscribeFilter.java:104)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
    at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
    at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
    at rx.Observable.unsafeSubscribe(Observable.java:10140)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.unsafeSubscribe(Observable.java:10140)
    at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
    at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10140)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
    at rx.internal.operators.CachedObservable$ReplayProducer.replay(CachedObservable.java:403)
    at rx.internal.operators.CachedObservable$CacheState.dispatch(CachedObservable.java:220)
    at rx.internal.operators.CachedObservable$CacheState.onNext(CachedObservable.java:191)
    at rx.internal.operators.CachedObservable$CacheState$1.onNext(CachedObservable.java:171)
    at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
    at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
    at rx.subjects.ReplaySubject$ReplayUnboundedBuffer.drain(ReplaySubject.java:644)
    at rx.subjects.ReplaySubject$ReplayState.onNext(ReplaySubject.java:457)
    at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:242)
    at com.polidea.rxandroidble.internal.RxBleRadioOperation.onNext(RxBleRadioOperation.java:86)
    at com.polidea.rxandroidble.internal.RxBleRadioOperation$1.onNext(RxBleRadioOperation.java:75)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
    at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
    at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
    at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
    at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onNext(OperatorTimeoutBase.java:131)
    at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
    at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
    at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.setProducer(OperatorTimeoutBase.java:115)
    at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
    at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:80)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
    at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
    at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
    at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
    at com.polidea.rxandroidble.internal.connection.RxBleGattCallback$1$$Lambda$4.call(Unknown Source)
    at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

**Comment by jashhk** [comment]
Manually insertion (`DatabaseHelper.java`):
```
public Observable<DeviceGattCharacteristicEntity> addDeviceGattCharacteristic(final DeviceEntity device, final BluetoothGattCharacteristic characteristic) {
        DeviceGattCharacteristicEntity gatt = new DeviceGattCharacteristicEntity();
        gatt.setUuid(characteristic.getUuid());
        gatt.setProperties(characteristic.getProperties());
        gatt.setPermissions(characteristic.getPermissions());
        gatt = dataStore.toBlocking().insert(gatt);

        DeviceGattCharacteristicEntity_DeviceEntity relationship = new DeviceGattCharacteristicEntity_DeviceEntity();
        relationship.setDeviceGattCharacteristicId(gatt.getUuid());
        relationship.setDeviceId(device.getAddress());
        relationship = dataStore.toBlocking().insert(relationship); // Throw android.database.sqlite.SQLiteException

        gatt = dataStore.toBlocking().refresh(gatt);
        gatt.getDevices();
        return dataStore.insert(gatt).toObservable();
    }
```

Stack Trace:
```
 android.database.sqlite.SQLiteException: foreign key mismatch - "DeviceGattCharacteristic_Device" referencing "DeviceGattCharacteristic" (code 1): , while compiling: insert into DeviceGattCharacteristic_Device (DeviceId, DeviceGattCharacteristicId) values (?, ?)
     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
     at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:996)
     at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38)
     at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:127)
     at io.requery.sql.ConnectionDelegate.prepareStatement(ConnectionDelegate.java:225)
     at io.requery.sql.PreparedQueryOperation.prepare(PreparedQueryOperation.java:58)
     at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:51)
     at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
     at io.requery.query.BaseScalar.value(BaseScalar.java:49)
     at io.requery.sql.EntityWriter.insert(EntityWriter.java:446)
     at io.requery.sql.EntityWriter.insert(EntityWriter.java:406)
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:203)
     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:189)
     at com.r_guardian.antiloss.data.local.DatabaseHelper.addDeviceGattCharacteristic(DatabaseHelper.java:112)
     at com.r_guardian.antiloss.data.DataManager.addDeviceGattCharacteristic(DataManager.java:128)
     at com.r_guardian.antiloss.beacon.BeaconManager$$Lambda$23.call(Unknown Source)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
     at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:283)
     at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:226)
     at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:375)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
     at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:154)
     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
     at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
     at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
     at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.onNext(OperatorSwitchIfEmpty.java:90)
     at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:76)
     at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:76)
     at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117)
     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
     at rx.internal.operators.OperatorTake$1$1.request(OperatorTake.java:109)
     at rx.internal.operators.OperatorTake$1$1.request(OperatorTake.java:109)
     at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
     at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.setProducer(OperatorSwitchIfEmpty.java:64)
     at rx.internal.operators.OperatorTake$1.setProducer(OperatorTake.java:93)
     at rx.internal.operators.OperatorTake$1.setProducer(OperatorTake.java:93)
     at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.setProducer(OnSubscribeFilter.java:104)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
     at rx.Observable.unsafeSubscribe(Observable.java:10140)
     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
     at rx.Observable.unsafeSubscribe(Observable.java:10140)
     at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
     at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
     at rx.Observable.unsafeSubscribe(Observable.java:10140)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
     at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
     at rx.internal.operators.CachedObservable$ReplayProducer.replay(CachedObservable.java:403)
     at rx.internal.operators.CachedObservable$CacheState.dispatch(CachedObservable.java:220)
     at rx.internal.operators.CachedObservable$CacheState.onNext(CachedObservable.java:191)
     at rx.internal.operators.CachedObservable$CacheState$1.onNext(CachedObservable.java:171)
     at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
     at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
     at rx.subjects.ReplaySubject$ReplayUnboundedBuffer.drain(ReplaySubject.java:644)
     at rx.subjects.ReplaySubject$ReplayState.onNext(ReplaySubject.java:457)
     at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:242)
     at com.polidea.rxandroidble.internal.RxBleRadioOperation.onNext(RxBleRadioOperation.java:86)
     at com.polidea.rxandroidble.internal.RxBleRadioOperation$1.onNext(RxBleRadioOperation.java:75)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
     at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
     at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
     at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onNext(OperatorTimeoutBase.java:131)
     at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
     at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
     at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.setProducer(OperatorTimeoutBase.java:115)
     at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
     at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:80)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
     at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
     at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
     at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
     at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
     at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
     at com.polidea.rxandroidble.internal.connection.RxBleGattCallback$1$$Lambda$4.call(Unknown Source)
     at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:761)
```

**Comment by jashhk** [comment]
Table generation
```
I/requery: beforeExecuteUpdate sql: create table Device (address varchar(255) primary key unique, alert integer not null, batteryLevel integer not null, connected boolean not null, createTime integer not null, distance integer not null, icon varchar(255), itemInfo varchar(255), name varchar(255), nickname varchar(255), rssi integer not null, status integer not null)
I/requery: beforeExecuteUpdate sql: create table DeviceGattCharacteristic (uuid binary(16), properties integer not null, permissions integer not null, primary key (uuid, properties, permissions))
I/requery: beforeExecuteUpdate sql: create table DeviceGattCharacteristic_Device (DeviceId varchar(255), DeviceGattCharacteristicId binary(16), foreign key (DeviceId) references Device (address) on delete cascade on update cascade, foreign key (DeviceGattCharacteristicId) references DeviceGattCharacteristic (uuid) on delete cascade on update cascade, primary key (DeviceId, DeviceGattCharacteristicId))
```

**Comment by npurushe** [comment]
Are `properties` and `permissions` required to be keys in your `DeviceGattCharacteristic` entity? currently the many to many relation ship doesn't support using composite keys for this purpose yet.

**Comment by jashhk** [comment]
@npurushe Yes. 

But it is very difficult to notice that it is not supported by using the original implementation (without that blocking call). It only throws NullPointerException while there are multiple queries in a transaction.

**Comment by s3r6** [comment]
Similar exception on insert. No info about cause provided.
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object io.requery.util.function.Supplier.get()' on a null object reference
    at io.requery.sql.Attributes.get(Attributes.java:38)
    at io.requery.sql.EntityReader.associativeQuery(EntityReader.java:303)
    at io.requery.sql.EntityReader.refreshAssociation(EntityReader.java:258)
    at io.requery.sql.EntityReader.refresh(EntityReader.java:251)
    at io.requery.sql.EntityReader.refresh(EntityReader.java:182)
    at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:786)
    at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:666)
    at io.requery.sql.EntityWriter.update(EntityWriter.java:643)
    at io.requery.sql.EntityWriter.upsert(EntityWriter.java:518)
    at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:960)
    at io.requery.sql.EntityWriter.update(EntityWriter.java:613)
    at io.requery.sql.EntityWriter.upsert(EntityWriter.java:518)
    at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:960)
    at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:841)
    at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:697)
    at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:666)
    at io.requery.sql.EntityWriter.insert(EntityWriter.java:459)
    at io.requery.sql.EntityWriter.insert(EntityWriter.java:411)
    at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:206)
    at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:192)
    at io.requery.sql.KotlinEntityDataStore.insert(KotlinEntityDataStore.kt:119)
    at io.requery.reactivex.KotlinReactiveEntityStore$insert$1.call(KotlinReactiveEntityStore.kt:57)
    at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
    at io.reactivex.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onSuccess(SingleOnErrorReturn.java:82)
    at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.Single.subscribe(Single.java:3589)
```

**Comment by s3r6** [comment]
Solved above by adding missed IDs to entitiies using relation, e.g.
```
@get:Generated
@get:Key
val id: Int
```
