### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "rx.subjects.SerializedSubject"

### ISSUE THREAD

**Issue by simophin** [requery/requery#362]
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.subjects.SerializedSubject" on path: DexPathList
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at io.requery.rx.TypeChangeListener.<init>(TypeChangeListener.java:41) 
                                                                           at io.requery.rx.RxSupport.<clinit>(RxSupport.java:43) 
                                                                           at io.requery.reactivex.ReactiveSupport$2.test(ReactiveSupport.java:63) 
                                                                           at io.requery.reactivex.ReactiveSupport$2.test(ReactiveSupport.java:59) 
                                                                           at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:45) 
                                                                           at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:263) 
                                                                           at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:182) 
                                                                           at io.reactivex.subjects.SerializedSubject.onNext(SerializedSubject.java:104) 
                                                                           at io.requery.reactivex.TransactionListenerSupplier$1.afterCommit(TransactionListenerSupplier.java:61) 
                                                                           at io.requery.sql.CompositeTransactionListener.afterCommit(CompositeTransactionListener.java:63) 
                                                                           at io.requery.sql.ConnectionTransaction.commit(ConnectionTransaction.java:144) 
                                                                           at io.requery.sql.ThreadLocalTransaction.commit(ThreadLocalTransaction.java:76) 
                                                                           at io.requery.reactivex.WrappedEntityStore$18.call(WrappedEntityStore.java:318) 
                                                                           at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:35) 
                                                                           at io.reactivex.Completable.subscribe(Completable.java:1592) 
                                                                           at io.reactivex.internal.operators.completable.CompletableToObservable.subscribeActual(CompletableToObservable.java:29) 
                                                                           at io.reactivex.Observable.subscribe(Observable.java:10514) 
                                                                           at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:467) 
                                                                           at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:325) 
                                                                           at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:29) 
                                                                           at io.reactivex.Observable.subscribe(Observable.java:10514) 
                                                                           at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:54) 
                                                                           at io.reactivex.Observable.subscribe(Observable.java:10514) 
                                                                           at io.reactivex.internal.operators.completable.CompletableFromObservable.subscribeActual(CompletableFromObservable.java:29) 
                                                                           at io.reactivex.Completable.subscribe(Completable.java:1592) 
                                                                           at io.reactivex.internal.operators.completable.CompletableObserveOn.subscribeActual(CompletableObserveOn.java:34) 
                                                                           at io.reactivex.Completable.subscribe(Completable.java:1592) 
                                                                           at io.reactivex.Completable.subscribe(Completable.java:
```

This is an incomplete stacktrace but I think it's sufficient enough. This happens while some data changes.

Basically our project has switched to RxJava2 only, therefore there's no RxJava1 at runtime. 

The RxJava2 version of RxSupport, namely `ReactiveSupport`, tries to access `RxSupport.referencesType()` in `toObservableResult`, which causes the `RxSupport` class to be initialised, which in turn creates a new `io.requery.rx.TypeChangeListener`instance. The TypeChangeListener will then create instances of RxJava1's SerializedSubject, which doesn't exist in this project.

**Comment by npurushe** [comment]
Thanks for the detailed bug report, fix will be in the next release thanks
