### ISSUE TITLE
Cannot bind argument at index 3 because the index is out of range.  The statement has 2 parameters.

### ISSUE THREAD

**Issue by jashhk** [requery/requery#365]
Hi,

I am trying to update a record to the database with RxJava in Android, and having trouble updating one field. It often throws java.lang.IllegalArgumentException and gives me the **same** message. There are always some updates on same instance between multiple threads (2 types of threads only which is Schedulers.io and Schedulers.computation).

Potential buggy query:
```
I/requery: beforeExecuteUpdate sql: update Device set status = ? where address = ?
I/requery: afterExecuteUpdate
```

The function call:
`dataStore.update(device).toObservable();`

```
@Entity
public interface Device extends Observable, Parcelable, Persistable {

    @Key
    @Index(value = "address_index")
    @Column(unique = true)
    @Bindable
    String getAddress();

    @Bindable
    int getRssi();

    @Bindable
    String getName();

    @Bindable
    String getNickname();

    @Bindable
    String getItemInfo();

    String getIcon();

    @Bindable
    int getDistance();

    @Bindable
    int getAlert();

    @Column(value = "CURRENT_TIMESTAMP")
    long getCreateTime();

    @Bindable
    boolean getConnected();

    @Bindable
    int getStatus();

    @Bindable
    int getBatteryLevel();
}
```

Full trace:
```
java.lang.IllegalArgumentException: Cannot bind argument at index 3 because the index is out of range.  The statement has 2 parameters.
                     at android.database.sqlite.SQLiteProgram.bind(SQLiteProgram.java:212)
                     at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:166)
                     at io.requery.android.sqlite.SqlitePreparedStatement.bindNullOrString(SqlitePreparedStatement.java:50)
                     at io.requery.android.sqlite.BasePreparedStatement.setString(BasePreparedStatement.java:356)
                     at io.requery.android.sqlite.BasePreparedStatement.setObject(BasePreparedStatement.java:310)
                     at io.requery.sql.BaseType.write(BaseType.java:63)
                     at io.requery.sql.GenericMapping.write(GenericMapping.java:351)
                     at io.requery.sql.EntityWriter$9.bindParameters(EntityWriter.java:554)
                     at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:52)
                     at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
                     at io.requery.query.BaseScalar.value(BaseScalar.java:49)
                     at io.requery.sql.EntityWriter.update(EntityWriter.java:592)
                     at io.requery.sql.EntityWriter.update(EntityWriter.java:513)
                     at io.requery.sql.EntityDataStore.update(EntityDataStore.java:242)
                     at io.requery.rx.SingleEntityStoreFromBlocking$5.call(SingleEntityStoreFromBlocking.java:123)
                     at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:41)
                     at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:29)
                     at rx.Single.subscribe(Single.java:1835)
                     at rx.Single$13$1.call(Single.java:1907)
                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                     at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                     at java.lang.Thread.run(Thread.java:761)
```

**Comment by npurushe** [comment]
What values did you modify before calling update in this case? thanks

**Comment by jashhk** [comment]
`device.setConnected(true);`
`device.setStatus(0)`

Two separated function calls in two threads in most all the time

**Comment by npurushe** [comment]
This is happening because you have two threads changing the object state during the update. As a work around for now simply synchronizing this will prevent the exception

**Comment by noberasco** [comment]
I'm affected by this issue, too.
I'll try the suggested workaround (after the holidays break) and see whether it helps.
