### ISSUE TITLE
Error with Upsert on entity with Composite Key

### ISSUE THREAD

**Issue by guptakeshav** [requery/requery#366]
Hi,
I had created an entity with a composite key and I was using "upsert" to insert or update the data. But I received the exception "android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed", as instead of updating, it tried to insert the data when the data having the same key was found.
<img width="838" alt="screen shot 2016-12-15 at 9 26 07 pm" src="https://cloud.githubusercontent.com/assets/8845010/21231609/e2fdb334-c30e-11e6-985a-a9bc0d2d9ed2.png">

PS: Using sqlite on Android.

**Comment by npurushe** [comment]
Hi can you please post the stacktrace from printStackTrace(). Also if you possible would you be able to share your entity definition. Thanks

**Comment by guptakeshav** [comment]
Something like this:

```
@Table(name = "Users")
@Entity
interface IUsers : Persistable {
    @get:ManyToOne
    @get:Key
    var group: IGroups

    @get:ManyToOne
    @get:Key
    var profile: IProfiles

    var status: String
}
```

And here is the stackTrace:
```
at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:59)
at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
at io.requery.query.BaseScalar.value(BaseScalar.java:49)
at io.requery.sql.EntityWriter.insert(EntityWriter.java:446)
at io.requery.sql.EntityWriter.upsert(EntityWriter.java:490)
at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:280)
at io.requery.sql.KotlinEntityDataStore.upsert(KotlinEntityDataStore.kt:123)
at com.abc.db_stores.UserStore.insertOrUpdateUser(RoomStore.kt:75)
at com.abc.app.ui.activities.MainActivity.insertIntoDB(MainActivity.java:151)
at com.abc.app.ui.activities.MainActivity.lambda$getAllUsers$3(MainActivity.java:139)
at com.abc.app.ui.activities.MainActivity$$Lambda$4.call(Unknown Source)
at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5317)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Users.group, Users.profile (code 1555)
at io.requery.android.sqlite.BaseConnection.throwSQLException(BaseConnection.java:69)
at io.requery.android.sqlite.SqlitePreparedStatement.executeUpdate(SqlitePreparedStatement.java:170)
at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:54)
... 22 more
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Users.group, Users.profile (code 1555)
at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:740)
at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
at io.requery.android.sqlite.SqlitePreparedStatement.executeUpdate(SqlitePreparedStatement.java:168)
... 23 more
```

**Comment by guptakeshav** [comment]
Any updates on this?

**Comment by consp1racy** [comment]
https://twitter.com/slicknet/status/782274190451671040

**Comment by npurushe** [comment]
Still looking into why your update with return 0 rows affected and cause an insert. If you can enable logs and post the statements executed that would be helpful thanks.

**Comment by guptakeshav** [comment]
```
beforeExecuteUpdate sql: update B set id = ? ,x = ? ,y = ? where id = ? 
afterExecuteUpdate
beforeExecuteUpdate sql: update Groups set id = ? ,a = ? ,Bid = ? where id = ? 
afterExecuteUpdate
beforeExecuteUpdate sql: update Profiles set id = ? ,email = ? ,firstName = ? ,lastName = ? ,phoneNumber = ? where id = ? 
afterExecuteUpdate
beforeExecuteUpdate sql: update Users set groupId = ? ,profileId = ? ,status = ? where groupId = ? and profileId = ? 
afterExecuteUpdate
beforeExecuteUpdate sql: insert into Users (groupId, profileId, status) values (?, ?, ?)
E/SQLiteLog: (1555) abort at 13 in [insert into Users (groupId, profileId, status) values (?, ?, ?)]: UNIQUE constraint failed: Users.groupId, Users.profileId
Exception executing statement: insert into Users (groupId, profileId, status) values (?, ?, ?)
```

I have changed some variables names, but I think everything is still making sense :)

PS: "Groups" has a ManyToOne relation with "B".

**Comment by guptakeshav** [comment]
I tried removing the composite key from User entity, and added an auto-generated Integer key.
Now, I still have 3 entities: Groups, Users, Profiles.
Groups having OneToMany relationship with Users. Users having ManyToOne relationship with Profiles.

According to logs, when I call upsert on Groups, it first tries to update Group, if it fails, then it tries to insert Group. After that, it directly tries to insert into Profiles, for which it gets Unique constraint failed on Profiles, because it is not trying to update Profiles, and directly inserting into it. Why is it happening? :/

**Comment by guptakeshav** [comment]
@npurushe Has it been possible for you to investigate this?
Been stuck on it for quite sometime now.

**Comment by npurushe** [comment]
The change set should fix your issue, but there will probably be some additional verification before releasing it, an update should be relatively soon though. Thanks!

**Comment by guptakeshav** [comment]
```
Caused by: java.lang.StackOverflowError: stack size 1036KB
                                                                                                  	at android.database.sqlite.SQLiteConnectionPool.finishAcquireConnectionLocked(SQLiteConnectionPool.java:911) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteConnectionPool.tryAcquirePrimaryConnectionLocked(SQLiteConnectionPool.java:847) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:613) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:586) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31) ~[na:0.0]
                                                                                                  	at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994) ~[na:0.0]
                                                                                                  	at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38) ~[na:0.0]
                                                                                                  	at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:127) ~[na:0.0]
                                                                                                  	at io.requery.android.sqlite.BaseConnection.prepareStatement(BaseConnection.java:160) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:220) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(EntityProxy.java:70) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.getKey(EntityProxy.java:262) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:223) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(EntityProxy.java:70) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.getKey(EntityProxy.java:262) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:223) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(EntityProxy.java:70) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.getKey(EntityProxy.java:262) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:223) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
                                                                                                  	at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
                                                                                                  	at io.requery.proxy.EntityProxy.get(Ent
I/art: Background sticky concurrent mark sweep GC freed 34065(2MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 37MB/37MB, paused 14.396ms total 37.719ms
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/data/com.abc.example/databases/default' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
```
