### ISSUE TITLE
java.lang.UnsupportedOperationException upserting immutable entities

### ISSUE THREAD

**Issue by simophin** [requery/requery#367]
When upserting an immutable instance with generated key, I get this error: 

```
java.lang.UnsupportedOperationException
                                                                             at com.example.testrequery.DogType$2.setLong(DogType.java:40)
                                                                             at com.example.testrequery.DogType$2.setLong(DogType.java:22)
                                                                             at io.requery.proxy.EntityProxy.setLong(EntityProxy.java:167)
                                                                             at io.requery.sql.EntityWriter.readKeyFromResult(EntityWriter.java:323)
                                                                             at io.requery.sql.EntityWriter.readGeneratedKeys(EntityWriter.java:295)
                                                                             at io.requery.sql.EntityWriter.access$200(EntityWriter.java:69)
                                                                             at io.requery.sql.EntityWriter$4.read(EntityWriter.java:418)
                                                                             at io.requery.sql.PreparedQueryOperation.readGeneratedKeys(PreparedQueryOperation.java:95)
                                                                             at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:56)
                                                                             at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
                                                                             at io.requery.query.BaseScalar.value(BaseScalar.java:49)
                                                                             at io.requery.sql.EntityWriter.insert(EntityWriter.java:446)
                                                                             at io.requery.sql.EntityWriter.upsert(EntityWriter.java:463)
                                                                             at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:280)
                                                                             at io.requery.reactivex.WrappedEntityStore$8.call(WrappedEntityStore.java:135)
                                                                             at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
                                                                             at io.reactivex.Single.subscribe(Single.java:2656)
                                                                             at io.reactivex.Single.subscribe(Single.java:2642)
                                                                             at io.reactivex.Single.subscribe(Single.java:2567)
                                                                             at com.example.testrequery.MainActivity.onCreate(MainActivity.java:21)
                                                                             at android.app.Activity.performCreate(Activity.java:6679)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

This is the model I use: 

```java
@AutoValue
@Entity
public abstract class Dog implements Persistable {
    @Key @Generated
    public abstract long id();
    public abstract String name();
    public abstract int age();

    public static Builder builder() {
        return new AutoValue_Dog.Builder().id(-1);
    }

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder id(long id);

        public abstract Builder name(String name);

        public abstract Builder age(int age);

        public abstract Dog build();
    }
}

```

Look like we should use `EntityBuilderProxy` instead of `EntityProxy` in the generated `DogType.$TYPE`? Below is the generated `$TYPE`:

```java
   public static final Type<Dog> $TYPE = new TypeBuilder<Dog>(Dog.class, "Dog")
    .setBaseType(Dog.class)
    .setCacheable(true)
    .setImmutable(true)
    .setReadOnly(false)
    .setStateless(true)
    .setBuilderFactory(new Supplier<DogType>() {
        @Override
        public DogType get() {
            return new DogType();
        }
    })
    .setBuilderFunction(new Function<DogType, Dog>() {
        @Override
        public Dog apply(DogType value) {
            return value.builder.build();
        }
    })
    .setProxyProvider(new Function<Dog, EntityProxy<Dog>>() {
        @Override
        public EntityProxy<Dog> apply(Dog entity) {
            return new EntityProxy<Dog>(entity, $TYPE);
        }
    })
    .addAttribute(ID)
    .addAttribute(NAME)
    .addAttribute(AGE)
    .build();
```

**Comment by npurushe** [comment]
If you have an entity with a generated key that is not known the only thing you can do is insert it. In the case of an immutable type the key can only be returned to you for an insert, for which there is a special overload which is like `<Key> key = insert(<Type>, <KeyClass>)`.

this particular case should have the following pattern:

```java
if (haveKey) {
    store.update(entity);
} else {
    Integer key = store.insert(entity, Integer.class);
}
```

Hope that helps. Your example should work if your entity is changed to not have a generated key.
