### ISSUE TITLE
ClassCastException when fetching with collection stored with convertion by by custom converter

### ISSUE THREAD

**Issue by sakuna63** [requery/requery#373]
## Problem

I have a converter like [it](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/model/IntegerListConverter.java) and an entity definition like a below

```
@Entity
abstract class AbstractEntity {
    //...

    @Converter(IntergerListConverter.class)
    List<Integer> ints;

    //...
}
```

I query like a below

```
List<Integer> ints = new ArrayList<>();
ints.add(1);
ints.add(2);
Result<Entity> reuslt = entityStore.select(Entity.class).where(ENTITY.INTS.eq(ints)).get();
```

ClassCastException occurs

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.List<Integer>;
  at com.example.IntegerListConverter.convertToPersisted(IntegerListConverter.java:18)
  at io.requery.sql.GenericMapping.write(GenericMapping.java:349)
  at io.requery.sql.SelectResult.iterator(SelectResult.java:135)
  at io.requery.query.BaseResult.iterator(BaseResult.java:124)
  at io.requery.query.BaseResult.first(BaseResult.java:88)
  at io.requery.sql.SelectCountOperation$1.evaluate(SelectCountOperation.java:42)
  at io.requery.sql.SelectCountOperation$1.evaluate(SelectCountOperation.java:38)
  at io.requery.query.BaseScalar.value(BaseScalar.java:49)
```

## Cause

I located the source of this problem. https://github.com/requery/requery/blob/feb0bb6b1470086feaebccd83f6addb7606bd6df/requery/src/main/java/io/requery/sql/gen/DefaultOutput.java#L318p

But I don't have any idea to solve it. Can I fix it?

**Comment by npurushe** [comment]
Thanks for reporting this fix is available in 1.1.1
