### ISSUE TITLE
Stackoverflow error after latest commit

### ISSUE THREAD

**Issue by guptakeshav** [requery/requery#393]
After the latest commit that solved issue #366, I am getting stackoverflow error, at the same place when I was getting the UNIQUE constraint failed error. I had posted the stack trace on that issue only, but that issue has been closed, so posting this in a different issue.

```
Caused by: java.lang.StackOverflowError: stack size 1036KB

at android.database.sqlite.SQLiteConnectionPool.finishAcquireConnectionLocked(SQLiteConnectionPool.java:911) ~[na:0.0]
at android.database.sqlite.SQLiteConnectionPool.tryAcquirePrimaryConnectionLocked(SQLiteConnectionPool.java:847) ~[na:0.0]
at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:613) ~[na:0.0]
at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348) ~[na:0.0]
at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894) ~[na:0.0]
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:586) ~[na:0.0]
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58) ~[na:0.0]
at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31) ~[na:0.0]
at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994) ~[na:0.0]
at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38) ~[na:0.0]
at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:127) ~[na:0.0]
at io.requery.android.sqlite.BaseConnection.prepareStatement(BaseConnection.java:160) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:220) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(EntityProxy.java:70) ~[na:0.0]
at io.requery.proxy.EntityProxy.getKey(EntityProxy.java:262) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:223) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(EntityProxy.java:70) ~[na:0.0]
at io.requery.proxy.EntityProxy.getKey(EntityProxy.java:262) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:223) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(EntityProxy.java:70) ~[na:0.0]
at io.requery.proxy.EntityProxy.getKey(EntityProxy.java:262) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:223) ~[na:0.0]
at io.requery.sql.EntityReader.refresh(EntityReader.java:182) ~[na:0.0]
at io.requery.sql.EntityReader.load(EntityReader.java:152) ~[na:0.0]
at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(EntityProxy.java:75) ~[na:0.0]
at io.requery.proxy.EntityProxy.get(Ent
I/art: Background sticky concurrent mark sweep GC freed 34065(2MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 37MB/37MB, paused 14.396ms total 37.719ms
W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/data/com.abc.example/databases/default' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
```

**Comment by npurushe** [comment]
It's ok to post in the original issue the comments will be checked and the issue reopened if needed thanks
