### ISSUE TITLE
OptimisticLockException when updating an entity with a @Version column

### ISSUE THREAD

**Issue by MikeNicholls** [requery/requery#399]
```java
@Test
public void testVersionColumn() {
    Group group = new Group();

    group.setName("One");
    data.insert(group);

    group.setName("Two");
    data.update(group);

    group.setName("Three");
    data.update(group);
}
```
Appears to have regressed between requery 1.1.0 and 1.1.1.  An exception is thrown on the last line when running with 1.1.1:
```
io.requery.sql.OptimisticLockException: Couldn't update (Groups [1, null, null, io.requery.query.ModifiableResult@3e27aa33, Three, io.requery.query.ModifiableResult@2e385cce, null, null, 3]) with version 3 entity may have been modified or deleted

	at io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:170)
	at io.requery.sql.EntityWriter.update(EntityWriter.java:508)
	at io.requery.sql.EntityDataStore.update(EntityDataStore.java:242)
```

**Comment by npurushe** [comment]
Thanks for reporting, the fix will be in the next update soon.
