### ISSUE TITLE
Getting rid of misleading exceptions with new jackson module

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#444]
Hi,

upon parsing the following string to the following model, I get this (abbreviated) exception. The parsing and inserting works without problems, thus the exception is a bit misleading. Can we get rid of this exception and only throw it if all (super)classes have been walked through and no id was found?

```Java
java.lang.NoSuchFieldException: No field id in class Lcom/example/example/data/models/AbstractPersonModel
     at java.lang.Class.getDeclaredField(Native Method)
     at io.requery.jackson.EntityAnnotationIntrospector.findObjectIdInfo(EntityAnnotationIntrospector.java:84)
     at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findObjectIdInfo(AnnotationIntrospectorPair.java:412)
     at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getObjectIdInfo(POJOPropertiesCollector.java:248)
     at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.<init>(BasicBeanDescription.java:111)
     at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.forDeserialization(BasicBeanDescription.java:119)
     at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(BasicClassIntrospector.java:111)
     at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(BasicClassIntrospector.java:16)
     at com.fasterxml.jackson.databind.DeserializationConfig.introspect(DeserializationConfig.java:900)
```

Models:

```Java
@Superclass
public abstract class AbstractBaseModel {
  @Key
  Integer id;
}
```

```Java
@Entity
public abstract class AbstractPersonModel extends AbstractBaseModel {
  String username;

  @ManyToMany
  //SomeModel can just be any requery class
  List<SomeModel> pokemonModels;
}
```

Code to parse & insert (value taken from [REST dummy API](https://jsonplaceholder.typicode.com/users)):
```Java
  EntityMapper entityMapper = new EntityMapper(Models.DEFAULT, database);
      entityMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
  String user = "{\n" +
      "\n" +
      "    \"id\": 1,\n" +
      "    \"name\": \"Leanne Graham\",\n" +
      "    \"username\": \"Bret\",\n" +
      "    \"email\": \"Sincere@april.biz\",\n" +
      "    \"address\": {\n" +
      "        \"street\": \"Kulas Light\",\n" +
      "        \"suite\": \"Apt. 556\",\n" +
      "        \"city\": \"Gwenborough\",\n" +
      "        \"zipcode\": \"92998-3874\",\n" +
      "        \"geo\": {\n" +
      "            \"lat\": \"-37.3159\",\n" +
      "            \"lng\": \"81.1496\"\n" +
      "        }\n" +
      "    },\n" +
      "    \"phone\": \"1-770-736-8031 x56442\",\n" +
      "    \"website\": \"hildegard.org\",\n" +
      "    \"company\": {\n" +
      "        \"name\": \"Romaguera-Crona\",\n" +
      "        \"catchPhrase\": \"Multi-layered client-server neural-net\",\n" +
      "        \"bs\": \"harness real-time e-markets\"\n" +
      "    }\n" +
      "\n" +
      "}";
      try {
    PersonModel personModel = entityMapper.readValue(user, PersonModel.class);
    database.insert(personModel);
  } catch (IOException e) {
    e.printStackTrace();
  }
```

**Comment by npurushe** [comment]
This is not a re-thrown exception from your stacktrace, it is caught and printed only.

**Comment by Agraphie** [comment]
Hi,

yes I know. Sorry for making it sounds like. Thanks for changing this.
