### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by miomao656** [requery/requery#46]
Do you plan to support raw sql?

I want to select rows from - to, limit method only receives one value.

**Comment by npurushe** [comment]
Hi do you have an example of the sql query you want to make? You can use `limit(n).offset(m)` or use a where clause and a limit depending on the case.

**Comment by miomao656** [comment]
SELECT * FROM `table` LIMIT [row to start on], [how many to include] 

yes i think your answer resolves my question :+1:

**Comment by npurushe** [comment]
Great!

**Comment by miomao656** [comment]
Hi 

When inserting or updating db and after that using this

```
.select(DocumentEntity.class)
                .orderBy(DocumentEntity.UPLOAD_DATE.desc())
                .limit(rows)
                .offset(offset)
                .get()
                .toObservable()
```

in combination with strict mode 

```
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectAll()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
```

i  get this exception after two or three cycles (insert or update then select)

```
E/StrictMode: Finalizing a Cursor that has not been deactivated or closed. database = /data/data/de.center.android/databases/center2cdd37022959, table = null, query = select id, commentsCount, documentId, downloaded, fileName, mimeType, numPages, representationFullText, representationJpg, representationMp4, representationPdf, representationPng, score, size, title, uploadDate, version, versionDate from CDDocument order by uploadDate desc limit 50 offset 50
                                             android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                 at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:101)
                                                 at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
                                                 at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1440)
                                                 at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1379)
                                                 at io.requery.android.sqlite.SqliteStatement.executeQuery(SqliteStatement.java:68)
                                                 at io.requery.sql.SelectResult.iterator(SelectResult.java:114)
                                                 at io.requery.query.BaseResult.iterator(BaseResult.java:107)
                                                 at io.requery.rx.RxSupport.toObservable(RxSupport.java:93)
                                                 at io.requery.query.BaseResult.toObservable(BaseResult.java:128)
.
.
.

W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.

```

**Comment by npurushe** [comment]
Thanks I think see the issue there, will work on a fix today

**Comment by npurushe** [comment]
What version of android did you encounter that on?

**Comment by miomao656** [comment]
On 4.x and 5.x
