### ISSUE TITLE
Kotlin data class insert problem

### ISSUE THREAD

**Issue by mdzigurski** [requery/requery#466]
I have a problem while trying to do an insert on a kotlin data class. Here is my data class:
```
@Table(name = "users")
@Entity(model = "ktdata")
data class User constructor(
    @get:Key  @get:Generated  @get:Column(name="id", nullable=false)
    var id: Int?,

    @get:Column(name="person_id", nullable=false)
    var personId: Int,

    @get:Column(name="status", nullable=false)
    var status: Int,

    @get:Column(name="created_at", nullable=false)
    var createdAt: java.time.ZonedDateTime
)
```

Here is the insert:
```
    val user = User(null, 4, 1, ZonedDateTime.now())
    data.insert(user)
```

Here is the exception:
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at model.UserType$2.setInt(UserType.java:40)
	at model.UserType$2.setInt(UserType.java:22)
	at io.requery.proxy.EntityProxy.setInt(EntityProxy.java:159)
	at io.requery.sql.EntityWriter.readKeyFromResult(EntityWriter.java:321)
	at io.requery.sql.EntityWriter.readGeneratedKeys(EntityWriter.java:297)
	at io.requery.sql.EntityWriter.access$200(EntityWriter.java:69)
	at io.requery.sql.EntityWriter$4.read(EntityWriter.java:413)
	at io.requery.sql.PreparedQueryOperation.readGeneratedKeys(PreparedQueryOperation.java:95)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:56)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
	at io.requery.query.BaseScalar.value(BaseScalar.java:48)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:441)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:401)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:204)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190)
	at io.requery.sql.KotlinEntityDataStore.insert(KotlinEntityDataStore.kt:118)
	at RequeryKt.main(Requery.kt:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Basically, it is throwing an exception when it tried to set ID of the inserted record back to the data class. I think the problem is related to not properly defined setter method of the generated column. I managed to make the insert work fine by replacing `@get:Key` with `@Key`, and `@get:Generated` with `@Generated`, but in that case data.update(user) would not work properly. 

This below is what was generated in UserType 

![image](https://cloud.githubusercontent.com/assets/1377099/23835113/c07dd344-071e-11e7-95ea-cee66d2320c1.png)

Any idea what am I doing wrong? Thanks!

**Comment by npurushe** [comment]
Hi Kotlin data classes are immutable so the generated id cannot be applied back to the object, hence the exception. There are a couple of options of how to handle this:

1) use the ```fun <K : Any, E : T> insert(entity: E, keyClass: KClass<K>): R``` overload which returns the generated id back to caller, which you can then use separately from the object.
2) change the entity from a data class to an interface or abstract class that is mutable
3) remove the generated key and instead used fixed key types

hope that helps

**Comment by ninjudd** [comment]
@npurushe would it be possible to change the behavior to return a copy of the object with the generated `id` field set so that data classes are still supported?

**Comment by k-misztal** [comment]
@ninjudd +1

**Comment by thiagoicarros** [comment]
I create a class only to do it:

```
open class GeneratedId: Persistable {
    @set:Generated
    @set:Key
    var id: Long = 0
        set(value){field = value}
        get() = field
}
```

Now, when i have a table that needs a genereted id i extends GeneretedId, even using data class

```
@Entity
@Table(name = "DealEquipment")
@JsonIgnoreProperties(ignoreUnknown = true)
data class DealEquipment(var dealId: Long = 0L,
                         var equipmentId: Long = 0L) : GeneratedId()
```

Works for me =)

**Comment by k-misztal** [comment]
I'll check it out, thanks!

**Comment by ninjudd** [comment]
But the `id` field will be mutable on this class, right? It would be better to do this without having to give up immutability.

**Comment by cfnz** [comment]
@thiagoicarros Is this still working for you?

When I do this I do not get an id field generated in the table, and if I manually create the field, I don't get to read the Id back.

Just wondering if it is still working with data classes.
