### ISSUE TITLE
io.requery.sql.CircularReferenceException: circular reference detected 

### ISSUE THREAD

**Issue by josecoll** [requery/requery#472]
This error is thrown at run-time when modelling an Entity with **more than one relationship to the same foreign table.**

The entities are modelled in code as follows:

```
    @Table(name = "vault_linear_states")
    @Entity(model = "vault")
    interface VaultLinearState : Persistable {

        // Single Primary Key
        @get:Key
        @get:Generated
        @get:Column(name = "id")
        var id: Int

        // Owner of this State
        @get:ForeignKey
        @get:OneToOne
        var owner: VaultParty

        /**
         * [DealState] attributes
         */

        @get:Index("deal_reference_index")
        @get:Column(name = "deal_reference")
        var dealRef: String

        // Participants to this deal state
        @get:OneToMany(mappedBy = "linear_state_parties")
        var dealParties: Set<VaultParty>

    }

    @Table(name = "vault_party")
    @Entity(model = "vault")
    interface VaultParty : Persistable  {

        @get:Key
        @get:Generated
        @get:Column(name = "id")
        var id: Int

        // NOTE: remove this back reference when Requery supports Unidirectional relationships
        @get:ManyToOne
        @get:Column(name = "linear_state_parties")
        val linearStateParties: VaultLinearState

        /**
         * [Party] attributes
         */
        @get:Column(name = "party_name")
        var name: String

        @get:Column(name = "party_key")
        var key: String

        // NOTE: remove this back reference when Requery supports Unidirectional relationships
        @get:OneToOne
        val owner: VaultLinearState
    }
```

Note errors are flagged at code generation time as *warnings* only,
The following *warnings* are displayed upon running the Kapt code generator:

```
warning: 2 mappings found for: net.corda.node.services.vault.schemas.VaultLinearStateEntity.owner -> net.corda.node.services.vault.schemas.VaultPartyEntity
warning: Circular Foreign Key reference found between net.corda.node.services.vault.schemas.VaultLinearStateEntity and net.corda.node.services.vault.schemas.VaultLinearStateEntity
warning: 2 mappings found for: net.corda.node.services.vault.schemas.VaultPartyEntity.linear_state_parties -> net.corda.node.services.vault.schemas.VaultLinearStateEntity
warning: Circular Foreign Key reference found between net.corda.node.services.vault.schemas.VaultPartyEntity and net.corda.node.services.vault.schemas.VaultPartyEntity 
```

The complete stack trace at run-time is:

```
io.requery.sql.CircularReferenceException: circular reference detected between vault_party and vault_linear_states

	at io.requery.sql.SchemaModifier.sortTypes(SchemaModifier.java:285)
	at io.requery.sql.SchemaModifier.createTables(SchemaModifier.java:123)
	at net.corda.node.services.vault.schemas.VaultSchemaTest.setup(VaultSchemaTest.kt:34)
```

**Comment by npurushe** [comment]
Hi the issue here is VaultLinearState has a foreign key reference to VaultParty, and VaultParty also has foreign key reference to VaultLinearState through `@ManyToOne`. It's generally not possible to create the tables using a single create table statement with a foreign key reference column, since they depend on each other. 

The table would have to be created without the foreign key column and then foreign key added afterwards which is currently not supported. While it is possible from what i've seen it is generally discouraged, and support for it varies between different databases.

The easiest solution is to reverse the dependency and have the `VaultParty` contain the foreign key to `VaultLinearState`
