### ISSUE TITLE
Cannot use @Generated for anything aside @Keys columns

### ISSUE THREAD

**Issue by low205** [requery/requery#484]
When entity has generated column(virtual column in oracle for examle), you cannot use it in INSERT, but you can't mark coluwn with `@Generated`. 

There is this code in InsertGenerator:
```
                       Expression<?> key = value.getKey();
                        switch (key.getExpressionType()) {
                            case ATTRIBUTE:
                                Attribute attribute = (Attribute) key;
                                if (attribute.isGenerated()) {
                                    throw new IllegalStateException();
                                }
                                qb.attribute(attribute);
                                break;
                            default:
                                qb.append(key.getName()).space();
                                break;
                        }
```

which throws this:
```
java.lang.IllegalStateException
	at io.requery.sql.gen.InsertGenerator$1.append(InsertGenerator.java:57)
	at io.requery.sql.gen.InsertGenerator$1.append(InsertGenerator.java:49)
	at io.requery.sql.QueryBuilder.commaSeparated(QueryBuilder.java:248)
	at io.requery.sql.QueryBuilder.commaSeparated(QueryBuilder.java:235)
	at io.requery.sql.gen.InsertGenerator.write(InsertGenerator.java:48)
	at io.requery.sql.gen.InsertGenerator.write(InsertGenerator.java:32)
	at io.requery.sql.gen.StatementGenerator.write(StatementGenerator.java:69)
	at io.requery.sql.gen.DefaultOutput.toSql(DefaultOutput.java:97)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:47)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
	at io.requery.query.BaseScalar.value(BaseScalar.java:48)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:441)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:401)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:204)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190)
```

**Comment by npurushe** [comment]
For that particular case (virtual column) you shouldn't mark the column as `@Generated`. In this context generated means a column returned as part of an insert/update. virtual columns are queryable as any other.

**Comment by low205** [comment]
I mean entity has virutal column, which can be queribale but not updatable/insertable, how can we exclude them from insert query generated by `datastore.insert(entity);` and in the same time make them return from insert or update, because they are regenerated at that time.

**Comment by npurushe** [comment]
Right ok I see the problem will reopen and look at good solution for this thanks

**Comment by npurushe** [comment]
The solution for this will be to mark the column with `@ReadOnly` which is effectively equivalent to setting `@Column(insertable = false, updateable = false)` in JPA. Previously these were included in an insert/update but will now be excluded with the change.
