### ISSUE TITLE
OneToOne relationship, casting crashes when a JSONArray field exists

### ISSUE THREAD

**Issue by 2x2xplz** [requery/requery#492]
Using requery 1.2.1 with Kotlin for Android development. (so requery, requery-kotlin, requery-android are all active, with kapt running requery-processor). I am using the basic (non Rx) data store type.

I have objects with a 1-to-1 relationship like the person/address classes in the sample. However in my case the "person" class has additional fields of type JSONArray and JSONObject. When I try to access the person class from the address class (i.e. address.person.name), it crashes with a ClassCast exception. The stacktrace takes me to GenericMapping, line 302.

I have ManyToOne relationships and these work OK, I can access the parent object from the child, no errors or casting issues. So perhaps something is different with OneToOne? (and yes, I have tried switching sides, assigning the parent to the child, reversing the mapping annotation, etc.)

```
03-28 22:41:08.761 21030-21030/com.allthecomps.apps.users.atc.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.allthecomps.apps.users.atc.android, PID: 21030
                                                                                        java.lang.ClassCastException: java.lang.String cannot be cast to org.json.JSONArray
                                                                                            at java.lang.Class.cast(Class.java:1731)
                                                                                            at io.requery.sql.GenericMapping.read(GenericMapping.java:302)
                                                                                            at io.requery.sql.EntityReader.fromResult(EntityReader.java:567)
                                                                                            at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
                                                                                            at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
                                                                                            at io.requery.query.BaseResult.firstOr(BaseResult.java:94)
                                                                                            at io.requery.query.BaseResult.firstOrNull(BaseResult.java:112)
                                                                                            at io.requery.sql.EntityReader.refreshAssociation(EntityReader.java:262)
                                                                                            at io.requery.sql.EntityReader.refresh(EntityReader.java:251)
                                                                                            at io.requery.sql.EntityReader.refresh(EntityReader.java:182)
                                                                                            at io.requery.sql.EntityReader.load(EntityReader.java:152)
                                                                                            at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61)
                                                                                            at io.requery.proxy.EntityProxy.get(EntityProxy.java:75)
                                                                                            at io.requery.proxy.EntityProxy.get(EntityProxy.java:70)
                                                                                            at com.xxx.MyModelEntity.getProperty(MyModelEntity.java:304)
                                                                                            at com.xxx.saveMyModelSample(MyModel.kt:65)
```

Inside the Android Studio variable watch window, the "person" is always null from within the "address", even after assignment and after explicity saving. And because of the casting issue, even a statement like: `Log.d("testing", "is the parent null? " + (address.person == null))` crashes.

**Comment by npurushe** [comment]
Hi you'll need to add converters (`@Converter`) to those fields if you intend to store them or mark them with `@Transisent` to not include them.
