### ISSUE TITLE
Kotlin: select(SomeEntity::property) returns type Return<out Result<SomeEntity>>

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#499]
Requery version: 1.2.0

Intent: 
I'd like to use a select statement result as part of another select statement without loading full entities as described here:
https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/FunctionalTest.java#L1173

Example 1:

    val qa = store.select(IJobApplication::jobOfferId).distinct() where (IJobApplication::candidateId eq candidateId)
    val ra = qa.get()
    val la = ra.toList()

results in 

    Caused by: java.util.NoSuchElementException
       at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:106)
       at io.requery.query.BaseResult.collect(BaseResult.java:77)
       at io.requery.query.BaseResult.toList(BaseResult.java:69)
       ...
    Caused by: java.sql.SQLDataException: no column _id
       at io.requery.android.sqlite.CursorResultSet.findColumn(CursorResultSet.java:114)
       at io.requery.sql.EntityReader.readCacheKey(EntityReader.java:472)
       at io.requery.sql.EntityReader.fromResult(EntityReader.java:508)
       at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
       at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
       at io.requery.query.BaseResult.collect(BaseResult.java:77) 
       at io.requery.query.BaseResult.toList(BaseResult.java:69) 
       ...

`_id` is primary key of `IJobApplication`.

Example 2: 
Using `qa` as a `notIn` argument produces the following error:

    Caused by: io.requery.sql.StatementExecutionException: Exception executing statement: select _id, authorId, createdAt, description, endsAt, gender, id, localCanContributeToNotifications, localSeen, localShouldShowNotification, offerDuration, offerUntil, pendingCreate, pendingRequestId, pendingRetry, pendingStatus, place, salaryUnit, salaryValue, showCandidatesDuration, showCandidatesUntil, startsAt, status, updatedAt from IJobOffer where authorId is not null and authorId != ? and status != ? and id not in ? order by offerUntil desc limit 10 
       at io.requery.sql.SelectResult.iterator(SelectResult.java:131)
       at io.requery.query.BaseResult.iterator(BaseResult.java:121)
       at io.requery.query.BaseResult.collect(BaseResult.java:75)
       at io.requery.query.BaseResult.toList(BaseResult.java:69)
       ...
    Caused by: android.database.sqlite.SQLiteException: near "?": syntax error (code 1): , while compiling: select _id, authorId, createdAt, description, endsAt, gender, id, localCanContributeToNotifications, localSeen, localShouldShowNotification, offerDuration, offerUntil, pendingCreate, pendingRequestId, pendingRetry, pendingStatus, place, salaryUnit, salaryValue, showCandidatesDuration, showCandidatesUntil, startsAt, status, updatedAt from IJobOffer where authorId is not null and authorId != ? and status != ? and id not in ? order by offerUntil desc limit 10
       at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
       at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:919)
       at io.requery.android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:522)
       at io.requery.android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:598)
       at io.requery.android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
       at io.requery.android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:37)
       at io.requery.android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:985)
       at io.requery.android.sqlitex.SqlitexPreparedStatement.<init>(SqlitexPreparedStatement.java:39)
       at io.requery.android.sqlitex.SqlitexConnection.prepareStatement(SqlitexConnection.java:129)
       at io.requery.android.sqlite.BaseConnection.prepareStatement(BaseConnection.java:171)
       at io.requery.sql.SelectResult.createStatement(SelectResult.java:74)
       at io.requery.sql.SelectResult.iterator(SelectResult.ja
    
    E/SQLiteLog: (1) near "?": syntax error

**Comment by npurushe** [comment]
version 1.3.0 contains this fix, note now partial selects require the type to be passed as the first parameter, this is a minor breaking API change so the version was increased to 1.3.0.
