### ISSUE TITLE
Android BasePreparedStatement ISO8601_FORMAT is not thread-safe

### ISSUE THREAD

**Issue by MikeNicholls** [requery/requery#513]
Running the following on Android:
```java
@Test
public void testDateQueryMultiThreaded() throws InterruptedException, ExecutionException, TimeoutException {
    int count = 100;
    int threads = 4;
    final int iterations = 100;
    for (int i = 0; i < count; i++) {
        Person person = randomPerson();
        data.insert(person);
    }
    final Executor executor = Executors.newFixedThreadPool(threads);
    final AtomicInteger totalCount = new AtomicInteger(0);
    FutureTask[] tasks = new FutureTask[threads];
    Callable<Void> callable = new Callable<Void>() {
        @Override
        public Void call() {
            Date startDate = new Date(-2208988800000L);
            Date endDate = new Date(946684800000L);
            for (int i = 0; i < iterations; ++i) {
                List<Person> people = data.select(Person.class)
                        .where(Person.BIRTHDAY.between(startDate, endDate))
                        .get()
                        .toList();
                totalCount.addAndGet(people.size());
            }
            return null;
        }
    };
    for (int i = 0; i < threads; ++i) {
        FutureTask<Void> task = new FutureTask<>(callable);
        tasks[i] = task;
        executor.execute(task);
    }
    for (FutureTask<?> task : tasks) {
        task.get(30, TimeUnit.SECONDS);
    }
    assertEquals(threads * count * iterations, totalCount.get());
}
```
Often fails with this exception:
```
io.requery.sql.StatementExecutionException: Exception executing statement: select id, address, age, birthday, description, email, homepage, name, picture, uuid from Person where birthday between ? and ?
at io.requery.sql.SelectResult.iterator(SelectResult.java:131)
at io.requery.query.BaseResult.iterator(BaseResult.java:121)
at io.requery.query.BaseResult.collect(BaseResult.java:75)
at io.requery.query.BaseResult.toList(BaseResult.java:69)
at io.requery.test.FunctionalTest$1.call(FunctionalTest.java:1504)
at io.requery.test.FunctionalTest$1.call(FunctionalTest.java:1495)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: Invalid day of week: 0
at java.util.SimpleTimeZone.checkRange(SimpleTimeZone.java:560)
at java.util.SimpleTimeZone.getOffset(SimpleTimeZone.java:346)
at java.util.GregorianCalendar.fullFieldsCalc(GregorianCalendar.java:503)
at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:599)
at java.util.Calendar.complete(Calendar.java:842)
at java.util.Calendar.get(Calendar.java:897)
at java.text.SimpleDateFormat.append(SimpleDateFormat.java:676)
at java.text.SimpleDateFormat.formatImpl(SimpleDateFormat.java:529)
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:820)
at java.text.DateFormat.format(DateFormat.java:314)
at io.requery.android.sqlite.BasePreparedStatement.setDate(BasePreparedStatement.java:214)
at io.requery.android.sqlite.BasePreparedStatement.setDate(BasePreparedStatement.java:209)
at io.requery.sql.type.JavaDateType.write(JavaDateType.java:47)
at io.requery.sql.type.JavaDateType.write(JavaDateType.java:28)
at io.requery.sql.GenericMapping.write(GenericMapping.java:366)
at io.requery.sql.SelectResult.iterator(SelectResult.java:123)
... 9 more
```
But can also fail with an unexpected number of entities being selected:
``java.lang.AssertionError: expected:<40000> but was:<35821>``

**Comment by npurushe** [comment]
1.3.1 has this change thanks!
