### ISSUE TITLE
NotMappedException with JunctionTable type

### ISSUE THREAD

**Issue by junseon** [requery/requery#517]
```
@Entity(name="UserEntity")
interface UserEntitable : Persistable {
    ...
    @get:JunctionTable(type = UserSongJuction::class)
    @get:ManyToMany
    val songs: MutableList<SongEntitable>
    ...
}
```

```
@Entity(model = "default", stateless = false)
@Table(name = "User_Song")
interface UserSongJuction : Persistable {

    @get:ForeignKey(delete = ReferentialAction.CASCADE, update = ReferentialAction.CASCADE, references = UserEntity::class)
    @get:Key
    var userId: Long

    @get:ForeignKey(delete = ReferentialAction.NO_ACTION, update = ReferentialAction.NO_ACTION, references = SongEntity::class)
    @get:Key
    var songId: Long

}
```
```
@Entity(name = "SongEntity")
interface SongEntitable : Persistable {

    @get:Key
    var id: Long

    var name: String

    not mapped any here.
```
then I run my project and crash
```
io.requery.meta.NotMappedException
    at io.requery.meta.ImmutableEntityModel.typeOf(ImmutableEntityModel.java:52)
    at io.requery.sql.SchemaModifier.createForeignKeyColumn(SchemaModifier.java:391)
```

How can I fix this?

**Comment by npurushe** [comment]
Hi if you change your junction table foreign key `references` to be the base entity class instead of the generated one that may resolve the NotMappedException. This should work but it looks like the kotlin annotation plugin may behave slightly differently from Java in this regard.

**Comment by tonyjs** [comment]
Thanks. I try to modify `references` class to base entity class. but the result is same.
