### ISSUE TITLE
Can't insert a AutoValue object

### ISSUE THREAD

**Issue by orafaaraujo** [requery/requery#542]
My AutoValue Object

```
@AutoValue
@Entity
public abstract class FactEntity implements Persistable {

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder setId(int id);
        public abstract Builder setTitle(String title);
        public abstract FactEntity build();
    }

    public static Builder builder() {
        return new AutoValue_FactEntity.Builder().setId(-1);
    }

    @Key
    @Generated
    public abstract int id();
    public abstract String title();
}
```
Data object (using Dagger)

```@Module
public class DatabaseModule {

    @Provides
    @Singleton
    ReactiveEntityStore<Persistable> provideDatabase(Configuration configuration) {
        return ReactiveSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
    }

    @Provides
    @Singleton
    Configuration provideConfiguration(DatabaseSource source, EntityModel model) {

        return new ConfigurationBuilder(source, model)
                .useDefaultLogging()
                .setWriteExecutor(Executors.newSingleThreadExecutor())
                .build();
    }

    @Provides
    @Singleton
    EntityModel provideModels() {
        return Models.DEFAULT;
    }

    @Provides
    @Singleton
    DatabaseSource provideDatabaseSource(Context context) {
        final DatabaseSource source = new DatabaseSource(context, Models.DEFAULT, 1);
        if (BuildConfig.DEBUG) {
            source.setTableCreationMode(TableCreationMode.DROP_CREATE);
        }
        return source;
    }
```
My insert 
```
mDatabase.insert(fact)
	.toObservable()
	.subscribeOn(Schedulers.io())
	.observeOn(AndroidSchedulers.mainThread())
	.subscribe(factEntity -> Timber.i(factEntity.toString()));
```

And I'm getting **java.lang.UnsupportedOperationException**
```
java.lang.UnsupportedOperationException
	at com.orafaaraujo.depuis.repository.entity.FactEntityType$2.setInt(FactEntityType.java:44)
	at com.orafaaraujo.depuis.repository.entity.FactEntityType$2.setInt(FactEntityType.java:26)
	at io.requery.proxy.EntityProxy.setInt(EntityProxy.java:159)
	at io.requery.sql.EntityWriter.readKeyFromResult(EntityWriter.java:319)
	at io.requery.sql.EntityWriter.readGeneratedKeys(EntityWriter.java:295)
	at io.requery.sql.EntityWriter.access$200(EntityWriter.java:69)
	at io.requery.sql.EntityWriter$4.read(EntityWriter.java:411)
	at io.requery.sql.PreparedQueryOperation.readGeneratedKeys(PreparedQueryOperation.java:95)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:56)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
	at io.requery.query.BaseScalar.value(BaseScalar.java:48)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:439)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:399)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:203)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:189)
	at io.requery.reactivex.WrappedEntityStore$1.call(WrappedEntityStore.java:67)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
	at io.reactivex.Single.subscribe(Single.java:2558)
	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
```

**Comment by GeorgePetri** [comment]
I think your FactEntity has to be annotated with @AutoValue

**Comment by orafaaraujo** [comment]
@GeorgePetri 
I'm sorry, the AutoValue already is annotated but I didn't put in the code... will fix it!

Thanks!

**Comment by npurushe** [comment]
If you have an entity with a generated key using AutoValue then the key cannot be set back on the original object since it's immutable. There is a special overload which is like `<Key> key = insert(<Type>, <KeyClass>)` for this case:

```java
Integer key = store.insert(factEntity, Integer.class);
```
Hope that helps. Would also work if you change your entity to not use a generated key.

**Comment by orafaaraujo** [comment]
Hi,

Yes, removing generated key works! But I would not like to handle with this myself.

When I use the code that you suggest I can't insert anything (I don't know if it is clean but I'm using ReactiveEntityStore)

For now I'll just change my key to multiple key... Thank you

**Comment by ecdpalma** [comment]
I've been able to get a similar case using `ReactiveEntityStore` working. But it feels strange.

```
@AutoValue
@Entity
public abstract class Entity {
  @Key
  @Generated
  public abstract Integer id();
...
}
```

Insert an instance with the recommended method, then map to a new instance, using the id just returned.

```
store.insert(newEntity, Integer.class).map(id -> {
 /* return new immutable entity using newEntity and the id */
});
```

Just note that, before calling `insert`, a dummy `id` needs to be set in `newEntity` (as required by AutoValue). If `@Nullable` is used for the `id`, then the following exception will be raised.

```
Caused by: java.lang.NullPointerException
at io.requery.util.Objects.requireNotNull(Objects.java:36)
at io.requery.cache.WeakEntityCache$KeyReference.<init>(WeakEntityCache.java:43)
at io.requery.cache.WeakEntityCache$WeakReferenceMap.putValue(WeakEntityCache.java:65)
at io.requery.cache.WeakEntityCache.put(WeakEntityCache.java:105)
at io.requery.sql.EntityWriter.insert(EntityWriter.java:450)
at io.requery.sql.EntityWriter.insert(EntityWriter.java:402)
at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:204)
at io.requery.reactivex.WrappedEntityStore$3.call(WrappedEntityStore.java:88)
```
