### ISSUE TITLE
"Delete Entity" is not working

### ISSUE THREAD

**Issue by 3DRaven** [requery/requery#544]
Example:

@Entity
abstract public class AbstractMessage implements Persistable {

    @Key
    @Generated
    int id;

    String action;
    boolean isShowed = false;
    long time;

    @OneToMany(cascade = {CascadeAction.SAVE, CascadeAction.DELETE})
    Set<MessageData> data;
}

@Entity
public interface MessageData {

    @Key
    @Generated
    int getId();

    String getKey();
    String getValue();
    @ManyToOne
    Message getMessage();
}

Message msg = createRandomMessage();
messageDataStore.insert(msg).blockingGet();
assertTrue(msg.getId() > 0);
messageDataStore.delete(msg).blockingAwait();
Message cached = messageDataStore.select(Message.class)
.where(Message.ID.equal(msg.getId())).get().firstOrNull();
assertNull(cached);

StackTrace:

io.requery.sql.RowCountException: Expected 1 row affected actual 0
                                                                                      at io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:174)
                                                                                      at io.requery.sql.EntityWriter.delete(EntityWriter.java:842)
                                                                                      at io.requery.sql.EntityWriter.cascadeRemove(EntityWriter.java:928)
                                                                                      at io.requery.sql.EntityWriter.clearAssociations(EntityWriter.java:878)
                                                                                      at io.requery.sql.EntityWriter.delete(EntityWriter.java:840)
                                                                                      at io.requery.sql.EntityDataStore.delete(EntityDataStore.java:343)
                                                                                      at io.requery.reactivex.WrappedEntityStore$14.call(WrappedEntityStore.java:201)
                                                                                      at io.requery.reactivex.WrappedEntityStore$14.call(WrappedEntityStore.java:198)
                                                                                      at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:35)
                                                                                      at io.reactivex.Completable.subscribe(Completable.java:1635)
                                                                                      at io.reactivex.Completable.blockingAwait(Completable.java:912)
                                                                                      at

**Comment by npurushe** [comment]
Your example is missing the `Message` defintion, wasn't able to reproduce it on a similar model, probably need more info. thanks

**Comment by npurushe** [comment]
Please post back if you have more info, thanks!

**Comment by masc3d** [comment]
Coud you please re-open this @npurushe. I'm seeing this issue as well with `1.4.0`, it occurs very sporadically.

```Caused by: io.requery.sql.RowCountException: Expected 1 row affected actual 0
                                                                                             	at io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:181) ~[na:0.0]
                                                                                             	at io.requery.sql.EntityWriter.delete(EntityWriter.java:879) ~[na:0.0]
                                                                                             	at io.requery.sql.EntityWriter.cascadeRemove(EntityWriter.java:971) ~[na:0.0]
                                                                                             	at io.requery.sql.EntityWriter.clearAssociations(EntityWriter.java:915) ~[na:0.0]
                                                                                             	at io.requery.sql.EntityWriter.delete(EntityWriter.java:877) ~[na:0.0]
                                                                                             	at io.requery.sql.EntityDataStore.delete(EntityDataStore.java:343) ~[na:0.0]
                                                                                             	at io.requery.sql.KotlinEntityDataStore.delete(KotlinEntityDataStore.kt:140) ~[na:0.0]```

**Comment by masc3d** [comment]
@npurushe didn't see #644, which is presumably a duplicate of this issue.
