### ISSUE TITLE
Deadlock in EntityReader

### ISSUE THREAD

**Issue by alex-shpak** [requery/requery#550]
Hi!

While using requery in backend application we faced some deadlock which we wasn't able to fix. It happens during many simultaneous requests.
Also we using [Hikari](https://github.com/brettwooldridge/HikariCP) connection poll limited by 8 connections.
Maybe you will have some idea what is the issue.

Here is thread dump
```
dw-14 - GET /v0.1/packages?name=Tutorial%20%23130 id=14 state=BLOCKED
    - waiting to lock <0x0ff29418> (a io.requery.proxy.EntityProxy)
     owned by dw-17 - DELETE /v0.1/packages/1652 id=17
    at io.requery.sql.EntityReader.fromResult(EntityReader.java:526)
    at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
    at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
    at io.requery.query.BaseResult.collect(BaseResult.java:77)
    at io.requery.query.BaseResult.toList(BaseResult.java:69)
    at se.danfoss.stcloud.resource.latest.PackageResource.list(PackageResource.java:86)
    
dw-18 - POST /v0.1/applications id=18 state=BLOCKED
    - waiting to lock <0x45b6679c> (a io.requery.proxy.EntityProxy)
     owned by dw-16 - DELETE /v0.1/packages/1652 id=16
    at io.requery.sql.EntityReader.fromResult(EntityReader.java:526)
    at io.requery.sql.EntityResultReader.read(EntityResultReader.java:45)
    at io.requery.sql.ResultSetIterator.next(ResultSetIterator.java:101)
    at io.requery.query.BaseResult.collect(BaseResult.java:77)
    at io.requery.proxy.CollectionInitializer.initialize(CollectionInitializer.java:58)
    at io.requery.sql.EntityReader.refreshAssociation(EntityReader.java:271)
    at io.requery.sql.EntityReader.refresh(EntityReader.java:251)
    at io.requery.sql.EntityReader.refresh(EntityReader.java:182)
    at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:753)
    at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:633)
    at io.requery.sql.EntityWriter.insert(EntityWriter.java:443)
    at io.requery.sql.EntityWriter.insert(EntityWriter.java:401)
    at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:204)
    at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190)
    
dw-11 - GET /v0.1/packages?name=Tutorial%20%23130 id=11 state=BLOCKED
    - waiting to lock <0x33eda0ab> (a io.requery.sql.EntityDataStore$DataContext)
     owned by dw-15 - GET /v0.1/packages?name=Tutorial%20%23130 id=15
    at io.requery.sql.EntityDataStore$DataContext.read(EntityDataStore.java:649)
    at io.requery.sql.EntityDataStore.select(EntityDataStore.java:449)
    at se.danfoss.stcloud.setup.dropwizard.AuthBundle$AuthHandler.authenticate(AuthBundle.java:52)
    at se.danfoss.stcloud.setup.dropwizard.AuthBundle$AuthHandler.authenticate(AuthBundle.java:47)
```
There are 19 more blocked threads like last one.

I'm not sure which data is useful to include here so please write what you need.

@devoto13

**Comment by npurushe** [comment]
Would you be able to share the entire thread dump? thanks

**Comment by alex-shpak** [comment]
Here is [gist](https://gist.github.com/alex-shpak/28f9f7b2d561afa05d14bca9f5482f6e)

**Comment by npurushe** [comment]
It looks like there are not enough connections to satisfy all the operations, will try to reproduce this
