### ISSUE TITLE
Wrong implementation of CollectionObserver

### ISSUE THREAD

**Issue by mirkoluchi** [requery/requery#568]
CollectionChanges is implemented in a way that **removing an element** that was **previously added** results in the element to be **removed**, while I think it should simply result in neither added nor removed.

Example:

```Java

ObservableList list = ....
Object obj = new Object();
list.add(obj);
list.remove(obj);

CollectionChanges observer = (CollectionChanges) list.observer();
Collection addedElements = observer.addedElements();
Collection removedElements = observer.removedElements();

// obj results as 'removed', while it should result as neither 'added' nor 'removed'
assertTrue(addedElements.isEmpty());
assertTrue(removedElements.contains(obj));
```

So I would change the **CollectionChanges** class like this:
```Java

/* CollectionChanges.java */

@Override
public void elementRemoved(E element) {
        Objects.requireNotNull(element);
        boolean wasAdded = added.remove(element);
        if (!wasAdded && removed.add(element)) {
            proxy.setState(attribute, PropertyState.MODIFIED);
        }
}

```

Because of the current implementation, this statement gives an error (and there might be other similar issues):

```Java

// Entity has a to-many relationship 'relatedEntities' to RelatedEntity

Entity entity = new Entity();
RelatedEntity relatedEntity = new RelatedEntity();
entity.getRelatedEntities().add(relatedEntity); // collection marks relatedEntity as 'added', which is correct
entity.getRelatedEntities().remove(relatedEntity); // collection marks relatedEntity as 'removed', which is NOT correct

getEntityDataStore().insert(entity); // This throws an exception, because it tries to remove the association between entity and related entity, that never existed
// io.requery.sql.RowCountException: Expected 1 row affected actual 0
// at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:744)
// at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:634)
// at io.requery.sql.EntityWriter.insert(EntityWriter.java:444)
// at io.requery.sql.EntityWriter.insert(EntityWriter.java:402)
// at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:204)
// at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190)

```

**Comment by npurushe** [comment]
This change proposal looks ok
