### ISSUE TITLE
IndexOutOfBoundsException from raw queries without arguments

### ISSUE THREAD

**Issue by exitface** [requery/requery#586]
This is on Requery version 1.3.2 on Android using Kotlin

`val ret = data.raw(Page::class, "SELECT * FROM Page")`

Throws

```java
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.get(ArrayList.java:411)
at io.requery.sql.ParameterInliner.apply(ParameterInliner.java:82)
at io.requery.sql.RawEntityQuery.<init>(RawEntityQuery.java:55)
at io.requery.sql.EntityDataStore.raw(EntityDataStore.java:535)
at io.requery.sql.KotlinEntityDataStore.raw(KotlinEntityDataStore.kt:146)
at io.requery.reactivex.KotlinReactiveEntityStore.raw(KotlinReactiveEntityStore.kt:79)
```

However the following will work

`val ret = data.raw(Page::class, "SELECT * FROM Page where ?", true)`

**Comment by npurushe** [comment]
Could share your definition of `Page`? wasn't able to reproduce this with the test entity classes.

**Comment by exitface** [comment]
```kotlin
import io.requery.*
import io.requery.sql.type.TimeStampType
import java.sql.Timestamp
import java.util.*

@Entity
interface Page : android.os.Parcelable, io.requery.Persistable {
  @get:Key
  @get:Generated
  var id: Int

  @get:Column(name = "is_deleted", value = "f")
  var isDeleted: Boolean

  var title: String

  var content: String

  @get:Column(name = "inserted_at", nullable = false, value = "(DATETIME('now'))")
  var insertedAt: Timestamp

  @get:Column(name = "updated_at", nullable = false, value = "(DATETIME('now'))")
  var updatedAt: Timestamp
}
```

I should add I'm also getting the error when omitting the class `data.raw("SELECT * FROM Page")`

**Comment by npurushe** [comment]
Unfortunately I couldn't reproduce your problem even with that model. I have added a possible fix based on the stack trace, but it maybe related to what Kotlin version you're using.
