### ISSUE TITLE
NullPointerException when saving @OneToMany entity

### ISSUE THREAD

**Issue by gollyzila** [requery/requery#60]
I am getting the following NPE error when I try to save a `Meal` that has a list of `MealItem`. I've gone through the wiki but haven't found what I could be doing wrong. Any help?

**logcat**
```
03-28 13:44:22.313 7390-7390/com.kevin.meals D/MealRepositoryImpl:58: saveMeal is new save
03-28 13:44:22.343 7390-7390/com.kevin.meals I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
03-28 13:44:22.344 7390-7390/com.kevin.meals I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
03-28 13:44:22.375 7390-7390/com.kevin.meals D/AndroidRuntime: Shutting down VM
                                                               
                                                               
                                                               --------- beginning of crash
03-28 13:44:22.381 7390-7390/com.kevin.meals E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.kevin.meals, PID: 7390
                                                               java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object io.requery.util.function.Supplier.get()' on a null object reference
                                                                   at io.requery.sql.Attributes.get(Attributes.java:35)
                                                                   at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:687)
                                                                   at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:592)
                                                                   at io.requery.sql.EntityWriter.insert(EntityWriter.java:448)
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:195)
                                                                   at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:185)
                                                                   at com.kevin.meals.data.MealRepositoryImpl.saveMeal(MealRepositoryImpl.java:59)
                                                                   at com.kevin.meals.mealPlanner.addEditMeal.AddEditMealPresenter.onSaveMeal(AddEditMealPresenter.java:57)
                                                                   at com.kevin.meals.mealPlanner.addEditMeal.AddEditMealDialog$1.onClick(AddEditMealDialog.java:92)
                                                                   at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:336)
                                                                   at android.view.View.performClick(View.java:5204)
                                                                   at android.view.View$PerformClick.run(View.java:21153)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**AbstractMeal.java**
```java
@Entity
abstract class AbstractMeal implements Parcelable{
  @Key @Generated
  int id;

  @ForeignKey
  @OneToOne
  MealType mealType;

  @Convert(JodaTimeLocalDateConverter.class)
  LocalDate plannedDate;

  @OneToMany
  List<MealItem> mealItemList;
}
```

**AbstractMealItem.java**
```java
@Entity
abstract class AbstractMealItem {
  @Key @Generated
  int id;

  String description;

//  @OneToMany(cascade = CascadeAction.NONE)
//  List<Ingredient> ingredientList;

  String notes;
}
```

**MealRepositoryImpl.java**
```java
public class MealRepositoryImpl implements MealRepository {
  private EntityDataStore<Persistable> mDataStore;

  [...]

  @Override
  public Meal saveMeal(String mealTypeString, LocalDate date, ArrayList<String> mealItemStringList, int id) {
    // Set meal type
    MealType mealType = new MealType();
    mealType.setDescription(mealTypeString);

    // Set meal item list
    ArrayList<MealItem> mealItemList = new ArrayList<>();
    for (String mealItemString :
        mealItemStringList) {
      // Set meal items
      MealItem mealItem = new MealItem();
      mealItem.setDescription(mealItemString);

      mealItemList.add(mealItem);
    }

    Meal meal = new Meal();
    meal.setMealType(mealType);
    meal.setPlannedDate(date);
    meal.getMealItemList().addAll(mealItemList);
    if (id > 0) {
      Timber.d("saveMeal is edit");

      mDataStore.update(meal);

    } else {
      Timber.d("saveMeal is new save");
      mDataStore.insert(meal);
    }

    return meal;
  }
}
```

**Comment by npurushe** [comment]
Hi thanks for the clear example code. Looks like you need to add a `@ManyToOne` link back to the parent Meal entity. This is needed because it will be used as the foreign key to the referencing Meal. 

```java
    ...
    @ManyToOne
    Meal meal; // owner of the item
```

**Comment by gollyzila** [comment]
Thank you for the quick reply!

I saw the usage of `@ManyToOne` in the unit tests for a `Person`'s `Phone` but I assumed it was specific to just the `MutableResult` and `Set` implementations (not `List`) since they used a `mappedBy = "owner"` value.

After adding your `@ManyToOne`suggestion to `MealItem` I am getting a different error when saving. It has occurred both before and after reinstalling the debug version of my app.

**logcat**
```
03-28 22:45:40.769 29035-29035/com.kevin.meals D/MealRepositoryImpl:58: saveMeal is new save
03-28 22:45:40.779 29035-29035/com.kevin.meals I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
03-28 22:45:40.779 29035-29035/com.kevin.meals I/art: Rejecting re-init on previously-failed class java.lang.Class<io.requery.query.SuppliedScalar$1>
03-28 22:45:40.788 29035-29035/com.kevin.meals E/SQLiteLog: (1) table MealItem has no column named meal
03-28 22:45:40.789 29035-29035/com.kevin.meals D/AndroidRuntime: Shutting down VM
03-28 22:45:40.790 29035-29035/com.kevin.meals E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.kevin.meals, PID: 29035
                                                                 android.database.sqlite.SQLiteException: table MealItem has no column named meal (code 1): , while compiling: insert into MealItem (description, meal, notes) values (?, ?, ?)
                                                                     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                     at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:994)
                                                                     at io.requery.android.sqlite.SqlitePreparedStatement.<init>(SqlitePreparedStatement.java:38)
                                                                     at io.requery.android.sqlite.SqliteConnection.prepareStatement(SqliteConnection.java:172)
                                                                     at io.requery.sql.ConnectionDelegate.prepareStatement(ConnectionDelegate.java:237)
                                                                     at io.requery.sql.PreparedQueryOperation.prepare(PreparedQueryOperation.java:49)
                                                                     at io.requery.sql.EntityUpdateOperation$1.get(EntityUpdateOperation.java:66)
                                                                     at io.requery.sql.EntityUpdateOperation$1.get(EntityUpdateOperation.java:56)
                                                                     at io.requery.query.SuppliedScalar.value(SuppliedScalar.java:51)
                                                                     at io.requery.sql.EntityWriter.insert(EntityWriter.java:446)
                                                                     at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:818)
                                                                     at io.requery.sql.EntityWriter.updateInverseAssociation(EntityWriter.java:689)
                                                                     at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:592)
                                                                     at io.requery.sql.EntityWriter.insert(EntityWriter.java:448)
                                                                     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:195)
                                                                     at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:185)
                                                                     at com.kevin.meals.data.MealRepositoryImpl.saveMeal(MealRepositoryImpl.java:59)
                                                                     at com.kevin.meals.mealPlanner.addEditMeal.AddEditMealPresenter.onSaveMeal(AddEditMealPresenter.java:57)
                                                                     at com.kevin.meals.mealPlanner.addEditMeal.AddEditMealDialog$1.onClick(AddEditMealDialog.java:92)
                                                                     at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:336)
                                                                     at android.view.View.performClick(View.java:5204)
                                                                     at android.view.View$PerformClick.run(View.java:21153)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by npurushe** [comment]
By adding the field the schema changed. So if you're in the development phase you can just clear the apps data and restart and the database will be created with the new schema. For release versions typically you increase the db schema version and provide upgrade logic (requery will add missing tables/columns automatically but not anything beyond that)

**Comment by gollyzila** [comment]
Thanks, clearing the app data fixed that issue.
