### ISSUE TITLE
Delete Kotlin data class NotMappedException

### ISSUE THREAD

**Issue by channguyen** [requery/requery#609]
I'm running into a weird exception when try to delete all objects from table, where the delete is very simple:
```
override fun clear(): Maybe<Boolean> {
    return dataStore.delete(User::javaClass).toMaybe()
}
```

This is the stack trace:
```
vex.KotlinReactiveEntityStore$delete$1.call(KotlinReactiveEntityStore.kt:73)
	at io.requery.reactivex.KotlinReactiveEntityStore$delete$1.call(KotlinReactiveEntityStore.kt:37)
	at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:35)
	at io.reactivex.Completable.subscribe(Completable.java:1635)
	at io.reactivex.internal.operators.maybe.MaybeFromCompletable.subscribeActual(MaybeFromCompletable.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:3725)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2007)
	at co.bird.birdseye.repository.UserRepositoryTest.setUp(UserRepositoryTest.kt:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
Any idea?

**Comment by npurushe** [comment]
Since you're using the kotlin module you shouldn't use `User::javaClass` but rather `User::class`, hope that helps
