### ISSUE TITLE
Limitation on Entities packages name inside a single Android module

### ISSUE THREAD

**Issue by lubbo** [requery/requery#613]
I have some entities placed in different packages inside the same Android module.

If packages names ends with the same last path component name the compilation fails.

i.e. 

* it.something.**core**.AbstractEntityA
* com.somethingelse.**core**.AbstractEntityB

compilation fails without any specific error, but the first missing reference to a not generated entity.
Something like "cannot find symbol"

This configuration works:

* it.something.**core1**.AbstractEntityA
* com.somethingelse.**core2**.AbstractEntityB

Is a known limitation or I there could be something wrong on my project configuration?

Thanks!

**Comment by npurushe** [comment]
If the compilation fails, there has to be an error. Do you have the output from javac? Thanks

**Comment by lubbo** [comment]
```./gradlew build```

```
:mdl.test:compileReleaseJavaWithJavac
/..../mdl/test/core/util/Comparator.java:15: error: cannot find symbol
import com.mdl.test.core.Models;
                                        ^
  symbol:   class Models
  location: package com.mdl.test.core
1 error
:mdl.test:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mdl.test:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

```./gradlew  build --stacktrace --debug```

```
09:08:40.776 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
09:08:42.929 [ERROR] [system.err] /..../mdl.test/src/main/java/com/mdl/test/core/util/Comparator.java:15: error: cannot find symbol
09:08:42.930 [ERROR] [system.err] import com.mdl.test.core.Models;
09:08:42.930 [ERROR] [system.err]                                         ^
09:08:42.930 [ERROR] [system.err]   symbol:   class Models
09:08:42.930 [ERROR] [system.err]   location: package com.mdl.test.core
09:08:42.932 [ERROR] [system.err] 1 error
09:08:42.933 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
09:08:42.933 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':mdl.test:compileReleaseJavaWithJavac'
09:08:42.933 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :mdl.test:compileReleaseJavaWithJavac FAILED
09:08:42.934 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :mdl.test:compileReleaseJavaWithJavac (Thread[Daemon worker Thread 3,5,main]) completed. Took 2.168 secs.
09:08:42.934 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.277 completed (0 in use)
09:08:42.934 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 3,5,main]] finished, busy: 2.434 secs, idle: 0.033 secs
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':mdl.test:compileReleaseJavaWithJavac'.
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Compilation failed; see the compiler error output for details.
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
09:08:42.935 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mdl.test:compileReleaseJavaWithJavac'.
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
09:08:42.936 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
09:08:42.937 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.Swapper.swap(Swapper.java:38)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:130)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
09:08:42.938 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
09:08:42.939 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
09:08:42.939 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
09:08:42.939 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
09:08:42.939 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
09:08:42.939 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
09:08:42.939 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 70 more
09:08:42.939 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:08:42.939 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
09:08:42.939 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
09:08:42.939 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
09:08:42.939 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 9.107 secs
```

**Comment by consp1racy** [comment]
Compilation of your project fails, annotation processing and generating of entities produces no error. You're trying to import entities from where they aren't. But they are generated somewhere.

Navigate generated sources in Android Studio and look for the generated entities. Once you find them report any disparity between expected and actual location.

**Comment by lubbo** [comment]
You are right!

I tested with following classes:

`com.mdl.test.core.AbstractEntity`
`com.mdl.test2.core.AbstractEntity2`

The Models.java is generated into package **com.mdl.test**

```
// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package com.mdl.test;

import com.mdl.test.core.Entity;
import com.mdl.test2.core.Entity2;

public class Models {
    public static final EntityModel CORE = new EntityModelBuilder("core")
    .addType(Entity2.$TYPE)
    .addType(Entity.$TYPE)
    .build();

    private Models() {
    }
}
```

Is package `com.mdl.test` correct?
Shouldn't be considered the same usecase as following?

`com.mdl.test.core.AbstractEntity`
`com.mdl.test2.core2.AbstractEntity2`

Where it generates 2 different Models.java

`com.mdl.test.core.Models`
`com.mdl.test2.core2.Models`

Maybe difference on package generation is related to the fact that the EntityModel static property would be named CORE for both Models and is constructed with "core" name?

```
[...]
public class Models {
    public static final EntityModel CORE = new EntityModelBuilder("core")
    [...]
}
```

I need to know the Models package because I'm generating other code that needs the EntityModel.

**Comment by consp1racy** [comment]
Looks like `Models` is generated in the library or application package as specified in `AndroidManifest.xml` or `build.gradle`. Entity implementations are generated wherever the prototypes were. This is the expected behavior. Can you confirm this is also your case?

**Comment by lubbo** [comment]
> Entity implementations are generated wherever the prototypes were.
Yes

But `Models` package depends on prototypes packages.

* Case 1

`com.mdl.test.core.AbstractEntity`
`com.mdl.test2.core2.AbstractEntity2`

generates 2 different Models.java:

`com.mdl.test.core.Models`
`com.mdl.test2.core2.Models`

* Case 2

`com.mdl.test.core.AbstractEntity`
`com.mdl.test2.core.AbstractEntity2`

generates only 1 Models.java:

`com.mdl.test.Models`

**Comment by npurushe** [comment]
Case 1 and 2 look identical? Different models only get generated if 1) You use `@Entity(model="")` to create different models or 2) The classes are in different modules in which case they cannot share the same model because of limitations in the way the annotation processors works.

**Comment by lubbo** [comment]
Classes are not in different modules and I've not specified @Entity(model="").
I should probably make a test project to better explain the case ....

**Comment by lubbo** [comment]
I've created a public repo here: 
git@bitbucket.org:mirkoluchi/requery-issues.git

In the sub directory Issue613 you'll find the Android project with 2 different android modules:

* onemodelgenerated
* twomodelgenerated

### onemodelgenerated

Contains 2 entities:

* com.requeryissue1.core.AbstractTestEntity
* com.requeryissue2.core.AbstractTestEntity2

and it generates only 1 Models.java in the following package:
`com.requeryissue2.Models.java`

#### **Question 1**
 What's the logic that select the destination package `com.requeryissue2` and not `com.requeryissue1`?
We need to know the location of Models.java in advance because we are generating code that depends on Models.java location.

### twomodelgenerated

Contains 2 entities:

* com.requeryissue1.core1.AbstractTestEntity
* com.requeryissue2.core2.AbstractTestEntity2

and it generates 2 Models.java:
`com.requeryissue1.core1.Models.java`
`com.requeryissue2.core2.Models.java`

#### **Question 2**
Why in this case it generates 2 Modules.java even if entities in this module are placed in 2 different packages as the module onemodelgenerated.

Could the discriminant be the name of the EntityModel that seems to be got from package last package path component (e.g. **core** and **core1** + **core2**)?

```
package com.requeryissue2;

import com.requeryissue1.core.TestEntity;
import com.requeryissue2.core.TestEntity2;
import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;

public class Models {
    public static final EntityModel CORE = new EntityModelBuilder("core")
    .addType(TestEntity.$TYPE)
    .addType(TestEntity2.$TYPE)
    .build();

    private Models() {
    }
}
```

```
package com.requeryissue1.core1;

import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;

public class Models {
    public static final EntityModel CORE1 = new EntityModelBuilder("core1")
    .addType(TestEntity.$TYPE)
    .build();

    private Models() {
    }
}
```

```
package com.requeryissue2.core2;

import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;

public class Models {
    public static final EntityModel CORE2 = new EntityModelBuilder("core2")
    .addType(TestEntity2.$TYPE)
    .build();

    private Models() {
    }
}
```

**Comment by npurushe** [comment]
Ok will take a look at your example thanks.

**Comment by lubbo** [comment]
Changed example repo to 
https://bitbucket.org/lubbbo/requery-issues
