### ISSUE TITLE
Deleting entity with @OneToMany on delete cascade, fails because SQL deletion returns affected row 0

### ISSUE THREAD

**Issue by lubbo** [requery/requery#644]
Creating 2 entities related by a @OneToMany relation:

**AbstractTestEntity** ->> **AbstractRelatedTestEntity**

the relation is annotated with JPA `javax.persistence.OneToMany` like that:

`@OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH, CascadeType.REMOVE, CascadeType.DETACH})`

```
@Entity()
@Table(name = "TestEntity")
public abstract class AbstractTestEntity {

    @Id
    @Column(nullable = false)
    protected Long id;

    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH, CascadeType.REMOVE, CascadeType.DETACH})
    protected Set<RelatedTestEntity> relatedEntities;
}
```

Assuming this usecase:
1. Create a TestEntity
2.  Add a RelatedTestEntity into the `relatedEntities`
3. Insert TestEntity in the datastore
4. Reload TestEntity from datastore

Deleting TestEntity from datastore fails on `io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:182)`

with following stack trace:

```
io.requery.sql.RowCountException: Expected 1 row affected actual 0
     at io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:182)
     at io.requery.sql.EntityWriter.delete(EntityWriter.java:874)
     at io.requery.sql.EntityWriter.cascadeRemove(EntityWriter.java:960)
     at io.requery.sql.EntityWriter.clearAssociations(EntityWriter.java:910)
     at io.requery.sql.EntityWriter.delete(EntityWriter.java:872)
     at io.requery.sql.EntityDataStore.delete(EntityDataStore.java:343)
     at com.requeryissue.IssueTest.testDeletion(IssueTest.java:103)
```

The operation fails probably because Requery tries to delete the RelatedTestEntity that has been already deleted by ON DELETE CASCADE contratint by SQLite.
SQL DB deletion doesn't fail but returns 0 affected rows and let Requery operation ending with failure after its checkRowsAffected.

You can test the issue in the following repository:
https://bitbucket.org/mirkoluchi/requery-issues 
in the proper **Issue644** directory you can find an Android project replicating the issue in the proper unit test `testDeletionOneToManyCascade`

**Comment by lubbo** [comment]
Changed example repo to
https://bitbucket.org/lubbbo/requery-issues

**Comment by masc3d** [comment]
this bug is caused by having sqlite's native foreign key constraints enabled, which is now the default for `1.4.1` and also causing #698.

we're currently mitigating the issue by overriding `SqlitexDatabaseSource.onConfigure`

```
override fun onConfigure(db: SQLiteDatabase) {
    super.onConfigure(db)
    // TODO: workaround for requery bug #698 and #644 (disabling foreign key constraints)
    db.setForeignKeyConstraintsEnabled(false)
}
```

**Comment by maxxx** [comment]
I noticed that 2 versions of dataStore.delete (for entity and list of entities) works differently in that case.
dataStore.delete(entity) - error
dataStore.delete(Collections.singletonList(log)) - no error

**Comment by masc3d** [comment]
should also be noted, that this `RowCountException` exception (and potentially others) may cause the reference cache to get corrupted / out of sync with db.

after long series of cumbersome workarounds, we finally had to (painfully) migrate away from requery due to this.
