### ISSUE TITLE
java.lang.StackOverflowError: stack size 1038KB

### ISSUE THREAD

**Issue by DreamerII** [requery/requery#650]
version: io.requery:requery - 1.4.0

E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-5
                                                                       Process: com.booklava.booklava, PID: 15077
                                                                       java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.StackOverflowError: stack size 1038KB
                                                                           at java.util.IdentityHashMap.get(IdentityHashMap.java:380)
                                                                           at io.requery.util.ClassMap.get(ClassMap.java:86)
                                                                           at java.util.Collections$UnmodifiableMap.get(Collections.java:1268)
                                                                           at io.requery.meta.ImmutableEntityModel.typeOf(ImmutableEntityModel.java:50)
                                                                           at io.requery.query.element.QueryElement.from(QueryElement.java:307)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:601)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:612)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:839)
                                                                           at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:704)
                                                                           at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:665)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:642)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:612)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:839)
                                                                           at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:704)
                                                                           at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:665)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:642)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:612)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:839)
                                                                           at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:704)
                                                                           at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:665)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:642)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:612)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:839)
                                                                           at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:704)
                                                                           at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:665)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:642)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:612)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:839)
                                                                           at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:704)
                                                                           at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:665)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:642)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:612)
                                                                           at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:946)
                                                                           at io.requery.sql.EntityWriter.updateMappedAssociation(EntityWriter.java:839)
                                                                           at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:704)
                                                                           at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:665)
                                                                           at io.requery.sql.EntityWriter.update(EntityWriter.java:642)

**Comment by Agraphie** [comment]
Hi there,

can you please provide the steps (and necessary classes) to reproduce this error? Thanks.

**Comment by DreamerII** [comment]
this is random crash. I can`t describe steps to reproduce.

**Comment by Agraphie** [comment]
But then how can we help you? Could you provide the entities or better yet the app? We need some source code/some way to reproduce it in order to track down the error and help you.

**Comment by DreamerII** [comment]
@Entity
@Table(name = "books_from_library")
public interface ILibraryBook extends BaseBook {


    String getPublisherName();

    String getNarratorName();

    @OneToMany(mappedBy = "libraryBook", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    List<Chapter> getChapters();

    void setChapters(List<Chapter> chapters);

    @Column(value = "0")
    int getDownloadState(); // int downloadState = DOWNLOAD_STATE_NONE;

    double getDuration();

    String getGiftedByUser();

    String getGiftNote();

    boolean isFinished();

    boolean isSynchronizedWithServer();

    @ManyToOne
    User getOwner();

    boolean isReleased();

    long getBookSize();
}

**Comment by DreamerII** [comment]
I think problem when i update Chapter


@Entity
@Table(name = "chapters")
interface IChapter extends Parcelable {

    @Key
    long getId();

    String getTitle();

    String getUrlLow();

    String getUrlMiddle();

    String getUrlHigh();

    double getDuration();

    String getLocalUrl();

    @ManyToOne(cascade = {CascadeAction.SAVE})
    LibraryBook getLibraryBook();
}
