### ISSUE TITLE
H2 database - Column "id" not found

### ISSUE THREAD

**Issue by lehmanju** [requery/requery#684]
```
2017-09-19 17:54:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3180)
	at org.h2.jdbc.JdbcResultSet.findColumn(JdbcResultSet.java:189)
	at io.requery.sql.EntityWriter.readKeyFromResult(EntityWriter.java:325)
	at io.requery.sql.EntityWriter.readGeneratedKeys(EntityWriter.java:308)
	at io.requery.sql.EntityWriter.access$200(EntityWriter.java:69)
	at io.requery.sql.EntityWriter$4.read(EntityWriter.java:424)
	at io.requery.sql.PreparedQueryOperation.readGeneratedKeys(PreparedQueryOperation.java:95)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:56)
	at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
	at io.requery.query.BaseScalar.value(BaseScalar.java:48)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:458)
	at io.requery.sql.EntityWriter.insert(EntityWriter.java:412)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:204)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190)
	at io.requery.sql.KotlinEntityDataStore.insert(KotlinEntityDataStore.kt:119)
	at io.requery.async.KotlinCompletableEntityStore$insert$$inlined$execute$1.get(KotlinCompletableEntityStore.kt:85)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This error message occurs on an entity insert into a H2 database. I suspect it is caused by selecting its generated id. Maybe this is related: https://stackoverflow.com/questions/16804321/org-h2-jdbc-jdbcsqlexception-column-id-not-found

**Comment by lehmanju** [comment]
I did some debugging, ```SchemaModfier.createTables``` does not include any quotes and ```findColumn``` does not include any either.

**Comment by npurushe** [comment]
Can you post the generated create table statement (or at least the portion with the id column definition)? thanks

**Comment by lehmanju** [comment]
This is one insert statement: ```insert into AsUser (device_id, user_id) values (?, ?)```
and this one is executed directly afterwards: ```select id, device_id, user_id from AsUser where user_id = ?```

It all looks pretty straigthforward to me. I don't think the statement itself is the problem but something with ```findColumn``` on a ResultSet.

**Comment by lgadawski** [comment]
If in create table statement You use quotes then in inserts also You should use quotes. In given example:

> insert into AsUser ("device_id", "user_id") values (?, ?)

**Comment by lehmanju** [comment]
If I recall correctly, this is not an issue about quotes but a problem with the inner workings of specifically H2.

**Comment by lehmanju** [comment]
If I recall correctly, this is not an issue about quotes but a problem with the inner workings of specifically H2.

**Comment by lehmanju** [comment]
I think this 
https://github.com/requery/requery/blob/3a122fe086662f887e2f97f53a88fdf57b8bbdda/requery/src/main/java/io/requery/sql/EntityWriter.java#L324
line is responsible for that error message. To be clear, the exception does not occur on stdout but in <dbname>.trace.db (next to the database file).

**Comment by lehmanju** [comment]
In fact the column there is a column named "SCOPE_IDENTITY()".
