### ISSUE TITLE
Updating entity broken in 1.4.1 (after 6a6d4eb maybe)

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#698]
Updating a `JobOffer` with the same `remoteId` (i.e. `remoteId` doesn't change but property state is `MODIFIED`) causes a foreign key constraint error in `JobOfferStats`.

```
@Table(name = "IJobOffer")
@Entity(cacheable = false)
interface JobOffer : Parcelable, Persistable {
    @get:Key
    @get:Generated
    @get:Column(name = "_id")
    var localId: Int

    @get:Column(name = "id")
    var remoteId: Int?
}

@Table(name = "IJobOfferStats")
@Entity(cacheable = false)
interface JobOfferStats : Parcelable, Persistable {
    @get:Key
    @get:Generated
    @get:Column(name = "_id")
    var localId: Int

    @get:ForeignKey(
            update = ReferentialAction.CASCADE, referencedColumn = "id",
            references = JobOffer::class)
    var jobOfferId: Int
}
```

Stacktrace:

```
android.database.sqlite.SQLiteException: foreign key mismatch - 
        "IJobOfferStats" referencing "IJobOffer" (code 1): , while compiling: 
        update IJobOffer set authorId = ? ,banned = ? ,createdAt = ? ,description = ? ,endsAt = ? ,
        gender = ? ,id = ? ,localCanContributeToNotifications = ? ,localSeen = ? ,
        localShouldShowNotification = ? ,offerDuration = ? ,offerUntil = ? ,pendingCreate = ? ,
        pendingRequestId = ? ,pendingRetry = ? ,pendingStatus = ? ,place = ? ,salaryUnit = ? ,
        salaryValue = ? ,showCandidatesDuration = ? ,showCandidatesUntil = ? ,startsAt = ? ,
        status = ? ,updatedAt = ? where _id = ?
    at io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
    at io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:919)
    at io.requery.android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:522)
    at io.requery.android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:598)
    at io.requery.android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
    at io.requery.android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:37)
    at io.requery.android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:985)
    at io.requery.android.sqlitex.SqlitexPreparedStatement.<init>(SqlitexPreparedStatement.java:39)
    at io.requery.android.sqlitex.SqlitexConnection.prepareStatement(SqlitexConnection.java:121)
    at io.requery.sql.ConnectionDelegate.prepareStatement(ConnectionDelegate.java:225)
    at io.requery.sql.PreparedQueryOperation.prepare(PreparedQueryOperation.java:58)
    at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:51)
    at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
    at io.requery.query.BaseScalar.value(BaseScalar.java:48)
    at io.requery.sql.EntityWriter.update(EntityWriter.java:632)
    at io.requery.sql.EntityWriter.update(EntityWriter.java:542)
    at io.requery.sql.EntityDataStore.update(EntityDataStore.java:243)
    at io.requery.sql.KotlinEntityDataStore.update(KotlinEntityDataStore.kt:126)
    at XXX
```

Expected behavior:

No error because `CASCADE` kicks in.

Workaround:

Revert code in 6a6d4eb.

**Comment by noberasco** [comment]
I'm affected by this bug, too.
Reverting to release 1.4.0 also works around the issue ;-)

**Comment by npurushe** [comment]
This is happening because your foreign key `jobOfferId` is referencing a non-key column `JobOffer.remoteId (id)` See http://www.sqlite.org/foreignkeys.html#fk_indexes. Reverting that change is probably not a good idea as enabling foreign key constraints is required in order to get correct foreign key behavior in sqlite. This had been correct in the standard sqlite data source, but not the `sqlcipher` and `sqlite-support` sources which is what that change fixes.

If you need to keep this behavior you can override `onConfigure` and not enabled the constraints, however this means constraints will not be enforced correctly.
