### ISSUE TITLE
Upsert foreign keys

### ISSUE THREAD

**Issue by christianCallelero** [requery/requery#705]
Foreign key constraint When I'am upserting entities with existing foreign keys. Is there a way to do this?

`
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: CarMake.id (code 1555)
                                                                               at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                               at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:904)
                                                                               at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                                               at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                                               at io.requery.android.sqlite.SqlitePreparedStatement.executeUpdate(SqlitePreparedStatement.java:168)
                                                                               at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:54) 
                                                                               at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40) 
                                                                               at io.requery.query.BaseScalar.value(BaseScalar.java:48) 
                                                                               at io.requery.sql.EntityWriter.insert(EntityWriter.java:456) 
                                                                               at io.requery.sql.EntityWriter.cascadeWrite(EntityWriter.java:943) 
                                                                               at io.requery.sql.EntityWriter.cascadeKeyReference(EntityWriter.java:927) 
                                                                               at io.requery.sql.EntityWriter.insert(EntityWriter.java:445) 
                                                                               at io.requery.sql.EntityWriter.upsert(EntityWriter.java:489) 
                                                                               at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:281) 
                                                                               at io.requery.rx.SingleEntityStoreFromBlocking$8.call(SingleEntityStoreFromBlocking.java:137) 
                                                                               at rx.Single$4.call(Single.java:616) 
                                                                               at rx.Single$4.call(Single.java:610) 
                                                                               at rx.Single$1.call(Single.java:95) 
                                                                               at rx.Single$1.call(Single.java:75) 
                                                                               at rx.Single.subscribe(Single.java:1725) 
                                                                               at rx.Single.subscribe(Single.java:1802) 
                                                                               at rx.Single$19$1.call(Single.java:1857) 
                                                                               at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
`

**Comment by npurushe** [comment]
Can you expand on how you upsert your entities? It looks like there is a entity with `CarMake.id` already existing, is that `CarMake` what you're upserting or is through a cascading operation?

**Comment by christianCallelero** [comment]
For example table B is dependent on table A, Table A has an existing data. Now if I upsert a data into table B which has an existing foreign key in table A. It returns that error. I think it is inserting a new data in table A that will make it a duplicate so it throws errors. Does upserting checks if the foreign key is existing and will just update/ignore it.
