### ISSUE TITLE
java.lang.NullPointerException with JunctionTable

### ISSUE THREAD

**Issue by steelxtreme** [requery/requery#713]
hi, now i'm using @junctiontable with kotlin and I don't know is this works such @JoinTable JPA.
I have 3 tables:

`@Entity
 interface Country :Persistable{
        @get:Key
        var idcountry: Long
        var name: String
        var countryPrefix: String?
        @get:Convert(PointConverter::class)
        var  position: Point?
        var lang: String?

        @get:OneToMany( mappedBy = "idcountry")
        @get:Nullable
        val cities :Result<City>?

}

@Entity
data class City constructor(

        @get:Key
        var idcity: Long,

        @get:Key
        @get:ForeignKey( references =  Country::class, update = ReferentialAction.CASCADE)
        var idcountry: Long,

        var name: String,

        @get:Convert(PointConverter::class)
        var  position: Point?
        ) : Persistable
`

And 

`@Entity
interface Client:Persistable {

    @get:Key
    var idclient: Long

    var name: String?

    @get:ManyToMany
    @get:JunctionTable(name="client_country", columns = arrayOf( Column(name="idclient"), Column(name="idcountry")) )
    val clientCountries: Result<Country>?

    @get:ManyToMany
    @get:JunctionTable(name="client_city", columns = arrayOf(  Column(name="idcountry"), Column(name="idcity")))
    val clientCities: Result<City>?

}`

if i use:

` val result=   select(Client::class).get()` 

with
`result.each(Consumer { co->
           println("client"+co.name)
           co?.clientCountries!!.each({
               c-> println("     "+c.name)}
           )
       })`

is working like a charm, but if a use

`result.each(Consumer { co->
           println("client"+co.name)
           co?.clientCities!!.each({
               c-> println("     "+c.name)}
           )
       })`

is throwing an exception:

`Exception in thread "main" java.lang.NullPointerException
	at io.requery.sql.Attributes.get(Attributes.java:38)
	at io.requery.sql.EntityReader.associativeQuery(EntityReader.java:329)
	at io.requery.sql.EntityReader.refreshAssociation(EntityReader.java:258)
	at io.requery.sql.EntityReader.refresh(EntityReader.java:251)
	at io.requery.sql.EntityReader.refresh(EntityReader.java:182)
	at io.requery.sql.EntityReader.load(EntityReader.java:152)
	at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61)
	at io.requery.proxy.EntityProxy.get(EntityProxy.java:75)
	at io.requery.proxy.EntityProxy.get(EntityProxy.java:70)
	at com.cps.entity.ClientEntity.getClientCities(ClientEntity.java:235)
	at com.cps.server.MainKt$main$1$1.accept(Main.kt:27)
	at com.cps.server.MainKt$main$1$1.accept(Main.kt)
	at io.requery.query.BaseResult.each(BaseResult.java:144)
	at com.cps.server.MainKt$main$1.invoke(Main.kt:26)
	at com.cps.server.MainKt$main$1.invoke(Main.kt)
	at io.requery.kotlin.BlockingEntityStore$DefaultImpls.invoke(EntityStore.kt:150)
	at io.requery.sql.KotlinEntityDataStore.invoke(KotlinEntityDataStore.kt:39)
	at com.cps.server.MainKt.main(Main.kt:21)`

How is the right way to use Junction table if the join table has three keys?

TABLE client_city
(
  idclient bigint NOT NULL,
  idcountry bigint NOT NULL,
  idcity bigint NOT NULL,
)

**Comment by npurushe** [comment]
Thanks for reporting yes that shouldn't throw an NPE, it's not working because there is not good support for composite keys in a many-to-many relationship, something which should be fixed in the next major release.

**Comment by steelxtreme** [comment]
Hi i guess this happens because I am using  2 columns values and should be 3 columns, but when I set 3 : 


    @get:ManyToMany
    @get:JunctionTable(name="client_city", columns=arrayOf(   Column(name="idclient"), Column(name="idcountry"),Column(name="idcity")))
    val clientCities: Result<City>?

i got 

`e: java.lang.IllegalStateException: failed to analyze: java.lang.ArrayIndexOutOfBoundsException: 2`

In generation code stage.
