### ISSUE TITLE
(Lombok) Unidirectional OneToOne with nullable FK

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#715]
Hi,

suppose I have an entity A which references another entity B via `@OneToOne`. As it is unidorectional I need to put `@ForeignKey` in entity A. As that reference can be `null`, I would like to put `@Nullable` on it as well, but this will lead to a code generation error.  On the other hand, now I get this exception

```Java
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object io.requery.util.function.Supplier.get()' on a null object reference
	at io.requery.sql.Attributes.get(Attributes.java:38)
	at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:678)
	at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:666)
	at io.requery.sql.EntityWriter.update(EntityWriter.java:640)
	at io.requery.sql.EntityWriter.upsert(EntityWriter.java:518)
	at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:281)
	at io.requery.reactivex.WrappedEntityStore$8.call(WrappedEntityStore.java:138)
```

**Comment by npurushe** [comment]
Can you also post the Code generation error? thanks

**Comment by Agraphie** [comment]
The code generation error is `Error:(23, 1) error: annotation type not applicable to this kind of declaration`. But I cannot reproduce the whole issue in a clean project. In a clean project I can add `@Nullable` to `@ForeignKey @OneToOne` and I also don't get the exception above. If you don't have any ideas what I could try I will try to reproduce the whole issue and otherwise close this bug.

**Comment by npurushe** [comment]
Doesn't look like there is any possible way to fix this from the requery processor side.
