### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lrx/subjects/SerializedSubject;

### ISSUE THREAD

**Issue by muldy** [requery/requery#720]
Hi!
I'm getting started with requery... I can't seem to get past this:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: pt.sage.gesrest.takeorderkotlin, PID: 22075
                  java.lang.NoClassDefFoundError: Failed resolution of: Lrx/subjects/SerializedSubject;
                      at io.requery.rx.TypeChangeListener.<init>(TypeChangeListener.java:41)
                      at io.requery.rx.RxSupport.<clinit>(RxSupport.java:36)
                      at io.requery.rx.RxSupport.toReactiveStore(RxSupport.java:42)
                      at pt.sage.gesrest.takeorderkotlin.MainActivity.onCreate(MainActivity.kt:33)
                      at android.app.Activity.performCreate(Activity.java:6251)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.subjects.SerializedSubject" on path: DexPathList[[zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/base.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_dependencies_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_0_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_1_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_2_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_3_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_4_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_5_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_6_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_7_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_8_apk.apk", zip file "/data/app/pt.sage.gesrest.takeorderkotlin-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/pt.sage.gesrest.takeorderkotlin-1/lib/arm, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at io.requery.rx.TypeChangeListener.<init>(TypeChangeListener.java:41) 
                      at io.requery.rx.RxSupport.<clinit>(RxSupport.java:36) 
                      at io.requery.rx.RxSupport.toReactiveStore(RxSupport.java:42) 
                      at pt.sage.gesrest.takeorderkotlin.MainActivity.onCreate(MainActivity.kt:33) 
                      at android.app.Activity.performCreate(Activity.java:6251) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                  	Suppressed: java.lang.ClassNotFoundException: rx.subjects.SerializedSubject
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 17 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

I have no idea on what this problem is...

Here's my gradle.
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "pt.sage.gesrest.takeorderkotlin"
        minSdkVersion 22
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding {
        enabled = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile 'io.reactivex.rxjava2:rxjava:2.1.1'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'


    //retrofit
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    //requery
    compile 'io.requery:requery:1.4.1'
    compile 'io.requery:requery-android:1.4.1' // for android
    annotationProcessor 'io.requery:requery-processor:1.4.1'

    kapt 'io.requery:requery-processor:1.4.1'
}
kapt {
    generateStubs = true
}
```

Thanks in advance

**Comment by npurushe** [comment]
Hi for RxJava 2 you should use the classes in `io.requery.reactivex` instead of `io.requery.rx`. This is something in the process of being cleaned up as v1 support is being deprecated.

**Comment by muldy** [comment]
Thank you!
