### ISSUE TITLE
Multi-column unique index does not work

### ISSUE THREAD

**Issue by wenLiangcan** [requery/requery#754]
This is the table definition code I just modified from the [wiki](https://github.com/requery/requery/wiki/Defining-Entities#multi-column-unique-index).    
```kotlin
@Entity
interface Person {
    @get:Index("name_index")
    @get:Column(unique = true)
    val firstName: String

    @get:Index("name_index")
    @get:Column(unique = true)
    val lastName: String
}
```

I ran these insertion statements under an` Android` Runtime simulated by [`Robolectrictest`](http://robolectric.org/):
```kotlin

import io.requery.Persistable
import io.requery.android.sqlite.DatabaseSource
import io.requery.kotlin.*
import io.requery.sql.KotlinEntityDataStore
import io.requery.sql.TableCreationMode
import org.junit.*
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config
import model.*

@RunWith(RobolectricTestRunner::class)
@Config(manifest = Config.NONE)
class DatabaseUnitTests {

    lateinit var data: KotlinEntityDataStore<Persistable>

    @Before
    fun setup() {
        val source = DatabaseSource(RuntimeEnvironment.application, Models.DEFAULT, 1)
        source.setTableCreationMode(TableCreationMode.DROP_CREATE)
        data = KotlinEntityDataStore<Persistable>(source.configuration)
    }

    @Test()
    fun test() {
        val p1 = PersonEntity()
        p1.setFirstName("A")
        p1.setLastName("1")
        data.insert(p1)

        val p2 = PersonEntity()
        p2.setFirstName("A")
        p2.setLastName("2")
        data.insert(p2)
    }
}

```   

And the second insertion failed with this exception:
```
... 1 more
Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [19] DB[1] step() [insert into Person (firstName, lastName) values (?, ?)]DB[1][C] [column firstName is not unique]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:725)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:719)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.executeForChangedRowCount(ShadowSQLiteConnection.java:651)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativeExecuteForChangedRowCount(ShadowSQLiteConnection.java:264)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativeExecuteForChangedRowCount(ShadowSQLiteConnection.java:259)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$executeForChangedRowCount(SQLiteConnection.java:727)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java)
	at android.database.sqlite.SQLiteSession.$$robo$$executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java)
	at android.database.sqlite.SQLiteStatement.$$robo$$executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java)
	at 
	... 
```

Seems this [issue](https://github.com/requery/requery/issues/252#issuecomment-253445439) does not fixed?

**Comment by npurushe** [comment]
In this case you have a unique constraint on the `firstName` column, so you cannot insert another record that has a `firstName` of `A`

**Comment by wenLiangcan** [comment]
@npurushe Isn't it the purpose of a multi-column unique index is creating unique constraints spanning multiple columns? Just like the case described in the [link](https://github.com/requery/requery/issues/252#issuecomment-253445439) I referenced above, 'A 1' should be considered different from 'A 2'.

**Comment by npurushe** [comment]
The `@Column(unique)` attribute applies to the column definition, not to the index definition, you can use [`@Table(uniqueIndexes=`](http://requery.github.io/javadoc/io/requery/Table.html#uniqueIndexes--) to indicate which indexes are unique. Hope that helps!

**Comment by wenLiangcan** [comment]
@npurushe Thanks for this info, mybe the wiki page is a bit out of date?     

After modified my code to use `uniqueIndexes`    
```kotlin
@Table(uniqueIndexes = arrayOf("name_index"))
@Entity
interface Person: Persistable, Parcelable {
    @get:Index("name_index")
    @get:Column(nullable = false)
    var firstName: String

    @get:Index("name_index")
    @get:Column(nullable = false)
    var lastName: String
}
```      

I got another error
```
Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() create table (firstName varchar(255) not null, lastName varchar(255) not null) [near "(": syntax error]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
    ...
```
