### ISSUE TITLE
Running the Requery APT Processor breaks builds?

### ISSUE THREAD

**Issue by pirogoeth** [requery/requery#76]
On my Android project, adding the `apt` line with the rest of the requery deps causes the build to break. I have no clue why and it doesn't make much sense. When it is commented out, builds succeed and run, but I'm assuming the models will not work at all.

When it's enabled, Gradle builds succeed, but when launching, I get this enormous stack trace:
```
04-09 21:56:53.968 14530-14530/com.uniform_imperials.herald E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.uniform_imperials.herald, PID: 14530
                                                                              java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.uniform_imperials.herald.MainApplication
                                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
                                                                                  at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                               Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.uniform_imperials.herald.MainApplication
                                                                                  at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:217)
                                                                                  at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:236)
                                                                                  at android.app.Application.attach(Application.java:187)
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:997)
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:981)
                                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
                                                                                  at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: java.lang.ClassNotFoundException: com.uniform_imperials.herald.MainApplication
                                                                                  at java.lang.Class.classForName(Native Method)
                                                                                  at java.lang.Class.forName(Class.java:324)
                                                                                  at java.lang.Class.forName(Class.java:285)
                                                                                  at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:205)
                                                                                  at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:236) 
                                                                                  at android.app.Application.attach(Application.java:187) 
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:981) 
                                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:573) 
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
                                                                                  at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.uniform_imperials.herald.MainApplication" on path: DexPathList[[zip file "/data/app/com.uniform_imperials.herald-2/base.apk"],nativeLibraryDirectories=[/data/app/com.uniform_imperials.herald-2/lib/arm, /data/app/com.uniform_imperials.herald-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                  at java.lang.Class.classForName(Native Method) 
                                                                                  at java.lang.Class.forName(Class.java:324) 
                                                                                  at java.lang.Class.forName(Class.java:285) 
                                                                                  at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:205) 
                                                                                  at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:236) 
                                                                                  at android.app.Application.attach(Application.java:187) 
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:981) 
                                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:573) 
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
                                                                                  at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.uniform_imperials.herald.MainApplication" on path: DexPathList[[dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-support-annotations-23.3.0_f1725d50a60d26b513183d454b93e2d8a8ef098b-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-rxjava-1.1.2_928a6f17bc0120519cc9e2505653a79076ddcdbe-classes.dex", dex file "/data/data/com.uniform_imperials.herald/files/instant-run/dex/slice-requery-1.0.0-beta12_e67f82482279ef4801fdfba7841576d51b16208b-classes.dex", dex fil
```

And here is my `build.gradle`:
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    compileOptions {
        encoding "UTF-8"
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    defaultConfig {
        applicationId "com.uniform_imperials.herald"
        minSdkVersion 20
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dataBinding {
        enabled = true
    }
}

repositories {
    jcenter()
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12-beta-3'

    // Design and compat libraries.
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.android.support:recyclerview-v7:23.3.0'
    compile 'com.android.databinding:library:1.0-rc5'
    compile 'com.android.databinding:adapters:1.0-rc5'
    compile 'com.github.mmin18:flexlayout:1.2.0'

    // Development and debugging dependencies.
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'me.dm7.barcodescanner:zxing:1.8.4'
    compile 'com.github.android-cjj:JJSearchViewAnim:49a43019d6'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.joshdholtz.sentry:sentry-android:1.2.1'
    compile 'io.reactivex:rxjava:1.1.2'
    compile 'io.reactivex:rxandroid:1.1.0'

    // Database & ORM dependencies
    compile 'io.requery:sqlite-android:3.12.0'
    compile 'io.requery:requery:1.0.0-beta12'
    compile 'io.requery:requery-android:1.0.0-beta12'
    apt 'io.requery:requery-processor:1.0.0-beta12'
}
```

Any ideas?

**Comment by npurushe** [comment]
Looks like you are using Android Studio 2.0 Instant Run? Try a full clean/rebuild once without instant run. Also are you using the final release version of AS 2.0?

**Comment by pirogoeth** [comment]
I am using the final release of AS 2.0. I'm gonna clean up my whole Gradle environment, rebuild, and try to relaunch. I'll post back in a few minutes.

**Comment by pirogoeth** [comment]
@npurushe No, a full clean did not fix it. Still crashes with the same exception.

**Comment by npurushe** [comment]
It looks similar to this issue https://code.google.com/p/android/issues/detail?id=199327. Can you check you are using the android gradle plugin 2.0 and not a earlier version. Also if you turn off instant run, build and deploy it should work, then try to turn instant run back on.

**Comment by pirogoeth** [comment]
Definitely using gradle version 2.0.0. Completely disabled instant run and it still crashes. Exception is shorter, but same-ish chain of "class not found".

```
04-09 22:38:06.481 19754-19754/com.uniform_imperials.herald E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.uniform_imperials.herald, PID: 19754
                                                                              java.lang.RuntimeException: Unable to instantiate application com.uniform_imperials.herald.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.uniform_imperials.herald.MainApplication" on path: DexPathList[[zip file "/data/app/com.uniform_imperials.herald-2/base.apk"],nativeLibraryDirectories=[/data/app/com.uniform_imperials.herald-2/lib/arm, /data/app/com.uniform_imperials.herald-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
                                                                                  at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.uniform_imperials.herald.MainApplication" on path: DexPathList[[zip file "/data/app/com.uniform_imperials.herald-2/base.apk"],nativeLibraryDirectories=[/data/app/com.uniform_imperials.herald-2/lib/arm, /data/app/com.uniform_imperials.herald-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:981)
                                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
                                                                                  at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                              	Suppressed: java.lang.ClassNotFoundException: com.uniform_imperials.herald.MainApplication
                                                                                  at java.lang.Class.classForName(Native Method)
                                                                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                  		... 12 more
                                                                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

Tried again after a clean and re-run, but it's the same result.

**Comment by npurushe** [comment]
Yeah that's pretty strange. I'm guessing the `com.uniform_imperials.herald.MainApplication` is not in your apk. Did you just add a custom Application to your app? I would delete the apk file and make sure it is built cleanly, also uninstall the app from from the device/emulator and redeploy it, also try removing the custom application class and then adding it back later.

**Comment by pirogoeth** [comment]
I did add a custom application entrypoint, but it's been working and starting fine up until I started running the apt... I've just uninstalled and I'll try cleaning up the build artifacts.

**Comment by pirogoeth** [comment]
@npurushe Is there a way to limit the packages that the requery processor runs on?

**Comment by npurushe** [comment]
It runs on any package that has the `io.requery` or `javax.persistence` annotations for the project the processor is specified on. Is there an issue you're encountering with a particular package or classes?

**Comment by pirogoeth** [comment]
No, was just curious because of my issue.

**Comment by npurushe** [comment]
In your subclass of application do you have any dependencies on generated code? Is the `MainApplication` actually in your apk that is deployed?

**Comment by pirogoeth** [comment]
I apologize for being dumb; Apparently my eyes missed the part that said Java 8 was required. Got switched over to the latest Java 8 JDK and things are working now. Thanks!

**Comment by npurushe** [comment]
Glad you found it!
