### ISSUE TITLE
io.requery.meta.NotMappedException when trying to insert standalone and ManyToMany-related entities

### ISSUE THREAD

**Issue by kkaun** [requery/requery#776]
This issue(or simple misunderstanding?) is kinda frustrating because it's not my first project with requery: 
recently I used quite simple one-directional cascade schemes and all worked wery well even using Kotlin. 

But now when I succesfully pass the build and try to insert things like standalone entity with no relations 
or entities with mutidirectional ManyToMany relationships it throws only one exception: **io.requery.meta.NotMappedException**.

Here are desired models that cause to the exception each time when trying to insert or upsert them with or without handwritten SQLite queries:

- Standalone (no relations):

```
	@Entity(name = "ArticleEntity")
	@Table(name = "article")
	interface Article : Persistable {

		@get:ForeignKey
		@get:Key
		@get:Column(name = "article_path_name", nullable = false)
		var pathName: String
	}
```

- Related ones: 

```
	@Entity(name = "CreationEntity")
	@Table(name = "creation", uniqueIndexes = ["creation_path_name_idx"])
	interface Creation : Persistable {

		@get: ForeignKey
		@get:Key
		@get:Index("creation_path_name_idx")
		@get:Column(name = "creation_path_name", nullable = false)
		var pathName: String

		@get:Column(name = "title", nullable = false)
		var title: String

		@get:Column(name = "description", nullable = false)
		var description: String

		@get:Column(name = "lat", nullable = false)
		var lat: Double

		@get:Column(name = "lng", nullable = false)
		var lng: Double

		@get: JunctionTable(type = CreationSearchResult::class)
		@get: ManyToMany
		var creators: Set<Creator>

		@get: JunctionTable(type = CreationSearchResult::class)
		@get: ManyToMany
		var styles: Set<Style>
	}
	
	 //---------------------------------------------------------------------------
	
	@Entity(name = "CreationSearchResultEntity")
	@Table(name = "creation_search_result")
	interface CreationSearchResult : Persistable {

		@get: ForeignKey(references = Creation::class)
		@get:Key
		val creationPathName: String

		@get: ForeignKey(references = Creator::class)
		@get:Key
		val creatorPathName: String

		@get: ForeignKey(references = Style::class)
		val stylePathName: String
	}

	 //---------------------------------------------------------------------------

	@Entity(name = "CreatorEntity")
	@Table(name = "style", uniqueIndexes = ["creator_path_name_idx"])
	interface Creator : Persistable {

		@get: ForeignKey
		@get:Key
		@get:Index("creator_path_name_idx")
		@get:Column(name = "creator_path_name", nullable = false)
		var pathName: String

		@get: ManyToMany
		var creations: Set<Creation>
	}

	 //---------------------------------------------------------------------------

	@Entity(name = "StyleEntity")
	@Table(name = "style", uniqueIndexes = ["style_path_name_idx"])
	interface Style : Persistable {

		@get: ForeignKey
		@get:Key
		@get:Index("style_path_name_idx")
		@get:Column(name = "style_path_name", nullable = false)
		var pathName: String

		@get: ManyToMany
		var creations: Set<Creation>
	}
```

Logically, I understand that if I make model even more complicated and make all relationships "one-directional" by my own working examples from the last project, it'll work.
But I wonder, is it the only way to get rid of mentioned exception with current model?
Thanks in advance.

**Comment by npurushe** [comment]
Hi could you post the full stack trace from the `NotMappedException` you're getting? that will help identity which relation in your example the issue relates to. Thanks

**Comment by kkaun** [comment]
Hi, sure! Below is typical stack trace for my current project containing models mentioned in the issue.

Btw, I i tried to use Int `_id`s in almost all present entities - for now all stays the same :( 
I even tried to relate all entities in the project through one `RootEntity` - and cauht exactly the same exception, but for that `RootEntity`! 

Out of options, really. Just hope for advice on which direction to move.
```
05-17 11:19:05.280 30526-30526/com.kkaun.archilearn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kkaun.archilearn, PID: 30526
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kkaun.archilearn/com.kkaun.archilearn.ui.materials.splash.SplashActivity}: io.requery.meta.NotMappedException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2706)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: io.requery.meta.NotMappedException
        at io.requery.meta.ImmutableEntityModel.typeOf(ImmutableEntityModel.java:52)
        at io.requery.sql.SchemaModifier.createForeignKeyColumn(SchemaModifier.java:468)
        at io.requery.sql.SchemaModifier.tableCreateStatement(SchemaModifier.java:441)
        at io.requery.sql.SchemaModifier.createTables(SchemaModifier.java:151)
        at io.requery.sql.SchemaModifier.createTables(SchemaModifier.java:128)
        at io.requery.android.sqlite.DatabaseSource.onCreate(DatabaseSource.java:201)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at io.requery.android.sqlite.DatabaseSource.getConnection(DatabaseSource.java:230)
        at io.requery.sql.EntityDataStore$DataContext.getConnection(EntityDataStore.java:635)
        at io.requery.sql.EntityDataStore.checkConnectionMetadata(EntityDataStore.java:573)
        at io.requery.sql.EntityDataStore$DataContext.getTransactionMode(EntityDataStore.java:746)
        at io.requery.sql.ThreadLocalTransaction.begin(ThreadLocalTransaction.java:56)
        at io.requery.sql.ThreadLocalTransaction.begin(ThreadLocalTransaction.java:48)
        at io.requery.sql.TransactionScope.<init>(TransactionScope.java:39)
        at io.requery.sql.TransactionScope.<init>(TransactionScope.java:33)
        at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:197)
        at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:191)
        at io.requery.sql.KotlinEntityDataStore.insert(KotlinEntityDataStore.kt:119)
        at com.kkaun.archilearn.data.articles.ArticlesDbRepository.saveAllStaticArticles(ArticlesDbRepository.kt:26)
        at com.kkaun.archilearn.util.DataExtensionsKt.populateAllPermTablesWithProgress(DataExtensions.kt:49)
        at com.kkaun.archilearn.ui.materials.splash.SplashActivity.onCreate(SplashActivity.kt:82)
        at android.app.Activity.performCreate(Activity.java:6864)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
```
