### ISSUE TITLE
SQL error or missing database (near "autoincrement": syntax error)

### ISSUE THREAD

**Issue by rerzer** [requery/requery#817]
I'm trying to get requery + SQLite to work under Kotlin.

I don't see any apparent issues with my models or the database setup.

Stacktrace:
```Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener beforeExecuteUpdate
INFO: beforeExecuteUpdate org.sqlite.jdbc4.JDBC4Statement@29176cc1 sql:
drop table if exists QueryItem 
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener afterExecuteUpdate
INFO: afterExecuteUpdate 0
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener beforeExecuteUpdate
INFO: beforeExecuteUpdate org.sqlite.jdbc4.JDBC4Statement@29176cc1 sql:
drop table if exists Beer 
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener afterExecuteUpdate
INFO: afterExecuteUpdate 0
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener beforeExecuteUpdate
INFO: beforeExecuteUpdate org.sqlite.jdbc4.JDBC4Statement@29176cc1 sql:
drop table if exists Details 
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener afterExecuteUpdate
INFO: afterExecuteUpdate 0
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener beforeExecuteUpdate
INFO: beforeExecuteUpdate org.sqlite.jdbc4.JDBC4Statement@29176cc1 sql:
create table Details (id integer primary key autoincrement not null, description varchar(255), details varchar(255), productID varchar(255), stock integer not null)
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener afterExecuteUpdate
INFO: afterExecuteUpdate 0
Sep 06, 2018 1:49:41 PM io.requery.sql.LoggingListener beforeExecuteUpdate
INFO: beforeExecuteUpdate org.sqlite.jdbc4.JDBC4Statement@29176cc1 sql:
create table Beer (id integer autoincrement not null, parseDate integer not null, details integer, image varchar(255), name varchar(255), price float not null, url varchar(255), foreign key (details) references Details (id) on delete cascade, primary key (id, parseDate))
Exception in thread "main" io.requery.sql.TableModificationException: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "autoincrement": syntax error)
	at io.requery.sql.SchemaModifier.createTables(SchemaModifier.java:162)
	at io.requery.sql.SchemaModifier.createTables(SchemaModifier.java:128)
	at MainKt.main(main.kt:18)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "autoincrement": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:60)
	at io.requery.sql.SchemaModifier.createTables(SchemaModifier.java:153)
	... 2 more
```

DB Setup:

```fun main(args: Array<String>) {
    val datasource = SQLiteDataSource()
    datasource.url = "jdbc:sqlite:beers.db"

    val config = ConfigurationBuilder(datasource, Models.DEFAULT)
            .useDefaultLogging()
            .build()

    val tables = SchemaModifier(config)
    tables.createTables(TableCreationMode.DROP_CREATE)

    val dataStore = KotlinEntityDataStore<Persistable>(config)
}
```

Models:

```@Entity
interface Beer : Persistable {

    @get:Key
    @get:Generated
    var id: Int

    @get:Key
    var parseDate: Long

    var price: Float
    var name: String
    var url: String
    var image: String

    @get:OneToOne(mappedBy = "beer")
    @get:ForeignKey
    var details: Details

    @get:OneToMany(mappedBy = "beer")
    var queryResults: Set<QueryItem>
}

@Entity
interface Details : Persistable {
    @get:Key
    @get:Generated
    var id: Int

    @get:OneToOne(mappedBy = "details")
    var beer: Beer

    var productID: String
    var stock: Int
    var description: String
    var details: MutableMap<String, String>
}

@Entity
interface QueryItem : Persistable {

    @get:Key
    @get:Generated
    var id: Int

    @get:Key
    var queryDate: Long

    @get:ManyToOne
    var beer: Beer

    var name: String
    var style: String
    var styleScore: Float
    var overallScore: Float
    var averageRating: Float
    var ratingCount: Int
    var imageUrl: String
}
```

Is there anything obviously wrong with this code? If so please point me in the right direction.

**Comment by npurushe** [comment]
In this particular case you have two @Key fields, but in SQLite you can only have 1 if the Key is generated.
