### ISSUE TITLE
Bulk insert in Kotlin not working

### ISSUE THREAD

**Issue by jeffzoch** [requery/requery#830]
1. Cannot complete type inference between Iterable<E> and List<E> when doing bulk insert on a stream. 
Here is a dummy example that fails. 
```
ds.insert(ticketBuilders.map{ ticketBuilder ->
            Ticket(
                    name = "ted")
        })
```

Even after adding an annotation s.t.
```
ds.insert<Iterable<Ticket>>(ticketBuilders.map{ ticketBuilder ->
            Ticket(
                    name = "ted")
        })
```
It fails with
```
io.requery.meta.NotMappedException
	at io.requery.meta.ImmutableEntityModel.typeOf(ImmutableEntityModel.java:52)
	at io.requery.sql.EntityDataStore$DataContext.proxyOf(EntityDataStore.java:609)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:198)
	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:191)
	at io.requery.sql.KotlinEntityDataStore.insert(KotlinEntityDataStore.kt:119)
```

**Comment by debop** [comment]
NotMappedException cause by "Entity not registered in EntityModel"
Check `Ticket` is registered your `EntityModel` (like `Models.DEFAULT`)

**Comment by jeffzoch** [comment]
@debop It is registered. If I do:
```
ticketBuilders.map{ ticketBuilder ->
            Ticket(
                    name = "ted")
        }.forEach{t -> ds.insert(t) })
```
then this compiles and works great. I wanted to try inserting them all at once though and this is where it fails.

**Comment by jeffzoch** [comment]
I was able to fix this by using named parameters like so:

```
ds.insert(entities = ticketBuilders.map{ ticketBuilder ->
            Ticket(
                    name = "ted")
        })
```
in order to resolve the ambiguity. I think this ambiguity should be resolved as the typical solution in kotlin (imo) is to add type inferences (which the error suggests) when in reality the named parameter resolves that ambiguity.
