### ISSUE TITLE
Bulk inserts 1 row affected actual -2

### ISSUE THREAD

**Issue by jeffzoch** [requery/requery#831]
I recently added bulk insert (had a previous issue about how to do so) and it compiles fine and works with an h2 database. I tried using an oracle database and got the following: 
`io.requery.sql.RowCountException: Ticket: expected 1 row affected actual -2`
The insert works when I iterate through my list of "tickets" and insert them, but if I insert an iterable it fails with the above error.
```
master_1  | io.requery.sql.RowCountException: Ticket: expected 1 row affected actual -2
master_1  | 	at io.requery.sql.EntityWriter.checkRowsAffected(EntityWriter.java:181)
master_1  | 	at io.requery.sql.EntityWriter.batchInsert(EntityWriter.java:291)
master_1  | 	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:229)
master_1  | 	at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:217)
master_1  | 	at io.requery.sql.KotlinEntityDataStore.insert(KotlinEntityDataStore.kt:120)
master_1  | 	at com.salesforce.master.tables.ticket.TicketRepositoryImpl.create(repository.kt:225)
```
is the full error

**Comment by steelxt** [comment]
Is this solved?

I'm having exactly the same issue
