### ISSUE TITLE
Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by jbenezech** [requery/requery#853]
I started to notice this exception on some devices in my production app. So far, all devices having this issue are HUAWEI (different models).

I have a table with about 4000 entries in it. This happens when doing a select by primary key on it.

```
UserProfileEntity dbUserProfile = mDatabaseService.getDataStore().findByKey(UserProfileEntity.class, dto.id).blockingGet();
```
which results in this sql:

`
select identity, address, address2, addressLatitude, addressLongitude, birthday, city, cityCode, country, countryCode, email, facebookId, firstname, gender, lastname, latitude, longitude, nickname, phone, profileCompleted, relationshipStatus from UserProfile where identity = ? 
`

Stack trace is

`
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. at android.database.CursorWindow.<init>(CursorWindow.java:110) at android.database.CursorWindow.<init>(CursorWindow.java:132) at net.sqlcipher.CursorWindow.<init>(CursorWindow.java:54) at net.sqlcipher.database.SQLiteCursor.fillWindow(SQLiteCursor.java:279) at net.sqlcipher.database.SQLiteCursor.getCount(SQLiteCursor.java:271) at net.sqlcipher.AbstractCursor.moveToPosition(AbstractCursor.java:178) at android.database.CursorWrapper.moveToPosition(CursorWrapper.java:197) at io.requery.android.sqlite.CursorResultSet.<init>(CursorResultSet.java:69) at io.requery.android.sqlcipher.SqlCipherPreparedStatement.executeQuery(SqlCipherPreparedStatement.java:140) at io.requery.sql.SelectResult.createIterator(SelectResult.java:125) ... 32 more
`

Reports include Android memory status which seem fine

`
 ( Memory TOTAL =3690), ( Memory USED =14), ( Memory THRESH =216), ( Memory AVAIL =1420), ( Memory LOW =false)
`

**Comment by npurushe** [comment]
I noticed you are using SqlCipher based on the stack do you have the same problem if using the regular android SQLite instance?

**Comment by jbenezech** [comment]
I unfortunately don't have a Huawei device to test that on and don't really want to push a different db in prod just for testing. Let me see if I can get hold of a device where I can reproduce the issue. I'll update the issue then.
