### ISSUE TITLE
Null pointer exception in OneToMany 

### ISSUE THREAD

**Issue by steelxtreme** [requery/requery#874]
Hi, I ha the following tables:

`@Entity
@Table(name = "wuser")
//@JsonIgnoreProperties(ignoreUnknown=true)
interface  User:Persistable,Serializable {

    @get:Key
    @get:Generated
     val id: Long?

     var email: String?

     var lastName: String?

     var username: String?

     var name: String?

     var password: String?

     var phone: String?

    @get:OneToMany( mappedBy = "wuser_id")
    @get:Nullable
    val userPockets :Result<UserPocket>?
}`

and

`@Entity
interface UserPocket:Persistable {

    @get:Key
    @get:Column(name="wuser_id")
    var  userId: Long?
    @get:Key
    @get:Column(name="pocket_id")
    var  pocketId: Long?
    var  description: String?

    @get:Column(name = "created_date")
    var  createdDate: Long?

    var active:Boolean

    // bi-directional many-to-one association to ClientPocket
   /* @get:ManyToOne
    @get:ForeignKey
     @get:Column(name = "id_pocket_type")
    var  pocketType: PocketType?*/

}`

and this is the stacktrace:
`java.lang.NullPointerException
	at io.requery.sql.Attributes.get(Attributes.java:38)
	at io.requery.sql.EntityReader.associativeQuery(EntityReader.java:303)
	at io.requery.sql.EntityReader.refreshAssociation(EntityReader.java:258)
	at io.requery.sql.EntityReader.refresh(EntityReader.java:251)
	at io.requery.sql.EntityReader.refresh(EntityReader.java:182)
	at io.requery.sql.EntityReader.load(EntityReader.java:152)
	at io.requery.proxy.EntityProxy.loadProperty(EntityProxy.java:61)
	at io.requery.proxy.EntityProxy.get(EntityProxy.java:75)
	at io.requery.proxy.EntityProxy.get(EntityProxy.java:70)
	at com.cps.common.entity.UserEntity.getUserPockets(UserEntity.java:366)
	at com.cps.gateway.ApiGatewayVerticle$start$authProvider$1.authenticate(ApiGatewayVerticle.kt:68)
	at com.cps.gateway.auth.WalletLoginHandler.handle(WalletLoginHandler.kt:37)
	at com.cps.gateway.auth.WalletLoginHandler.handle(WalletLoginHandler.kt:16)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:95)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:42)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:529)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:515)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:172)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:134)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

I don't if UserPocket double key is tha cause of  the error.

thanks in advance.

**Comment by steelxtreme** [comment]
after many hours struggling with this and changing some  annotations was solved by adding @ForeingKey with some cofigurations.


   @get:Key
    @get:Column(name="wuser_id")
    @get:ForeignKey(references = User::class , referencedColumn = "id")
    var  userId: Long?
