### ISSUE TITLE
No entry point stacktrace with NoSuchElementException

### ISSUE THREAD

**Issue by s3r6** [requery/requery#889]
Getting such error possibly from simple select
```
db.select(SomeEntity::class).where(SomeEntityType.ID.eq(id)).get()
                .observable()
                .doOnError { /*does not called!*/ }
```
Stacktrace does not contain any pointer to code, exception is thrown from `io.reactivex.internal.operators.observable.ObservableSingleSingle.SingleElementObserver#downstream`: `downstream.onError(new NoSuchElementException());`

How to debug this?
```
W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.util.NoSuchElementException
W/System.err:     at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onComplete(ObservableOnErrorNext.java:115)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onComplete(ObservableFromPublisher.java:46)
W/System.err:     at io.requery.reactivex.QuerySubscription.requestAll(QuerySubscription.java:64)
W/System.err:     at io.requery.reactivex.QuerySubscription.request(QuerySubscription.java:47)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onSubscribe(ObservableFromPublisher.java:64)
W/System.err:     at io.requery.reactivex.ReactiveResult$1.subscribeActual(ReactiveResult.java:56)
W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:14827)
W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:14774)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
W/System.err:     at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
W/System.err:     at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7000)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
W/System.err: Caused by: java.util.NoSuchElementException
W/System.err: 	... 32 more
```

**Comment by s3r6** [comment]
This error is produced by `.observable().firstOrError()` or `.observable().singleOrError()` when no elements are available.
